### ISSUE TITLE
Issue validating url

### ISSUE THREAD

**Issue by afuggini** [aldeed/meteor-simple-schema#102]
Hi,

I'm trying to validate an optional URL field with `regEx: SimpleSchema.RegEx.Url`. The problem is that when I use `check(doc, mySchema)` server side, match fails if URL is empty, even though i'm using `optional: true`. 

How can I make check() work and allow an empty URL?

Thanks.

**Comment by Deelux** [comment]
How and where should I call simpleSchema.clean? I have the same issue. Getting a provide valid url on a empty string.
