### ISSUE TITLE
URL regex throws errors

### ISSUE THREAD

**Issue by subhog** [aldeed/meteor-simple-schema#113]
I got the following error today:
`an error occurred while executing regular expression`

![screen shot 2014-07-04 at 14 19 59](https://cloud.githubusercontent.com/assets/1041199/3481668/92072416-0375-11e4-8da0-d021e43b2ceb.png)

Reproduction:
- Create a form with custom schema and a field with `type: String` and `regEx: SimpleSchema.RegEx.Url`
- Submit the form, fails as the field is empty
- Fill the field with `http://abc.aaaaa`
- Add a few more letters `a` to the end
- Soon the error will appear

**Comment by aldeed** [comment]
Not sure what to do about this for now.
