### ISSUE TITLE
Optional sub-schemas are either broken or unintuitive

### ISSUE THREAD

**Issue by vthunder** [aldeed/meteor-simple-schema#133]
Hi,

I'm not sure if this is working as designed. If it is, then perhaps the documentation could make it clearer somehow. It's certainly unintuitive to me.

I have a schema with non-optional fields:

```
Schema.Address = new SimpleSchema({
  ...
  street: {
    type: String
  }
  ...
});
```

Which I use in a few places. My "Order" schema contains a "ShippingInfo" schema, which can only have one address, so I set it like so:

```
Schema.ShippingInfo = new SimpleSchema({
  ...
  address: {
    type: Schema.Address
  }
  ...
});

Schema.Order = new SimpleSchema({
  ...
  shipping: {
    type: Schema.ShippingInfo,
    optional: true
  }
  ...
});
```

That is, shipping need not be set, but if it is, then it needs to have an address.

Unfortunately, it doesn't seem to work. I get validation errors for the address keys (like "street"). So I am working around it like this:

```
Schema.Order = new SimpleSchema({
  ...
  shipping: {
    type: [Schema.ShippingInfo],
    maxCount: 1
  }
  ...
});
```

It's not optimal, imo, but it works.

**Comment by petermikitsh** [comment]
This bug still exists, but the work-around also works.
