### ISSUE TITLE
How to trim before validation?

### ISSUE THREAD

**Issue by wursttheke** [aldeed/meteor-simple-schema#140]
Hey Eric!

Is there an easy and dry way to trim string inputs (remove leading and trailing whitespace) before validation? Currently im using autoValue like this:

``` javascript
Players.attachSchema(new SimpleSchema({
  name: {
    type: String,
    label: "Your Name",
    min: 1,
    autoValue: function() {
      if (this.value) {
        return this.value.trim();
      }
    }
  }
}));
```

It works but it would be cool to have a simple option for this like `trim: true` or something similar. I have the feeling that the autoValue feature is not really meant for this job.

And, of course: Thanks for this awesome package!

**Comment by wursttheke** [comment]
Hey Eric! Again, thanks again for the great trimming feature. 

I encountered another situation though, which I think leads to unexpected behavior.

Given you have a schema/collection2 with a required field `name` on it:

```javascript
Todo.attachSchema(new SimpleSchema({
  name: { type: String },
}));
```

This is what happens when you insert documents with leading/trailing whitespace:

```javascript
Todo.insert({name: "   test   "}) // => insert works (as expected), string is trimmed
Todo.insert({name: ""}) // => insert fails (as expected), because name is required
Todo.insert({name: "   "}) // => insert works (strange!), string is trimmed to a blank string and inserted into db
```

The problem is the last line. With the automatic trimming of string, I would expect it to fail validation, because after the trimming an empty string would be left. Maybe the check for emptiness and the trimming are somehow done in the wrong order?

**Comment by aldeed** [comment]
@wursttheke, it's probably actually that the filter clean comes before the trim clean. Will need to test for sure, but it's probably OK to reverse those to fix this issue. Can you post your previous comment as a new issue?
