### ISSUE TITLE
Simple-Schema: TypeError: Object [object Object] has no method 'attachSchema'

### ISSUE THREAD

**Issue by CaptainChainsaw** [aldeed/meteor-simple-schema#147]
Hi,

I'm running Meteor 0.9.1.1 and I keep getting issues with simple-schema:

```
$ meteor
[[[[[ ~/game ]]]]]

=> Started proxy.
=> Started MongoDB.     
W20140907-08:06:03.233(-7)? (STDERR) 
W20140907-08:06:03.357(-7)? (STDERR) /home/me/.meteor/packages/meteor-tool/.1.0.28.tx8gz++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20140907-08:06:03.358(-7)? (STDERR)                        throw(ex);
W20140907-08:06:03.362(-7)? (STDERR)                              ^
W20140907-08:06:03.363(-7)? (STDERR) TypeError: Object [object Object] has no method 'attachSchema'
W20140907-08:06:03.364(-7)? (STDERR)     at app/lib/schema-Account-Type.js:22:13
W20140907-08:06:03.365(-7)? (STDERR)     at app/lib/schema-Account-Type.js:25:3
W20140907-08:06:03.365(-7)? (STDERR)     at /home/me/game/.meteor/local/build/programs/server/boot.js:161:10
W20140907-08:06:03.365(-7)? (STDERR)     at Array.forEach (native)
W20140907-08:06:03.366(-7)? (STDERR)     at Function._.each._.forEach (/home/me/.meteor/packages/meteor-tool/.1.0.28.tx8gz++os.linux.x86_64+web.browser+web.cordova/meteor-tool-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20140907-08:06:03.366(-7)? (STDERR)     at /home/me/game/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
```

This is the file that contains my schema:

```
AccountType = new Meteor.Collection("AccountType");
Schema = {};
Schema.AccountType = new SimpleSchema({
    accountType: {
        type: String,
        allowedValues: ['test', 'live']
    },
    createdBy: {
        type: String,
        autoValue: function(){ return this.userId }
    }
});

SimpleSchema.debug = true;
AccountType.attachSchema(Schema.AccountType);
```

This schema was previously working on an earlier version of Meteor.

Any ideas what the issue with this could be?

**Comment by aj07mm** [comment]
I got the same using 
aldeed:collection2         2.3.1 
and Meteor 1.

Foo = new Meteor.Collection("foo");

var Schemas = {};

Schemas.Foo = new SimpleSchema({
    empresaRazaoSocial: {
        type: String,
        label: "Title",
        max: 200
    }
});

Foo.attachSchema(Schemas.Foo);

**Comment by laughingturtle** [comment]
What do you mean by 'stubbing' ?

**Comment by mvgalle** [comment]
In your terminal try adding the following package to your application : 

`meteor add aldeed:collection2

Solved the problem for me. :)

**Comment by khaynay** [comment]
Had same issues with meteor app: "ReferenceError: SimpleSchema is not defined"
open terminal in the project folder and type the following command `meteor add aldeed:collection2`
result:
**Changes to your project's package version selections:

aldeed:collection2    added, version 2.7.1
aldeed:simple-schema  added, version 1.5.3
mdg:validation-error  added, version 0.2.0**
