### ISSUE TITLE
Validation of conditional sub-schemas

### ISSUE THREAD

**Issue by jamgold** [aldeed/meteor-simple-schema#152]
I am trying to figure out how to implement a schema that would allow validating different sub-schemas based on field in the parent.

Say I have the schemas for Mammal, Lizard and Bird and now want to create the schema for a collection Pets, which contains a generic field nameOfPet and a field typeOfPet = [Mammal, Lizard, Bird] so that I can include different sub-schemas. Would I custom, or blackbox these? Or do I need to write my own validation?

Is this possible at all?

**Comment by 7immy** [comment]
+1
