### ISSUE TITLE
coditional - optional 

### ISSUE THREAD

**Issue by pociej** [aldeed/meteor-simple-schema#165]
Is there any good way to have one filed optional if and only if other is set ? 

the best way would be 

``` javascript
field : {
type : String, 
optional : true, 
custom : function(doc){
if(!doc.other_filed){
return required, 
}
}
```

but how to get access to foc inside custom ?

**Comment by Errbel** [comment]
Hi there !

Playing with custom field like that:

    ...
    time: {
        type: String,
        autoform: {
            type: "select-radio-inline",
            options: function () {
                return [
                        {label: "TIME1", value: 'TIME1'},
                        {label: "TIME2", value: 'TIME2'}
                    ];
            }
        }
    },
    volume: {    
        type: Number,
        label: 'Volume',
        autoform: {
            afFieldInput: {
            type: "text"
            }
        },
        optional: true,
        custom: function(){
            if (this.siblingField("time").value !== "TIME1"){
                return "required"          // Built-in error type string !
            }
        },
    },
    ....

volume is not required for time = TIME1 and required for time = TIME2 ==> OK, but...
When time = TIME2 AND volume = 3 (a number), I got a validation error (type "required")!

Here SimpleSchema debug log : 
    SimpleSchema invalid keys for "addForm" context: [Object]0: Objectname: "mySchema.volume" 
     type: "required" 
      value: 3
      __proto__: Object
    length: 1
    __proto__: Array[0]

We can see in logs that value = 3 for volume...

What am I doing wrong ?

Thx !!

**Comment by RobertLowe** [comment]
@aldeed There appears to be an issue with nested/sub-schemas not being validated when `custom` returns and the field is `optional` is set true

    PostPhoto = new SimpleSchema
      title:
        type: String

      description:
        type: String

    Posts = new SimpleSchema

      type: 
        type: String
        allowedValues: [
          'Photo', 
          'Video'
        ]

      photo: 
        type: PostPhoto
        optional: true
        custom: ()->
          # only required when the type is Photo and the sub-schema fails
          if @field('type').value == "Photo" && !Match.test(@value || {}, PostPhoto)
            "required"


It appears that when `photo` is "required" by the `custom` attribute but the key is optional the sub-schema doesn't run it's validations.

For example in the case above; I'm validating the `Post` object via autoform, however when the `custom` attribute returns "required" the nested/sub-schema keys are not triggered `title`/`description` are not triggering 'required` error validations.

Any thoughts? Am I just using this incorrectly, would there be a better way to validate sub-schemas that are conditionally required?
