### ISSUE TITLE
Allow updating an entire document

### ISSUE THREAD

**Issue by scuendet** [aldeed/meteor-simple-schema#175]
This is linked to issue #82. The MongoDB documentation indicates that it is possible to replace all fields of a document at once: http://docs.mongodb.org/manual/reference/method/db.collection.update/#example-update-replace-fields

However, when I do a `MyColl.update({id: docId}, {field1: val1, field2, val2})`, the update fails with the error:
 Error: When the modifier option is true, all validation object keys must be operators. Did you forget `$set`?

Is that intended or am I doing something wrong?

**Comment by yourcelf** [comment]
I've used this approach to solve this need:

    // helpers.js
    mongoReplacementModifier = function(keep, change) {
      var $unset = {};
      for (var key in change) {
        if (keep[key] === undefined) {
          $unset[key] = "";
        }
      }
      var copy = _.clone(keep);
      delete copy._id;
      return {$set: copy, $unset: $unset}
    };

    // update code
    var newDoc = {field1: val1, field2: val2};
    var stale = MyColl.find(docId);
    var modifier = mongoReplacementModifier(newDoc, stale);
    MyColl.update(docId, modifier);

Not *too* severe, and only makes one extra read on the db.

**Comment by rbabayoff** [comment]
You can also use this npm package to calculate a mongodb modifier diff between 2 docs, for more complex docs:

https://www.npmjs.com/package/rus-diff

**Comment by realyze** [comment]
I just got bitten by this. In my case, we're using `upsert` with object literals quite heavily which is a bummer.

**Comment by derwaldgeist** [comment]
+1 for adding this.

According to Meteor docs, an upsert modifier may contain a whole document: http://docs.meteor.com/#/full/modifiers

It would be really nice if SimpleSchema would support this, since it is quite errorprone to create a $set for all of the document's values.

**Comment by AbdelBa** [comment]
What you can do is validating your object 'by hand' prior to call update with `{update: false}`

```javascript
// https://github.com/aldeed/meteor-simple-schema#cleaning-data
MySchema.clean(myDoc);

// https://github.com/aldeed/meteor-simple-schema#validating-data
check(myDoc);

// ok, myDoc is ready to be stored
myCollection.update(someId, myDoc, {validate: false});
```

**Comment by OminStyle** [comment]
+1

**Comment by c316** [comment]
+1

**Comment by amjedonline** [comment]
Hi, is there any progress on this issue ? Would be really helpful to be able to use the restivus out of the box update APIs.

**Comment by savvopoulos** [comment]
+1

**Comment by danimbrogno** [comment]
+1

**Comment by thebarty** [comment]
Hi guys, 

this is related to https://github.com/aldeed/meteor-collection2/issues/318.

Read here for more discussions on this https://forums.meteor.com/t/collection2-validating-fields-against-each-other-in-embedded-arrays/20107

**Comment by Taakn** [comment]
I am trying the following:

```
if (Meteor.isServer) {
    return Organizations.update(organizationId, myDoc, {validate: false});
}
```

of this:
```
if (Meteor.isServer) {
    return Organizations.update({_id: organizationId}, myDoc, {validate: false});
}
```


and I am getting the following error:

```
Exception while invoking method 'Organizations.update' Error: Update parameter cannot have both modifier and non-modifier fields.
at isModificationMod (packages/mongo/mongo_driver.js:588:11)
at MongoConnection._update (packages/mongo/mongo_driver.js:512:20)
at MongoConnection.<anonymous> (packages/meteor.js:212:23)
at MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:49)
at [object Object].update (packages/mongo/collection.js:568:29)
at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core.js:220:19)
at [object Object].OrganizationsUpdate (lib/methods.js:142:32)
at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
at packages/ddp-server/livedata_server.js:711:19
at [object Object]._.extend.withValue (packages/meteor.js:1100:17)

```
Do you know what could be causing this issue?

Thanks!

**Comment by AnthonyReid99** [comment]
Same here, I've tried passing {validate: false, removeEmptyStrings: false} as my third argument to update and I'm also getting the 'Update parameter cannot have both modifier and non-modifier fields'. Is there ANY way I can just get this insert to work? I don't need any validation or anything like that.

**Comment by kcrawford** [comment]
+1

**Comment by jbergenthal2** [comment]
I had the same problem, see [aldeed/meteor-collection2/issues/355](/aldeed/meteor-collection2/issues/355)
One workaround is to use not `validate:false`, but `bypassCollection2:true`

**Comment by jbergenthal2** [comment]
I had the same problem, see [aldeed/meteor-collection2/issues/355](/aldeed/meteor-collection2/issues/355)
One workaround is to use not `validate:false`, but `bypassCollection2:true`

**Comment by jbergenthal2** [comment]
Instead of `validate: false`, use `bypassCollection2:true`

**Comment by Sntax** [comment]
+1

**Comment by markengelstad** [comment]
+1

**Comment by n00bvn** [comment]
Hi guys,

I'm facing this issue. So what's the solution to fix this?

**Comment by aldeed** [comment]
Closing since this is a collection2 issue. https://github.com/aldeed/meteor-collection2/issues/368
