### ISSUE TITLE
Allow defaultValue field to accept functions

### ISSUE THREAD

**Issue by kev1597770** [aldeed/meteor-simple-schema#194]
I want to set the following schema field to have all locations (i.e. an array of all location ids) as a default value.  Though I might be able to accomplish this with an autoValue field it seems like a more elegant solution would be to allow the defaultValue field to accept a function.

```
locations: {
    type: [String],
    label: "Locations",
    optional: true,
    autoform: {
      type: "select-checkbox",
      options: function(){
        var a = Locations.find( {}, { fields:{ name:1 } } ).fetch();
        var r = [];
        a.forEach(function(e) {
          r.push( { label: e.name, value: e._id } );
        });
        return r;
}}},
```

**Comment by neang-tola** [comment]
Hi @Aldded,
autoValue: function () {
  if (this.operator === null && !this.isSet) {
    return defaultValue;
  }
}

it still not work when we using in update operation. It work only for insert operation.
Please help me for update the autoValue function that support for insert operation.
