### ISSUE TITLE
Object ... has no method 'attachSchema'

### ISSUE THREAD

**Issue by cpalanzo** [aldeed/meteor-simple-schema#203]
Started by trying to add autoform and collection2 to existing Meteor app - could not get Simple-Schema to work - missing attachSchema method. Looked at everything online. Removed, reinstalled all items. Did Meteor Reset. Removed everything and added JUST Simple-Schema. No luck.

Researched everything on the web.

Bit the bullet - created NEW meteor project and added all packages... Copied existing code - NO luck!
Still can't get the attachSchema method! 

I'm a Meteor noob - but a pretty old and experienced developer... did NOT want to bother you..
But your packages look great, collections, autoform everything - but can't seem to get over this basic hurdle... Just using Simple Schema... !!

Advice? Next steps?

![screen shot 2014-12-08 at 9 48 35 pm](https://cloud.githubusercontent.com/assets/9503630/5351429/019e0694-7f24-11e4-8131-3aac31872907.png)

**Comment by aj07mm** [comment]
I had the same prob as @cpalanzo 

Im using

```
accounts-base              1.1.3  A user account system
accounts-meteor-developer  1.0.3  Login service for Meteor developer accounts
accounts-password          1.0.5  Password support for accounts
aldeed:collection2         2.3.1  Automatic validation of insert and update operations on the client and server.
houston:admin              2.0.0  A zero-config Meteor Admin
iron:router                1.0.6  Routing specifically designed for Meteor
meteor-platform            1.2.1  Include a standard set of Meteor packages in your app
meteorhacks:npm            1.2.2  Use npm modules with your Meteor App
npm-container              1.0.0+ Contains all your npm dependencies
```

My meteor version is Meteor 1.0.2.1

I tried the snippet below but no deal
```
Foo = new Meteor.Collection("foo");

var Schemas = {};

Schemas.Foo = new SimpleSchema({
    empresaRazaoSocial: {
        type: String,
        label: "Title",
        max: 200
    }
});

Foo.attachSchema(Schemas.Foo);

```

errors:

```
TypeError: Object [object Object] has no method 'attachSchema'
    at app/lib/common.js:11:5
    at app/lib/common.js:13:3
    at /Users/aj07mm/Desktop/leilao/.meteor/local/build/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/aj07mm/.meteor/packages/meteor-tool/.1.0.35.1l26b8e++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /Users/aj07mm/Desktop/leilao/.meteor/local/build/programs/server/boot.js:82:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

tried to downgrade collection2 to previous versions but no go

**Comment by Weijtmans** [comment]
I found that the houston:admin package causes the problems.
