### ISSUE TITLE
Set this.docId in custom and autoValue on client

### ISSUE THREAD

**Issue by dohomi** [aldeed/meteor-simple-schema#208]
Hello Eric,

I just had the use case inside an AutoForm where I wanted to get the _id of the document inside of the ```autoValue```function. But even in ```isUpdate```context the field _id is not accessible. The ```this``` context has a ```docId```but it is undefined.

Shouldn't be the ```docId```set?
Cheers

**Comment by FatBoyXPC** [comment]
@aldeed I'd also lke to have docId available to the client. I'm using a custom validator to verify that field A and field B are a unique pair. I find it easiest if I can do this via the docId, so right now I'm limisted to putting this on a server side check.
