### ISSUE TITLE
Type [String] refusing allowed values

### ISSUE THREAD

**Issue by caioreis** [aldeed/meteor-simple-schema#215]
Hi,

I'm working with this code:

``` js
  accessories: {
    type: [String],
   allowedValues: ['Freezer', 'Ar Condicionado', 'GPS', 'Microondas', 'CD Player', 'Animais Permitidos', 'Geladeira', 'TV', 'Bóia para Puxar', 'Churrasqueira', 'Chuveiro Interno', 'Cooler', 'Fly', 'Fish Finder', 'Som USB / AUX', 'Fogão', 'Rádio VHF', 'Wakeboard / Ski', 'VHF', 'Escada', 'Ducha de Água Doce', 'Tapete', 'DVD', 'Suíte', 'Água Quente', 'Plataforma Móvel', 'Gerador', 'Equipamento de Pesca', 'Iluminação Subaquática', 'Material de Mergulho Livre', 'Bote de Apoio s/ Motor Motor', 'Bote de Apoio c/ Motor Motor', 'Carregador para Telefone 12v'],
    label: 'Acessórios'
  } 
```

And for some reason AnunciosSchema._schema.accessories don't returns allowedValues key. If I remove array from type, so it will be just a String, I can access it. What's happening?

Tks

**Comment by imajus** [comment]
I assume you should include that part into official README. It's unclear than using `type: [String]` along with `allowedValues: [ 'a', 'b', 'c' ]` will represent an enumeration. I had to search thru issues in order to find this example.
