### ISSUE TITLE
Multiple RegEx Per Key

### ISSUE THREAD

**Issue by aldeed** [aldeed/meteor-simple-schema#22]
It was mentioned in #5 that `regEx` should support multiple regular expressions for a single schema key. This seems like a good idea. Might be best to name them rather than using an array, and then those names can be used for custom messages:

``` js
MySchema = new SimpleSchema({
  password: {
    type: String,
    regEx: {
      numbers: twoNumbersRegEx
    }
  }
});

MySchema.messages({
    'regEx.numbers': "[label] must have two numbers"
});
```

**Comment by drewlsvern** [comment]
I have tried implementing exactly as shown here, but it doesn't seem to work. It just display the default regEx error message "[label] failed regular expression validation". Are there any known bugs with feature?
