### ISSUE TITLE
Feature request: serverOnly / clientOnly field option

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-simple-schema#223]
I think it would be nice to have a **serverOnly / clientOnly** option for fields where (for example) **validation** or **autovalue generation** should only run on one side (server or client).

I know we could use `Meteor.isClient` and `Meteor.isServer` and call `attachSchema()` several times but having the above option would allow more **compact and beautiful code**.

**Comment by dandv** [comment]
Second this. Autovalues are another use case when proprietary code is involved that should not be exposed on the client. That autovalue code would only run on the server, and the client would only receive the result.

**Comment by CaptainN** [comment]
I just hit an issue where this would be useful. I have some autovalues for timestamps, owner and the like, that I was trying to use ongoworks:security to deny updates for. But the autovalue gets set on the client, and that was triggering the deny. It'd be great if there was a way to define the autovalue only for the server.

**Comment by aldeed** [comment]
Closing. This wouldn't make sense in core anymore since SimpleSchema is an NPM package, but someone who wants this bad enough would likely be able to write a separate package to add support for these schema options.
