### ISSUE TITLE
Password must be a string error

### ISSUE THREAD

**Issue by abachuk** [aldeed/meteor-simple-schema#225]
I followed documentation for validating one key agains another https://github.com/aldeed/meteor-simple-schema#validate-one-key-against-another. This gives me an error:  "Password must be a string", no matter what the value. So, it fails validation all the time.

Here is error:

```

SimpleSchema.clean: filtered out value that would have affected key "email", which is not allowed by the schema
SimpleSchema.clean: filtered out value that would have affected key "password.digest", which is not allowed by the schema
SimpleSchema.clean: filtered out value that would have affected key "password.algorithm", which is not allowed by the schema
Exception while invoking method 'createUser' Error: Enter a password must be a string at getErrorObject (packages/aldeed:collection2/collection2.js:363:1)
at [object Object].doValidate (packages/aldeed:collection2/collection2.js:346:1)
at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/collection2.js:147:1)
at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:1042:1)
at createUser (packages/accounts-password/password_server.js:693:1)
at packages/accounts-password/password_server.js:713:1
at tryLoginMethod (packages/accounts-base/accounts_server.js:186:1)
at Object.Accounts._loginMethod (packages/accounts-base/accounts_server.js:302:1)
at [object Object].Meteor.methods.createUser (packages/accounts-password/password_server.js:699:1)
at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
Sanitized and reported to the client as: Enter a password must be a string [400]

```

I use this schema for creating a new user.

**Comment by aldeed** [comment]
What's your full user schema? I think you probably attached a schema that doesn't match the way the Meteor accounts packages actually save user data. You could remove the schema, create a user, and then look at the mongo document that is created to make sure it matches your schema.

**Comment by abachuk** [comment]
This is how my schema looks:

{ createdAt: Mon Jan 12 2015 22:26:14 GMT-0500 (EST),
_id: 'cGfG3gyZcb82DcuAJ',
 services: { password: { bcrypt: '$2a$10$StHtz1nEqOE5886Ngf0IJOqvZiQPK6b5UuSjBv0vLatOC997DQhJ.' } },
username: 'user@gmail.com',
emails: [ { address: 'user@gmail.com', verified: false } ] }

**Comment by aldeed** [comment]
Is this still an issue? If so, will need a more complete reproduction.

**Comment by JackC27** [comment]
Having the same problem. Why are you of the opinion the schema would matter? If I use Account.createUser("jack", "jack@jack.com", "jack", "profile", someCallback(){//code here//} ) same with any variation you throw at it (["jack", "jack@jack.com", "jack", "profile"]). It's not throwing an error because of the schema. The error is because something other than a string is being passed to the function on line 116. Asking out of curiosity not trying to be a jerk. 

![screen shot 2015-10-08 at 2 09 43 am](https://cloud.githubusercontent.com/assets/3687036/10358977/dcafe118-6d61-11e5-8579-b41fa6b8eb51.png)

![screen shot 2015-10-08 at 2 10 28 am](https://cloud.githubusercontent.com/assets/3687036/10358979/e4461b72-6d61-11e5-82bf-5dd2b2e469b0.png)

I realize it's months down the road but it appears this is still an open issue.

**Comment by JackC27** [comment]
It does appear that serverside creation of a user will work.
![screen shot 2015-10-08 at 2 24 18 am](https://cloud.githubusercontent.com/assets/3687036/10359170/f9ffed6a-6d63-11e5-9082-b2b792d7d9d3.png)

![screen shot 2015-10-08 at 2 24 37 am](https://cloud.githubusercontent.com/assets/3687036/10359177/02e21aac-6d64-11e5-94e7-df31f5f44e76.png)

**Comment by JackC27** [comment]
Duplicating the server side way to do account creation results in...
![screen shot 2015-10-08 at 2 30 48 am](https://cloud.githubusercontent.com/assets/3687036/10359238/b77e2e1a-6d64-11e5-8619-9a9c406672db.png)

So if there is more than I can do to duplicate this issue please let me know.

**Comment by aldeed** [comment]
To clarify, the problem would be that password is not a string because it's not set. And it's not set because it is cleaned to match your schema, but your schema doesn't match what the accounts-password package is actually trying to save. So just correct your user schema and it should be fine.
