### ISSUE TITLE
How to add new key-value pairs on the fly to the schema?

### ISSUE THREAD

**Issue by KrishnaPG** [aldeed/meteor-simple-schema#230]
How to dynamically add new key-value pairs for the schema object on the fly?

Code examples are always creating a static (non-varying) SimpleSchema object. Is it possible to alter the object later once it is created (perhaps assign a new object with more key-val pairs)?

Also, is the SimpleSchema object reactive? i.e. if new key-value pair is added to the schema, whatever depends on it (such as autoform) gets notified automatically?

**Comment by aldeed** [comment]
I wouldn't recommend it, but there are ways you could do it. You could have multiple schemas defined and then dynamically build a new schema by merging some of the component schemas: `new SimpleSchema([schema1, schema2])`

**Comment by KrishnaPG** [comment]
For now - I got away with dynamic templates for creating new autoforms (with new schema) automatically whenever the schema changes. But it would be great if autoform supports reactive-schema (re)loading in-built.

**Comment by jdmswong** [comment]
you can create the schema dynamically on the client by putting it in a `Tracker.autorun()` block
