### ISSUE TITLE
Validation is not run on $addToSet and $pull

### ISSUE THREAD

**Issue by bulldozerlovesyou** [aldeed/meteor-simple-schema#231]
When I run updates with `$addToSet` and `$pull`, validation is not run.
Consider this local collection of two-colored national flags:

    Flags = new Mongo.Collection(null);
    Flags.attachSchema(new SimpleSchema({
        name: {
            type: String
        },
        colors: {
            type: [String],
            minCount: 2,
            maxCount: 2
        }
    }));

    Flags.insert({name: 'Sweden', colors: ['blue', 'yellow']});

When you try to run

    Flags.update({name: 'Sweden'}, {$set: {colors: ['yellow']}})

you get a validation error. But when you run

    Flags.update({name: 'Sweden'}, {$pull: {colors: 'yellow'}})

or

    Flags.update({name: 'Sweden'}, {$addToSet: {colors: 'red'}})

you don't. Is this a bug? Is there a work-around?

**Comment by aldeed** [comment]
I guess you could call it a bug, but it's really just a not-yet-implemented feature of collection2. SimpleSchema handles all validation that does not require database awareness, but the validation you're asking about requires database awareness, so it needs to be implemented as extra validation provided by collection2 pkg. See https://github.com/aldeed/meteor-collection2/issues/12.
