### ISSUE TITLE
mergeSchemas(), simple-schema.js, Line: 745 throws Errors

### ISSUE THREAD

**Issue by obiwarn** [aldeed/meteor-simple-schema#233]
I use Websorm IDE. When I enable JS exception breakpoints, I get a load of exceptions from simple schema on creating a new schema.

when calling new SimpleSchema() then:
coming from simple-schema.js Line 39

in Line 745:
    throw new Match.Error("Expected " + pattern.name);

**Comment by aldeed** [comment]
Will need reproduction code.
