### ISSUE TITLE
[Question] What is the best way to set field optional on autoform validation and required on insert (method & collection2)

### ISSUE THREAD

**Issue by delgermurun** [aldeed/meteor-simple-schema#238]
I have `userId` field to save inserted user id. I set `autoform: {omit: true}`, so it doesn't render on autoform but still required and form doesn't submit.

What I need is optional on form and required on method (collection insert).

How can I do that?

Thank you.

**Comment by aldeed** [comment]
Set the `schema` attribute for the form to a SimpleSchema instance that matches the validation you want for the form.
