### ISSUE TITLE
SimpleSchema.RegEx.Url and localhost URL

### ISSUE THREAD

**Issue by picsoung** [aldeed/meteor-simple-schema#239]
Hello,

Once again, thanks for all the hard work you put in your packages.

I thought I already posted this issue but I can't find it again, so maybe not.

Something I realize when I coming SimpleSchema and Autoform, on a field with like this

```js
image_url:{
        type:String,
        label: "image URL",
        regEx: SimpleSchema.RegEx.Url
    },
```

The autoform validator thinks that an URL like `http://localhost:3000/public/img/file.png` is not a valid URL.

Looking at the regex using a visualizing tool like http://regexper.com/ I thought the port part was included.
I am having a hard time to find out which part of the regex is failing.

Also I thought that using a library like [URI.js](http://medialize.github.io/URI.js/) you can validate a URL, but not :(

Hope it helps,
Nicolas

**Comment by rdewolff** [comment]
The part of the URL failing is the domain name without ".com" or "." something.

So basically ```http://localhost:3000/my/file.png``` will fail, but ```http://localhost.com:3000/my/file.png``` will succeed.

**Comment by rbell01824** [comment]
I'm not sure this should be closed.  While the url http://localhost.com:3000/my/file.png passes the edit it does not in fact load in the browser (at least not on my system).

**Comment by aldeed** [comment]
For now I'm not adjusting the built in `Url` expression since everyone wants something different and you can simply use your own.
