### ISSUE TITLE
Possible to use Collection content as allowedValues (not reactive)

### ISSUE THREAD

**Issue by Visudare** [aldeed/meteor-simple-schema#241]
Is there any way to solve the problem that it seems to be impossible to add a Collection content as array as allowedValues ? 

For example:
```javascript
My_Schema = new SimpleSchema({
      group : {
           type : String,
           allowedValues : _.pluck(Groups.find().fetch(), 'name') 
      }
});
```

The return of the cursor is always empty.

**Comment by aldeed** [comment]
If on the client, you would need to wait until your groups subscription is ready.

**Comment by Visudare** [comment]
Okay as I expected. I thought there is maybe a build-in option to do this without waiting for the subscribtion. :) Thanks.
