### ISSUE TITLE
Add `getAllowedValues` API

### ISSUE THREAD

**Issue by mquandalle** [aldeed/meteor-simple-schema#242]
Unless I missed it somewhere, there is no public API to get the list of allowed values for a given field. The use case would be to display a `select` form element with all the possible values simpleSchema will accept.

**Comment by sunstorymvp** [comment]
Hi, there is a way to do it like this:

@Schemas = {}

@Schemas.Device = new SimpleSchema
  platform:
    type: String
    allowedValues: [
      'iOS'
      'Android'
      'Web'
    ]

template(name='device')
   select(multiple name='platform' size='4')
     each platform
       option(value=this)=this

Template.device.helpers
  platform: ->
    Schemas.Project._schema.platform.allowedValues

BUT, I dont know how to get allowedValues if field type is array (e.g. [String]).
in this case its undefined.

**Comment by radekmie** [comment]
Public API solution (automatically takes care about non-static `allowedValues`):
`Schemas.Device.getDefinition('platform').allowedValues`

**Comment by aldeed** [comment]
Closing this. Not planning to provide any specific way to do this since there are ways already.
