### ISSUE TITLE
Match key to regex

### ISSUE THREAD

**Issue by basaundi** [aldeed/meteor-simple-schema#244]
I would benefit from having a schema for variable key names.

Proposed syntax:

``` javascript
BookSchema = new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 200
  },
  '^property_' : {
    keyIsRegex: true,
    blackbox: true
  }
});
```

**Comment by aldeed** [comment]
Interesting. This could take the place of the __any I was planning to implement (#213). I think in order to keep everything working, only the last piece of the dot-separated key could be regex. Maybe instead of `keyIsRegex`, we just borrow the javascript literal notation:

```js
BookSchema = new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 200
  },
  '/^property_/i' : {
    type: String
  },
  'foo.$.bar./^property_/i' : {
    type: Number
  }
});
```

**Comment by aldeed** [comment]
Just noticed the PR attached. Do you think you could update the PR to use the syntax I propose? You should also add a `SimpleSchema.keyIsRegEx(key)` utility function that returns true or false to help autoform and other packages filter out such keys.

**Comment by basaundi** [comment]
Why do you think only the leaf can be a RegExp?
A possible approach would be converting the whole thing to a regular expression `'foo.$.bar./^property_/i'` to `/^foo\.[0-9]+\.property_/i`

but then it wouldn't be possible to have different regexp options for each part:
```javascript
'/_file$/i.$./^prop_/
```

**Comment by aldeed** [comment]
There are many areas of code and many other packages that rely on parsing the dot-separated segments. I did not mean to say only the last piece, but simply that only the pieces rather than the whole thing. If your regEx key is an object or array, then yes there would be additional segments after the regEx.

**Comment by basaundi** [comment]
So, what needs to be done in order to see this feature integrated? :smiley: 
Currently we are running a forked version of the package.

**Comment by aldeed** [comment]
I'll be releasing the next AutoForm in a few days, then turning attention to a few collection2 issues, then simple-schema issues. Happy to look at PRs in the meantime.

**Comment by basaundi** [comment]
Okay, thanks.

**Comment by davidecantini** [comment]
Hi @aldeed,
I'd like to know if you have any update on when this enhancement will be available.
Thanks in advance for your attention.

**Comment by aldeed** [comment]
I'm back to working on SS. There are quite a few things to be done, but this is near the top of the list. No timeline.

**Comment by ShockiTV** [comment]
We would welcome the __any or something what can represent key of object.
Currently using String(_id) as property names of 1 Object and there is no way how to auto validate it's internals as long as I know - keeping as blackbox for now.
For arrays there is $, but for keys nothing yet ?

**Comment by davidecantini** [comment]
Hi @aldeed, thanks for your last update. 
Do you have any ETA on this feature at this time? 
Thanks

**Comment by rudza** [comment]
Hey! 

Any update on this feature implementation? :)

**Comment by andrewpeterprifer** [comment]
Yes, it would be nice to see this issue revived. :) Any news?

**Comment by firrae** [comment]
Has there been any progress on this? This would be the exact solution to an issue we're having currently.

**Comment by vblagomir** [comment]
I would ask about this as well.. There is $ for arrays, but nothing for nested objects' keys with various names (what if a key is an _id). Maybe can be available in 2.0?

**Comment by aldeed** [comment]
This is one of the few things I wasn't able to get into the rewritten Node package. It turned out to be extremely complex to adapt the inner workings to support this. I will probably tackle it again at some point, and I'd look at any PR.

**Comment by aldeed** [comment]
Moved to https://github.com/aldeed/simple-schema-js/issues/250

The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
