### ISSUE TITLE
Autovalue Issue: properties and methods are not available

### ISSUE THREAD

**Issue by jjmasse** [aldeed/meteor-simple-schema#246]
When applying updates to collections from the server the autoValue attributes are unavailable and it causes the autoValue attributes to re-rerun.

For example:
```javascript
 Collection.update(ID, {
     $set: {
          a : b
     }
});
```
In the schema references to ```this.value``` is always undefined - and in cases I wish to unset() will fall through.

This just started recently with something I have been working on.  It was working as expected a few weeks ago.

**Comment by aldeed** [comment]
Will need a reproduction to be able to determine what's wrong.

**Comment by jjmasse** [comment]
Hey - sorry for taking awhile to get back to you, thank you for your time.
So while working up an example everything seems to be working just fine.  I tested your most current release of Collection2 as well as 2.3.1 which was the version I have been using.

I will dig further into what I am doing.

Thanks again!
