### ISSUE TITLE
Validate if its present on database

### ISSUE THREAD

**Issue by aj07mm** [aldeed/meteor-simple-schema#248]
Currently its it possbile to validate the presence of some document property at database.
ie: check it some email is already in database, for not having them duplicated

**Comment by aldeed** [comment]
If attached to a collection, you can use the `unique` prop [that collection2 package provides](https://github.com/aldeed/meteor-collection2#index-and-unique).

Otherwise you have to do the lookup yourself in a `custom` validation function.
