### ISSUE TITLE
window.S is undefined

### ISSUE THREAD

**Issue by fredevery** [aldeed/meteor-simple-schema#249]
I keep getting:

simple-schema.js:261 Uncaught TypeError: undefined is not a function

and on line 261 is:

if (S(fieldName2).startsWith(keyPrefix)) {

and I see on lines 10-12:

if (Meteor.isClient) {
  S = window.S;
}

but window.S is undefined. I am assuming it's supposed to be using underscore string but I don't see it in the package dependencies.

[EDIT]

I see now that there is a string.js file in the project. Not sure why window.S is undefined for me then.

[EDIT]

Aaah...figure it out. I've got raix:famono added as well, and it's brought the define method in with the requirejs_client lib. So the string module isn't exporting onto the window namespace

**Comment by pmp0x** [comment]
How did you solve it? 

exporting the namespace during Meteor.startup doesn't seem to work for me
