### ISSUE TITLE
Running `check` for one field

### ISSUE THREAD

**Issue by jonjamz** [aldeed/meteor-simple-schema#251]
I have some Meteor methods that update one field in a document, and for now I'm doing something like this:

```javascript
if (email) {
  schemaContext.validateOne({email: email}, 'email') || throw new Meteor.Error(500, 'Invalid email');
  // Update email
}
```

I wanted to just use `check` lib for validation, but it doesn't work because it requires all fields in the schema to exist (no `validateOne` variant of that).

**Comment by aldeed** [comment]
Does this work?

```js
check({email: email}, mySchema.pick('email'));
```

**Comment by jonjamz** [comment]
That works, thanks--but I don't get a very useful error message back when it fails. 

It would be ideal if using `check` on a single field returned the error message for that field.

**Comment by aldeed** [comment]
In SimpleSchema 2.0, this can be done with

```js
mySchema.validate({ email: email }, { keys: ['email'] });
```

**Comment by jonjamz** [comment]
@aldeed v2.0 looks epic and I'm pumped that it can be used with just node. Thanks!

**Comment by smohantyCME** [comment]
> In SimpleSchema 2.0, this can be done with
> 
> ```js
> mySchema.validate({ email: email }, { keys: ['email'] });
> ```

What about `clean`ing just 1 field? Can that be done too?
