### ISSUE TITLE
Meteor.userId(): Check if inside a method

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-simple-schema#253]
Take the following code:
```javascript
var schemaUserId = new SimpleSchema({
    
    userId: {
        
        type: String,

        autoValue: function() {
            console.log(['***userId***', this]);
            // Error: Meteor.userId can only be invoked in method calls.
            // Use this.userId in publish functions.
            if (Meteor.userId()) return Meteor.userId();
        },
    },
});

var someCollection.attachSchema(schemaUserId);
```

Suppose I am allowing remote (3rd party external services) to manipulate my data, how can I check if the attempt was started from a meteor method or not? When 3rd party services attempt to change data, calling ```Meteor.userId()``` will throw ```Error: Meteor.userId can only be invoked in method calls...```. I need to know the origin caller **(client / server / 3rd party external service)** ??

**Comment by aldeed** [comment]
When a schema is attached to a collection, `this.userId` should always be set within the autoValue function so you can use that instead. If it's `null`, then there is no user context.

**Comment by abachuk** [comment]
I have similar issue. According to C2 documentation: autoValue for this.userId always return null for server-initiated actions. When I need to allow 3rd party services to update a collection on the server side - I get error Error: User is required [400]

**Comment by boustanihani** [comment]
I am having situations, where ```this.userId``` returns ```null``` and ```Meteor.userId()``` is returning the real ID, mostly **inside method calls**...

**Comment by aldeed** [comment]
OK, that is the real issue, then. I don't think there would ever be a user context outside of a method call, but we can fix the value of `this.userId` when validating within a method. However, that fix will be in collection2 package code, so can you close this and open a new issue in that repo?

**Comment by boustanihani** [comment]
Done :)
