### ISSUE TITLE
Question: "required" when parent has "optional: true"

### ISSUE THREAD

**Issue by boustanihani** [aldeed/meteor-simple-schema#254]
Should fields, whose parent field has ```optional: true``` throw **required** if unset?

**Comment by aldeed** [comment]
If an object exists, then all the required properties of it must be present, and you won't be allowed to unset a required property. But you can unset the optional parent.

**Comment by boustanihani** [comment]
I was about to go crazy, but I just found out what is really happening :) Take for example this code:

```javascript
Schema = {};

Schema.image = new SimpleSchema({
    type: {
        type: String,
        denyUpdate: true,
    },
    state: {
        type: String,
        optional: true,
        defaultValue: 'uploading', // Causes => [Error: Type is required]
    },
});

Schema.posts = new SimpleSchema({
    image: {
        type: Schema.image,
        optional: true,
    },
    youtube: {
        type: String,
        label: 'URL',
        optional: true,
    },
});

myCollection = new Mongo.Collection('posts');

myCollection.attachSchema(Schema.posts);

myCollection.insert({
    youtube: 'https://www.youtube.com/watch?v=videoid'
}, function(err) {
    if (err) console.log(err);
});

// [Error: Type is required]
// invalidKeys: [ { name: 'image.type', type: 'required', value: null } ]
```

I was wondering why I am getting the error ```Type is required``` even though its parent node has ```optional: true``` and no image was passed!! It is because the nested ```image.state``` has a ```defaultValue```. Commenting the ```defaultValue``` solves the problem, **but don't you think that default values should not get generated when they have no parent node** ?

**Comment by aldeed** [comment]
It's been a subject of debate, but unfortunately there are different cases where each behavior is more desirable. We might just need two separate options eventually. Still deciding.

See https://github.com/aldeed/meteor-simple-schema/issues/193#issuecomment-65960401
