### ISSUE TITLE
this.field() not working as expected

### ISSUE THREAD

**Issue by dohomi** [aldeed/meteor-simple-schema#256]
Hello,

I try to set up the real name based on firstName and lastName with the help of autoValue:

```
  "profile.firstName": {
    type: String,
    index: 1,
    regEx: /^[a-zA-Z-]{2,25}$/
  },
  "profile.lastName": {
    type: String,
    regEx: /^[a-zA-Z-]{2,25}$/,
    index: 1
  },
  /**
   * @TODO - this is undefined undefined
   */
  "profile.name": {
    type: String,
    autoValue: function () {
      var name = this.field("profile.firstName").value + ' ' + this.field("profile.lastName").value;
      return name;
    }
  },
```

But it just not work as expected, I only receive ```undefined undefined```as values. Any idea on this? Thanks a lot!

**Comment by dohomi** [comment]
Acutally I'm not sure if this issue belongs to collection2 because I try to set properties for ```Meteor.users```collection..

**Comment by aldeed** [comment]
Your autoValue would need to be much more complex to handle update modifiers, etc. Usually I use a collection helper to generate the full name as needed.

As for why they are undefined, you'll need to post your insertion code. Are you just using `Accounts.createUser`?

**Comment by dohomi** [comment]
Hi Eric,

yes I use Accounts.createUser and there the ```this.field```is undefined. I'm wrapping now the function making sure that the ```this.field()```function is actually set correctly. Now it works, but do you have any best practice for this matter?

Cheers and Thanks for the quick reply
