### ISSUE TITLE
custom validation help needed

### ISSUE THREAD

**Issue by Errbel** [aldeed/meteor-simple-schema#258]
Hi there !

Playing with custom field like that:

    ...
    time: {
        type: String,
        autoform: {
            type: "select-radio-inline",
            options: function () {
                return [
                        {label: "TIME1", value: 'TIME1'},
                        {label: "TIME2", value: 'TIME2'}
                    ];
            }
        }
    },
    volume: {    
        type: Number,
        label: 'Volume',
        autoform: {
            afFieldInput: {
            type: "text"
            }
        },
        optional: true,
        custom: function(){
            if (this.siblingField("time").value !== "TIME1"){
                return "required"          // Built-in error type string !
            }
        },
    },
    ....

volume is not required for time = TIME1 and required for time = TIME2 ==> OK, but...
When time = TIME2 AND volume = 3 (a number), I got a validation error (type "required")!

Here SimpleSchema debug log : 
    SimpleSchema invalid keys for "addForm" context: [Object]0: Objectname: "mySchema.volume" 
     type: "required" 
      value: 3
      __proto__: Object
    length: 1
    __proto__: Array[0]

We can see in logs that value = 3 for volume...

What am I doing wrong ?

Thx !!

**Comment by aldeed** [comment]
Doesn't look like you're checking whether it's set. Add `&& !this.isSet`. If you're allowing updates, you'll probably need a lot more checking to handle different modifier operators, too.

**Comment by Errbel** [comment]
It's used with autoform ( ;) ) only in insert mode.
Ok for this.isSet, but in this case field is set.
I had AutoForm.resetForm("addForm") in my rendered function, and no more problems...

Thx Aldeed
