### ISSUE TITLE
console.log(ProfileSchemaContext.invalidKeys()); always invalid with "keyNotInSchema"

### ISSUE THREAD

**Issue by fourq** [aldeed/meteor-simple-schema#259]
I just installed simple-schema today, but I cannot get past my deny() update function due to this error always being caught. I'm not using a userId key anywhere. Any ideas why this might be? I noticed there was some talk about others having issues with this error so I'm hoping it's something that's being looked at.

thanks

```
I20150211-13:17:07.630(-6)? [ { name: 'userId',
I20150211-13:17:07.630(-6)?     type: 'keyNotInSchema',
I20150211-13:17:07.630(-6)?     value: 'vkegN3AD8WFZNpPBp' } ]
```

**Comment by aldeed** [comment]
Can you post more of your code? The schema and the client-side update call. If it's complaining about a `userId` property, most likely there is a `userId` property on the object. If you're not adding it, then a package you're using might be.

**Comment by fourq** [comment]
yeah I can, but even if I add "'userId:': {type: String}," to my schema, it still throws that error. I'll post in just a bit.

**Comment by fourq** [comment]
I think posting that last post is what solved this for me. (not sure where the userId is coming from yet) but I had 'userId:': String instead of 'userId': String. I'll figure out where that userId is coming from and thanks for quickly looking into this. I'm going to close this.
