### ISSUE TITLE
How to extend a collection?

### ISSUE THREAD

**Issue by laran** [aldeed/meteor-simple-schema#272]
I posted my question on StackOverflow. Basically, I have a Task and I want to have DailyTask which extends Task. I'm not sure how to do this in SimpleSchema (or generally in mongo).

Here's a link to the SO post: http://stackoverflow.com/questions/28715654/is-there-a-way-to-handle-inheritance-using-simpleschema

Many thanks.

**Comment by aldeed** [comment]
It's already mentioned in your SO post comments, but see the bit about passing an array of schemas to create a new schema here: https://github.com/aldeed/meteor-simple-schema#combining-simpleschemas
