### ISSUE TITLE
How to define a schema for an array of arrays?

### ISSUE THREAD

**Issue by rnarayan** [aldeed/meteor-simple-schema#277]
I have a field that is an array of arrays. I have tried different ways to define the schema for it but none worked.

Here is the structure of the field:
arr = [Array[2], Array[2], Array[2], Array[2]]  //every element is an array of two elements
arr[0] = ["Movies",  [Object] ]
Object has the following structure:
Object = {id: 123, name: 'Shawshank Redemption'}

Thanks for the help.

**Comment by pascoual** [comment]
Same issue.
@aldeed do you have a idea ?

Thanks

**Comment by aldeed** [comment]
`.$` means "array item" so

```js
{
  arrayField: {
    type: Array
  },
  'arrayField.$' {
    type: Array
  },
  'arrayField.$.$' {
    type: String
  }
}
```

That's as close as you can get right now. Mixing multiple types in the same array (string and object) is not yet supported.

**Comment by pascoual** [comment]
Thanks Eric, but none is working:

arrayField: {
    type: Array
  }
**Give**:
Error: Invalid definition for signaturesExpected.$ field.
at packages/aldeed:simple-schema/simple-schema.js:465:1
at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
at [object Object].SimpleSchema (packages/aldeed:simple-schema/simple-schema.js:462:1)


'arrayField.$' {
    type: Array
},
**Give**:
Error: Invalid definition for signaturesExpected.$.$ field.
at packages/aldeed:simple-schema/simple-schema.js:465:1
at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
at [object Object].SimpleSchema (packages/aldeed:simple-schema/simple-schema.js:462:1)

'arrayField.$.$' {
    type: String
  }
**Give**:
Compilation ok but validation not:
[] => ok - strange as it's not an array of array
[[]] => ko
[["",""]] => ko

Thanks.
Pascal

**Comment by aldeed** [comment]
If you want `[]` to be invalid, you'd have to specify `minCount: 1`.

If you want to enforce the two item array, you'll have to specify `minCount: 2, maxCount: 2`.

Not sure why "Invalid definition". I'll have to check it out, but I think we have tests for this scenario.

**Comment by pascoual** [comment]
@aldeed are you ok that both [[]] & [["",""]] should work (array of array) and are not (for now) ?

If I'm not wrong, this mean that, for now, there is no solution to get an array of array on a schema.

Thanks a lot.
Pascal
