### ISSUE TITLE
Dynamic / dependable allowedValues

### ISSUE THREAD

**Issue by smeijer** [aldeed/meteor-simple-schema#278]
Is there any advice on dependable situations? What if the ```allowedValues``` of field 2, depends on the value of field 1.

Should be great if allowedValues accepted an object to map from.

Say:
```js
field1.allowedValues = ["a", "b", "c"];

field2.dependsOn = 'field1';
field2.allowedValues = {
  "a": ["A", "AA", "AAA"],
  "b": ["B", "BB", "BBB"],
  "c": ["C", "CC", "CCC"]
}
```

Then, when ```field1``` has a value of ```a```, ```field2``` ```allowedValues``` are ```A```, ```AA```, and ```AAA```. And when ```field1``` has a value of ```B```, the ```allowedValues``` of ```field2``` are ```B```, ```BB```, and ```BBB```.

I tried this by passing a function to allowedValues, but it seems like allowedValues have no context to get siblingFields?

**Comment by aldeed** [comment]
You can do it with a `custom` function that returns `"notAllowed"` when the value should not be allowed.

**Comment by smeijer** [comment]
I know I can validate like that. But than again, If I would define the allowed values in a object like mentioned in my previous post, SimpleScheme throws an exception that the scheme is being invalid, because allowedValues cannot be an object.

So, allowing allowedValues to be a object, even if SimpleScheme itself won't use it for validation, would help me enormously. Than we could check in a ```custom``` function against the ```allowedObjects```. Like for example:

```js
carParts: {
  label: 'car parts',
  allowedValues: {
      'ford': ['door', 'hood', 'exhaust'],
      'dodge': ['engine', 'roof', 'horn']
  },
  custom: function() {
    var parent = this.siblingField('carPart');
    var allowed = _.contains(this.definition.allowedValues[parent], this.value);
    if(! allowed)
       return 'notAllowed';
  }
}
```

**Comment by aldeed** [comment]
Put your object in some other property of the definition. You can use any property and then tell ss about it: https://github.com/aldeed/meteor-simple-schema#extending-the-schema-options

**Comment by smeijer** [comment]
I've added a "allowedValuesMap" property to fit this purpose, and that did it indeed.

Thanks.
