### ISSUE TITLE
Issue with msavin:mongol

### ISSUE THREAD

**Issue by jlynch80** [aldeed/meteor-simple-schema#279]
I get the error "TypeError: Object [object Object] has no method 'attachSchema'" attaching to Meteor.user while using aldeed:simple-schema and msavin:mongol together.

**Comment by aldeed** [comment]
On client or server? Most likely this issue is in the msavin:mongol package.

**Comment by jlynch80** [comment]
On server, and yeah, issue is msavin:mongol. Didn't have the issue until after the package was added.

**Comment by udnaan** [comment]
another incompatible package is sewdn:collection-behaviours. This only affects the Meteor.users collection.
