### ISSUE TITLE
Checks don't work when using $inc

### ISSUE THREAD

**Issue by elie222** [aldeed/meteor-simple-schema#280]
Meteor.users.update(Meteor.userId(), {
      // works
      $set: {
        balance: Meteor.user().balance - 2
      }
      // doesn't work
      // $inc: {
      //   balance: -2
      // }
    });

The uncommented out code works with the following schema:
  balance: {
    type: Number,
    defaultValue: 0,
    min: 0
  }

You can't have a negative balance.

But if you $inc, as in the commented out code, your balance can drop below 0.

**Comment by aldeed** [comment]
This is already tracked here: https://github.com/aldeed/meteor-collection2/issues/12

It's an issue that has been around for some time, so we should try to get it implemented.
