### ISSUE TITLE
Add GitHub repo, e.g. Atmosphere URL a

### ISSUE THREAD

**Issue by dandv** [aldeed/meteor-simple-schema#283]
https://atmospherejs.com/aldeed/simple-schema

Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by aldeed** [comment]
Done
