### ISSUE TITLE
validateOne runs over all keys in schema

### ISSUE THREAD

**Issue by ChenRoth** [aldeed/meteor-simple-schema#285]
while debugging a validateOne invocation, I've noticed the mechanism runs through all keys in schema where only one key is desired

is this intentional? seems to me like useless computation

**Comment by aldeed** [comment]
As far as I recall, it's intentional. There can be custom validations where validity of one field depends on values from another, so we loop through other fields as much as we have to to make this work as expected.

**Comment by ChenRoth** [comment]
I see.
Well, in my use case it's redundant (I only validate a single field at a time), but what ya gonna do? :)

thanks
