### ISSUE TITLE
this.value in custom() interpreted as string instead of boolean

### ISSUE THREAD

**Issue by Visudare** [aldeed/meteor-simple-schema#288]
There seems to be a problem with the SimpleSchema.custom method. this.value seems to be interpreted as a String instead of Boolean.

This is my code:
```javascript
TestCollection = new Meteor.Collection('test_collection');

TestSchema = new SimpleSchema({
	_id : {
		type : String,
		regEx : SimpleSchema.RegEx.Id,
		optional : true
	},
	test : {
		type : String,
		min : 3,
		custom : function () {
			console.log(typeof(this.value));
			if (this.value !== false && (typeof(this.value) == 'string' && this.value.length < 3)) {
				return 'required';
			}
		}
	}
});

TestCollection.attachSchema(TestSchema);

if (Meteor.isClient) {
	TestCollection.insert({
		test : false
	});
}

```

What I try to do is simple:

The field "test" must be an String - and when its a String it has to be 3 chars or more. But when its "false" (as boolean) its also okay. 

The form should not be able to submit correctly without setting the field "test" but when I insert a document to the collection in my code directly I want to have the possibility to do this.

I dont know why but when logging typeof(this.value) I get "string" instead of boolean back.

**Comment by aldeed** [comment]
Since your schema type is string, the cleaning process converts it to a string. It's not currently possible to have two different types allowed, but it's on the roadmap.

**Comment by Visudare** [comment]
:+1: Then I am waiting for it :)
