### ISSUE TITLE
soop integrates simple-schema

### ISSUE THREAD

**Issue by miguelalarcos** [aldeed/meteor-simple-schema#291]
Hi, I would like to tell you about my new package ```soop```, [Simple Object Oriented Programming](https://github.com/miguelalarcos/soop), where I integrate ```simple-schema``` and ```collection2``` validations.
I tell you if you had an opinion about the integration of your packages.
I'm still not sure if that kind of programming is useful with Meteor, but I want to give it a try. Thanks for your attention.

**Comment by aldeed** [comment]
Interesting @miguelalarcos. It reminds me a little of [peerdb](https://atmospherejs.com/peerlibrary/peerdb). I have not used that, and I have not used OOP for DB operations in Meteor, but I'm interested in the idea of it. Someday I may try to write an app in that way to see how it compares.
