### ISSUE TITLE
Schema Structure 

### ISSUE THREAD

**Issue by rustanacexd** [aldeed/meteor-simple-schema#293]
Is there any way to support this mongo structure? so inside the domain stats is another {}

I am basing my structure as one to one relationship and I saw this on official mongoDB -

http://docs.mongodb.org/manual/tutorial/model-embedded-one-to-one-relationships-between-documents/

```
Schemas.Domain = new SimpleSchema({
    name: {
        type: String,
        label: "Domain Name",
        max: 50
    },
    
    companyDescription: {
        type: String,
        label: "Company Description",
        optional: true
    },

    domainStats: {
            pageRank: {
            type: Number,
            label: "",
            optional: true
        },

        domainAuthority: {
            type: Number,
            label: "Domain Authority",
            optional: true
        },

        pageAuthority: {
            type: Number,
            label: "Page Authority",
            optional: true
        },

        majesticTrust: {
            type: Number,
            label: "Majestic Trust",
            optional: true
        },
    }

   
});
Domains.attachSchema(Schemas.Domain);
```

**Comment by aldeed** [comment]
Schema definitions are flat with dot notation, so you would define `domainStats` as `type: Object` and then define `'domainStats.pageRank'`, etc.

**Comment by rustanacexd** [comment]
Thanks! I saw collections2  samples and I see the usage of dollar sign. ex: "emails.$.verified" what is the difference between the two?

**Comment by aldeed** [comment]
Dollar sign is placeholder for "array index", so in your example `emails` is an array and each array item is an object with a `verified` property. The key "emails.$.verified" would define the schema for that property (applied to every item in the array).

**Comment by rustanacexd** [comment]
I appreciate the response. Thanks a lot! I've actually read the whole simple-schema and it is clearly explained there. Sorry for my trouble. thanks again!
