### ISSUE TITLE
"0 must be an object"--unclear what field is being referenced

### ISSUE THREAD

**Issue by cmnjcs** [aldeed/meteor-simple-schema#295]
Hi, trying to run the following code:

    var newTower = new Tower(towerDoc, self);
    Groves.update({_id: this._id},
                      {$push: {towers : newTower}});

The schema for Groves is:

    GroveSchema = new SimpleSchema({
      _id: {
        type: String
      },
      name: {
        type: String
      },
      belongsTo: {
        type: [String]
      },
      createdAt: {
        type: Date
      },
      towers: {
        type: [TowerSchema]
      },
      variables: {
        type: Object,
        blackbox: true
      }
    });

When the `update()` operation is called, I get the following:

    Error: 0 must be an object
        at getErrorObject (packages/aldeed:collection2/collection2.js:363:1)
        at [object Object].doValidate (packages/aldeed:collection2/collection2.js:346:1)
        at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:147:1)
        at [object Object].Grove.claimTower (packages/grove:grove-api/lib/Grove.js:170:1)
        at repl:1:4

I can't figure out what `0` is referring to--nothing in the schema, or any of the other schemas, has a `0` field. I tried changing `TowerSchema` to `Object`, but I get the same error. If I make a context from `TowerSchema`, and use that to validate `newTower`, I get `true`. Any thoughts?

**Comment by aldeed** [comment]
It's referring to the first item in the `towers` array maybe. If it's an array of `Tower` instances, then your schema should say `type: [Tower]`

**Comment by cmnjcs** [comment]
That would do the trick. Thanks.
