### ISSUE TITLE
Error: key $push must not start with '$'

### ISSUE THREAD

**Issue by bensmeets** [aldeed/meteor-simple-schema#297]
Totally possible that this has something to do with wrong code on my end, but just as a FYI. I'm getting an error after calling a "clean" on a new document "Error: key $push must not start with '$'".

I call the clean, so the autoValues are populated. Calling Collection.clean() changes the raw doc json from:
```
history: [{
  date: Fri Mar 20 2015 10:49:16 GMT+0100 (CET)
}]
```
To
```
'$push': { 
  history: {
    date: Fri Mar 20 2015 10:49:16 GMT+0100 (CET)
  }
}
```

Which seems to throw the error.

**Comment by aldeed** [comment]
Can you post the full original object and `clean` call? It shouldn't do that unless you tell it it's a modifier.

**Comment by bensmeets** [comment]
Sure, this is the code (it's using the collection hooks package), not litteral code but the essential parts are intact.

```
Collection.before.insert(function (userId, doc) {
  ...snip...

  console.dir(doc);
  MySchema.clean(doc);
  console.dir(doc);
  
...snip...
});
```

Log output of first console.dir is (take note of the _id):
```
{
  _id: 'D'
  foreign_id: 'A',
  user_id: 'B',
  history: [{
    user_id: 'C',
    date: Fri Mar 20 2015 23: 52: 22 GMT + 0100(CET)
  }]
}
```

Log output of second console.dir is (no more _id):
```
{
  foreign_id: 'A',
  user_id: 'B',
  '$push': {
    history: {
      user_id: 'C',
      date: Fri Mar 20 2015 23: 52: 22 GMT + 0100(CET)
    }
  }
}
```

Could it have something to do with the collection-hooks package? (just started using it this week).

Cheers.

**Comment by aldeed** [comment]
To avoid it stripping the `_id`, you'll need to add the `_id` key to your schema.

I'm not sure why it's converting to $push. Seems like a bug, but I'll have to investigate.

**Comment by aldeed** [comment]
@bensmeets please post the relevant schema. I tried reproducing this with the following, but I can't.

```js
var testSchema = new SimpleSchema({
    foreign_id: {
      type: String,
      optional: true
    },
    user_id: {
      type: String,
      optional: true
    },
    history: {
      type: [Object]
    },
    'history.$.user_id': {
      type: String
    },
    'history.$.date': {
      type: Date
    }
  });
  
  var testDate = new Date();
  var doc = {
    foreign_id: 'A',
    user_id: 'B',
    history: [{
      user_id: 'C',
      date: testDate
    }]
  };
  
  testSchema.clean(doc);
  
  test.equal(doc, {
    foreign_id: 'A',
    user_id: 'B',
    history: [{
      user_id: 'C',
      date: testDate
    }]
  });
```
