### ISSUE TITLE
simple-schema1.3.1 + autoform 4.2.2 + planifica wizard 0.0.5 (too much recursion on all browsers)

### ISSUE THREAD

**Issue by tcastelli** [aldeed/meteor-simple-schema#303]
Hello I'm experiencing trouble with this  configuration with most of schemas defined for planifica(especially on IE where this is easily repeated). The error that I get is the famous too much recursion: not enough stack space (similar to what happens with firefox with some forms). 
I don't know if it is connected or if it could help to trace any recursive abuse. At the moment i switched back to Simple Schema 1.3.0 and everything works again (waiting until plugins are updated to 5.0)

update: checking again i have found that i can reproduce the error with 1.3.0 so I'm trying to figure out what else is involved

**Comment by aldeed** [comment]
@tcastelli MDG has fixed some recursion issues in the upcoming 1.1 release. Try running your app with `meteor --release 1.1-rc.1`

If not fixed, you'll need to provide a link to repo that shows the issue in a simple app.

**Comment by tcastelli** [comment]
I've tried with the new version and switching many quickfields to array or objectfields, and seems to be working now. Also found out that version 0.3.1 of of the package u2622:persistent-session was creating background troubles which were resolved by reverting to previous version (not sure if EJSON errors were related in producing the too much recursion thing). I think we can close this by now
