### ISSUE TITLE
How to apply Regex validation to an array of strings

### ISSUE THREAD

**Issue by emmanuelbuah** [aldeed/meteor-simple-schema#304]
Below is the code test the bug
```
var EmailSchema = new SimpleSchema({
    emails: {
        type: [String],
        minCount: 1,
	optional: false,
        regEx: SimpleSchema.RegEx.Email
        }
});

isValid = EmailSchema.namedContext("myContext").validate({ emails: ['sdfsdfsf sd'] });
//isValid is false. 

isValid = EmailSchema.namedContext("myContext").validateOne({ emails: ['sdfsdfsf sd'] },"emails");
//isValid is true. I could be wrong but shouldn't "emails" validation be false? 
 
```

I'm probably missing something but is it possible to apply Regex validation to an array of strings as defined above?

**Comment by aldeed** [comment]
Use a full definition instead of the `[String]` shortcut.

```js
emails: {
  type: Array,
  minCount: 1
},
'emails.$': {
  type: String,
  regEx: SimpleSchema.RegEx.Email
}
```

**Comment by emmanuelbuah** [comment]
@aldeed  I tried your suggestion but code below still validates to true 
```
var EmailSchema = new SimpleSchema({
    emails: {
    type: Array,
   minCount: 1
   },
   'emails.$': {
    type: String,
    regEx: SimpleSchema.RegEx.Email
  }
});

isValid = EmailSchema.namedContext("myContext").validateOne({ emails: ['sdfsdfsf sd'] },"emails");
```

**Comment by aldeed** [comment]
You probably have to pass "emails.$" or "emails.0" as the second arg.

**Comment by emmanuelbuah** [comment]
Mmm. I'm actually using autoForm to submit multiple emails with the schema provided. The comma delimited emails are translated into an array on autoForm formtoDoc hook and visa versa. The issue is that since autoForm is handling the validation, entering something like - sdfsdfsf sd, doesn't invalidate the form.

**Comment by aldeed** [comment]
The invalid keys would be assigned to the individual array item fields, so they wouldn't show up in the form if you don't have fields for those. I would need to see a full reproduction to be able to figure out the best way to make it work.

**Comment by emmanuelbuah** [comment]
Sounds good. I will put a repo together.

**Comment by aldeed** [comment]
@emmanuelbuah, I think putting something like this in your form below your emails field will work.

```html
{{#each invalidEmailFields}}
  <p>{{afFieldMessage name=this.name}}</p>
{{/each}}
```

With helper

```js
invalidEmailFields: function () {
  var c = AutoForm.getValidationContext();
  if (c) {
    return _.select(c.invalidKeys(), function (key) {
      return key.name.indexOf('emails.' === 0);
    });
  }
}
```

Either way, this is an autoform question, so I will close and you can post in the autoform repo if you still need help.

**Comment by emmanuelbuah** [comment]
Sounds good. Thanks.
