### ISSUE TITLE
SimpleSchema.RegEx.Email.test('asasdf@sdfsdf') == true

### ISSUE THREAD

**Issue by emmanuelbuah** [aldeed/meteor-simple-schema#306]
Looks like SimpleSchema.RegEx.Email regex has a bug for 

```
SimpleSchema.RegEx.Email.test('asasdf@sdfsdf') == true
```

**Comment by aldeed** [comment]
That is a valid address. From the readme:

> SimpleSchema.RegEx.Email for emails (uses a permissive regEx recommended by W3C, which most browsers use)

If you want something more specific, you can write your own, but the only way to truly validate an email address is to send an email to it.

**Comment by emmanuelbuah** [comment]
Got it. Just wanted to confirm. Thanks.
