### ISSUE TITLE
Big request: Schema join (including AutoForm)

### ISSUE THREAD

**Issue by AlexFrazer** [aldeed/meteor-simple-schema#309]
Let's say I have a simple database where there are `Students` and `Classes`. It would be very ideal if there was some kind of join where you could create a Schema that relates to other Schemas. For example,
```
StudentSchema = new SimpleSchema({
  name: { type: String },
  classes: [Schema({
    relationship: "Classes",
    max: 5,
    min: 1
  })]
});
```
So if you do `Student.findOne()`, it could look like this:
```
{
  name: "Steve",
  classes: [{
    name: "Calculus",
    department: "Math"
  }, {
    name: "Painting",
    department: "Art"
  }]
}
```
Would this be possible?

EDIT: I know you can kind of do it this way. Maybe it'd be nice to expedite the process.

```
classes: {
  type: [String],
  autoform: {
    options: function() {
      return Classes.find().map(function(doc) {
        return { label: doc.name, value: doc._id};
      })
    }
  }
}
```

**Comment by aldeed** [comment]
This may be done someday in collection2, tracked [here](https://github.com/aldeed/meteor-collection2/issues/31), and then autoform could also take advantage of these relationships as you describe.
