### ISSUE TITLE
Defining object for type

### ISSUE THREAD

**Issue by BrooklynC** [aldeed/meteor-simple-schema#313]
Eric,

This could be a basic javascript question but I'm encountering it through simple-schema so thouht you might be best to ask.  I am trying to set a value for a field (marketCap) in my document to the product of two other fields (lastClose and sharesOs).  I have the following code but keep getting: "Error: Market Cap must be an object".

lib/collections/companies.js

    CapTableSchema = new SimpleSchema({
    lastClose: {
        type: Number,
        label: "Previous Day's Close",
        min: 0,
        optional: true
    },
    sharesOs: {
        type: Number,
        label: "Current Shares Outstanding",
        min: 0,
        optional: true
    },
    marketCap: {
        type: Object,
        label: "Market Cap",
        min: 0,
        optional: true
    }
    });

server/fixtures.js

    MarketCapCalc = {}

    Companies.insert({
        name: "Example",
        sector: "Technology",
        status: "Public",
        capTable: {
            lastClose: "10",
            sharesOs: "100",
            marketCap: marketCapCalc
        }
    });

    marketCapCalc = function () {
        {$multiply: ["$capTable.lastClose", "$capTable.sharesOs"]};
        return marketCapCalc
    };

Am I missing something in my schema definition?  Or is the function definition?  Thanks very much.  Brendan

**Comment by aldeed** [comment]
I haven't worked with mongo aggregation much, but I don't think you can use aggregation operators like `$multiply` outside of a `.aggregate` command, and if you could, I don't think it would be correct to have it in a function. Either way, it's not something simple-schema recognizes and supports. You'd just have to calc before inserting.

```js
var lastClose = 10;
var sharesOs = 100;
var marketCap = lastClose*sharesOs;

Companies.insert({
    name: "Example",
    sector: "Technology",
    status: "Public",
    capTable: {
        lastClose: lastClose,
        sharesOs: sharesOs,
        marketCap: marketCap
    }
});
```

And change `marketCap` schema to `type: Number`.

**Comment by BrooklynC** [comment]
Thanks man
