### ISSUE TITLE
Dynamically Create a Object with Rules

### ISSUE THREAD

**Issue by engenheiro** [aldeed/meteor-simple-schema#315]
Hello, I having trouble to get the mongoDb data to create a object with SimpleSchema Rules dynamically . The client  dont gets the data... But when I put console.log(ObjectWithMongoDbData), the client responds and works very well.

The code:

var services = ServicesCollection.find().fetch(); //ServicesData from mongoDb
ServicesList = {};

_.each(brideServices, function(element, index){ 
    index += 1;
    ServicesList[index] = {
        type: Boolean
    }
});
ServicesSchema = new SimpleSchema(ServicesList);

**Comment by aldeed** [comment]
Make sure your client is subscribed and you wait until the subscription is ready to do your `find`. (Put all your code in the callback to `Meteor.subscribe` on the client.)

**Comment by engenheiro** [comment]
Dont works when I call the schema on a form. And I need duplicate the Schema on the server.
