### ISSUE TITLE
Immutability

### ISSUE THREAD

**Issue by MichelFloyd** [aldeed/meteor-simple-schema#319]
Have you considered an option on a key such as `immutable: true` ?

Some document properties are set at insert but should never be changed after that. It would be awesome for simple-schema to be able to block such changes automatically.

**Comment by aldeed** [comment]
collection2 pkg adds `denyUpdate: true` option, or you can simply strip out attempts to update using an autoValue like

```js
autoValue: function () {
      if (this.isSet && this.isFromTrustedCode) {
        return;
      }

      if (!this.isInsert) {
        this.unset();
      }
    }
```

Both solutions rely on collection2. Immutability doesn't really mean anything outside of a collection context.

**Comment by MichelFloyd** [comment]
Thanks Eric! Just what I needed!
