### ISSUE TITLE
Support multiple instances of the same schema

### ISSUE THREAD

**Issue by pedesen** [aldeed/meteor-simple-schema#321]
Is it possible to generate a form which contains an array of instances of the same schema? It would be very helpful to insert/update and validate multiple documents at once. Something like [Formsets in Django](https://docs.djangoproject.com/en/1.7/topics/forms/formsets/). Does someone has an advice how to accomplish this?

**Comment by aldeed** [comment]
Not directly, but I think you're asking for something similar to [this](http://autoform.meteor.com/update-each). If you don't want to use `autosave` like in the example, you would just have to create a button somewhere, and in the click handler for that button, loop through all the forms and call `$('#formId').submit()`.

**Comment by pedesen** [comment]
Yes, thanks! That should do the trick. Keep up the good work!
