### ISSUE TITLE
Context doesn't return error messages 

### ISSUE THREAD

**Issue by Firfi** [aldeed/meteor-simple-schema#323]
My schema definition looks like this:

    var emailValidation = {
      type: String,
      regEx: SimpleSchema.RegEx.Email
    };

    new SimpleSchema({
    ...
        email: emailValidation,
    ... 
    }

When I call this code on client or on server:

    var ctxt = Schema.UserSignInForm.newContext();
    var valid = ctxt.validate({}); // autoconvert
    console.warn(ctxt.invalidKeys());

It prints out only object with name: 'emai' and type: 'regEx' properties, omitting message property.

I don't have SimpleSchema.messages call in code.

**Comment by aldeed** [comment]
There is no message prop. Once you see what keys are invalid, you can call `ctxt.keyErrorMessage(key)` to get a reactive message string.

If you want to add `message` prop, you could do

```js
var ik = ctxt.invalidKeys();
ik = _.map(ik, function (o) {
  return _.extend({message: Schema.UserSignInForm.keyErrorMessage(o.name)}, o);
});
```

**Comment by Firfi** [comment]
Wow, reading this, I can't remember why I ever suposed that there _must_ be a message property. Thanks!
