### ISSUE TITLE
Thinking about SimpleSchema + Publications

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-simple-schema#326]
*Sorry, this is not really an issue but I wasn't sure where else to discuss this.*

For a while now I've been thinking about ways to centralize more of an app's behavior in SimpleSchema. One example would be deciding which properties need to be published where. 

The common way is defining a list of fields for each publication, but to be it really feels like that could belong inside the schema. 

One idea I had was to add two properties, `publishedTo` and `publishedFor` (both being arrays of `String`s). 

`publishedTo` defines the **publication contexts**, for example `homepage`, `postPage`, `userProfile`, etc.

`publishedFor` defines the **publication roles**, such as `member`, `admin`, `owner`, etc.

By combining both, you could say that a property should only be published to admins when on the user profile page, or to owners of a document when they're on that document's page. 

This would make it a lot easier to ensure you're not publishing unnecessary data or leaking private information.

Of course, this is only tangentially related to SimpleSchema, since most of the work would have to happen inside your publications themselves. But I wanted to get some feedback on this idea, and I'd be curious to know if others have implemented something similar.

**Comment by aldeed** [comment]
This could all be done by a separate pkg. Makes sense to keep it separate from collection2. Here's one possibility for publishedFor:

Override `find` function, roughly:

```
Mongo.Collection.prototype.find = function (selector, options) {
  var self = this;
  options = options || {};

  if (options.userId) {
    // Check READ security and omit fields we shouldn't be publishing to this user
    options.fields = _.select(options.fields, function (val, field) {
      var allowedRoles = self._getAllowedRolesForFieldBasedOnSchema(field);
      return Roles.userIsInRole(options.userId, allowedRoles);
    });
  }

  superFind.call(this, selector, options);
};
```

Then by simply passing `userId` option, you get the schema-based field filtering.

```javascript
collection.find({}, {fields: {foo: 1, bar: 1}, userId: this.userId});
```
