### ISSUE TITLE
Empty strings / accounts create

### ISSUE THREAD

**Issue by sylido** [aldeed/meteor-simple-schema#327]
Something similar to the already closed #156 - when I create a new user using the `accounts-ui` package it creates the optional fields in profile - firstName, lastName, organizaiton, but since they are empty simple-schema/collection2 removes them from the profile object.

Which is fine, we don't really want empty string fields, but when I try creating an Account Information page that displays these optional values (and the user can set them for the first time), yet it gets stuck because the keys don't exist.

The solution I was thinking of is to use the `removeEmptyStrings : false` but it doesn't seem like I have direct access to the insert/update happening in the `accounts-ui` package. What's the solution to this, custom helper to handle the case where they are not defined ? 

I mean, they are set to "optional" in the schema, so it shouldn't fail at creating the form, it should be created with no values set to those fields and on update it should do a $set on those new fields if they have a non-empty string value.

**Comment by aldeed** [comment]
Is the profile form autoform or your own custom form? AutoForm shouldn't have any problem with the missing profile object.

**Comment by sylido** [comment]
You are right, I take that back, it's not the empty fields, it works fine on another account with that info missing. It is an autoForm that uses afQuickFields.

It's stuck on the "Loading..." template and doesn't even render the form if I remove all the afQuickFields.
I don't get any output that tells me what's really wrong, here's a [pastebin](http://pastebin.com/6Yv4BX8t) of what I have - the template is at the bottom and it's in Jade.

**Comment by sylido** [comment]
OK, completely wrong here - wasn't autoforms/scheme at all - it was a lack of user data, even though I could see it using `Mongol` it actually wasn't getting published for some reason...very weird.

**Comment by sylido** [comment]
Even the before hooks weren't triggering correctly so reference this [iron-router issue](https://github.com/iron-meteor/iron-router/issues/1268). I was wondering what was happening, hopefully it's fixed by the time someone finds this.
