### ISSUE TITLE
Update Simple Schema object in collection

### ISSUE THREAD

**Issue by abtx** [aldeed/meteor-simple-schema#334]
Hi,
I've got a collection that uses Simple Schema. Most of the objects are simple, but there are some dynamic ones too, and I've got problem with updating these. Object would look something like milestones: {
    type: Array,
    optional: true}}
and
'milestones.$.complete': {
    type: Boolean
  }
How would I update 'complete' property in this type of objects? I tried go this way:
Projects.update({_id:currentPostId, 'milestones.$.name':this.name}, {$set:{completed:true}}); 
and few others, but none work. 
What would be the correct notation for this?

**Comment by aldeed** [comment]
`Projects.update({_id:currentPostId, 'milestones.name':this.name}, {$set:{'milestones.$.name':true}});`

See here: http://docs.mongodb.org/manual/reference/operator/projection/positional/#proj._S_
