### ISSUE TITLE
Field that can take one of multiple values (each with its own schema)

### ISSUE THREAD

**Issue by KrishnaPG** [aldeed/meteor-simple-schema#341]
What is the recommended method?

I have parent schema that holds charts, where the chart type could be one of many types, each with its own schema. For example,
````
myCharts =  new SimpleSchema({
   chartInstances: [Object],
   "chartInstances.$.chartType":  ??  // could be one of pie, bar, line so on... How to imply it?
});
pie = new SimpleSchema({   ratios: [integer] });
bar = new SimpleSchmea( { x: [integer], y: [integer], colorscehme; .... })
line = new SimpleSchema( .... )
````

**Comment by trusktr** [comment]
I'm wondering the same exact thing as you in one of my cases (it's called "cardType" in my case).

I'm also wondering about things like having a String or null. Does the following work?

```js
  // _id of a parent CardRelationship.
  parentId: { type: String, regEx: Id, custom: function() {
      if (!this.value.match(Id) || this.value !== null)
          return 'spaceId is not a valid _id or is not null.'
  }},
```

**Comment by trusktr** [comment]
Nevermind for my second case. Null or undefined values are allowed: https://github.com/aldeed/meteor-simple-schema/blob/cc9e76eaabc615e3a530b14c56dfc97e278030cd/simple-schema-validation-new.js#L153

I guess if we don't want null or undefined values then we *must* add a custom validator? An option to configure this would be nice! @aldeed 

For my first case (like your case @KrishnaPG), we can probably just write a `custom` validator, and validate on that.

```js
myCharts =  new SimpleSchema({
   chartInstances: [Object],
   "chartInstances.$.chartType":  {
     type: String
   },
   "chartInstances.$.chartInstance":  {
     type: Object,
     custom: function() { /* Check if this object matches the Schema with name parent.chartType */ }
   }
});
```

**Comment by john-osullivan** [comment]
How did you all resolve this?  I'm doing the exact same thing right now and running into an issue with the approach you were describing in that last post, @trusktr .  My custom validation function checks a `packageType` field and then uses it to validate against one of four possible schema.  The function itself, however, isn't receiving the values I passed in.  The keys from the input object match up with the schema, and the input object has the right object nested in the right key, but the validator on that key is getting an empty object as a value.  Kinda throws a wrench in my plans.  How did you two work this one out?

**Comment by trusktr** [comment]
I just used Meteor check and Match.

**Comment by trusktr** [comment]
(Instead of simple schema)

**Comment by aldeed** [comment]
SS does not support dynamic types. You can dynamically create the whole schema and then validate against it.
