### ISSUE TITLE
how to set default/auto value of a field based on _id

### ISSUE THREAD

**Issue by KrishnaPG** [aldeed/meteor-simple-schema#342]
I have a `name` field that when not specified I would like to have a default value something like `base+_id`.  If user specifies any value, it should take precedence over the default value

How to achieve this? Tried be below, but it gives `_id` as 'undefined'
````
gSchemas.esChartInstances = new SimpleSchema({
    chartName: { 
        type: String,
        autoValue: function () { if (this.isInsert) return "chart-" + this.field('_id').value; }
    }, 
});
````
It is not giving the "_id" value, rather it is giving "chart-undefined" for all.

**Comment by aldeed** [comment]
Collection2 package removes the _id before running autoValues. It's related to some other things that I plan to change eventually, so it can probably be fixed. But it's a collection2 issue, so can you post this over in that repo instead?

**Comment by KrishnaPG** [comment]
Thanks @aldeed . Done https://github.com/aldeed/meteor-collection2/issues/217
