### ISSUE TITLE
check() with simpleSchema not matching Collection2 Date type

### ISSUE THREAD

**Issue by adamdawkins** [aldeed/meteor-simple-schema#346]
This issue seems to be a bit of a mixture of simple schema, Collection2 and autoform, but I thought I'd raise it at the root, which I **think** is in Simple Schema. Sorry if I'm wrong!

I have a Collection2 collection with an optional birthday field:

```coffee
Schemas.Subscription = new SimpleSchema(
  birthday:
    type: Date
    optional: true
)

Subscriptions.attachSchema(Schemas.Subscription)
```

When I submit an autoform with the date quickField, this works as expected. It gets stored as a date on the collection. So far so good.

I also have a server API which can take the results of a POST request. The `birthday` parameter in that requested is formatted correctly as a string of `YYYY-MM-DD`, but when I check the parameters in my Meteor method before inserting, it throws an error on the date:

```coffee
Meteor.methods
  'subscriptions.new': (subscription) ->
    check subscription, Subscriptions.simpleSchema()
    Subscriptions.insert subscription
```

where `subscription.birthday` is `1990-07-27`, the check fails because the object doesn't match the schema. The invalid key being thrown on the birthday field is expectedConstructor.

If I don't check the subscription on the way in, `Subscriptions.insert()` still correctly converts the passed string into a date.

What's the correct way for me to deal with this? I want to `check()` each Meteor method, as it's best practice, but am I already protected enough in this case from the schema attached to the Collection2 not to worry?

**Comment by niklasp** [comment]
+1

**Comment by aldeed** [comment]
You need to do `subscription.birthday = new Date(subscription.birthday)` before validating and inserting, which is what `Subscriptions.simpleSchema(subscription).clean()` would also do, which is what `insert` also does by default. So either don't `check` (which should be safe in this case), or `clean` before you check.
