### ISSUE TITLE
Very slow updates because of SimpleSchema

### ISSUE THREAD

**Issue by nerdmed** [aldeed/meteor-simple-schema#347]
Dear Team, i have a lot of trouble using simple schema. At the beginning and creation of a document updates are very fast. But as soon as my document grows updating a simple number field causes the browser to freeze for nearly 5 seconds. I have very lange objects and data inside the schema but these are blackboxed.

Is it possible that SimpleShema is validating the whole document on every update?
I tried to disable validation in the options for the update: No change - Meteor Error with simulation timeout ?!
I tried to disable cleaning: No Change
I tried to activate SimpleSchema.debug - No Output

Its really frustrating. Right now the issue only resolves when i remove the Schema from the collection!
Would be great to get a hint on how to proceed. 

Kind Regards
Ahmed

**Comment by hamxiaoz** [comment]
I had similar problem. I switched to just use plain meteor collection and it became fast again.

**Comment by mraak** [comment]
Had the same problem here too.

**Comment by nerdmed** [comment]
@aldeed would be great to get any reaction on this. I think using plain meteor collection is not the way to go.

**Comment by joejeet** [comment]
Same problem. Any updates on this @aldeed

**Comment by aldeed** [comment]
I cannot debug this without a link to an example app repo that reproduces the issue. It may also be related to some performance issues being documented in https://github.com/aldeed/meteor-simple-schema/issues/494
