### ISSUE TITLE
Relational Schema not inserting

### ISSUE THREAD

**Issue by faebuk** [aldeed/meteor-simple-schema#349]
Hey there

I got following schema: 
http://pastebin.com/PFwTn3JT

the schema is basically normalized because of the data integrations. So first of all is the db design right? Or how should it be done? 

If I'm then inserting data with following code:
http://pastebin.com/XNBcPaM5
the relations don't get inserted. and if they get inserted, the values are inserted and not the _id from the collection item. 

Might someone tell me how to do relations with inserting id with simple schema?

Greetings

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.
