### ISSUE TITLE
How to merge few or more SimpleSchema?

### ISSUE THREAD

**Issue by shkomg** [aldeed/meteor-simple-schema#350]
Hi,

I need to conditionally build SimpleSchema from standard blocks: field name & type pairs. To let app admin to customize current product properties.

For example I have to build SimpleSchema from this kind of data: 
```
a= [
{name:'title', type: 'string'},
{name:'description', type: 'string'},
{name:'price', type: 'number'},
{name:'qty', type: 'number'},
];
```

To look like this:
```
aSchema= new SimpleSchema({
title: {type:String},
description: {type:String},
price: {type:Number},
qty: {type:Number}
});
```
It looks like good solution to have one big schema with all the blocks I may need to be defined. And use ```.pick```to build new custom SimpleSchema. But I'll need to pick multiple fields with the same name like (in resulting schema there will be only one from them):
```
var newSchema = bigSchema.pick(['title', 'title']);
```
Also I tried to do like this:
```
a = aSchema.simpleSchema().pick('title'); 
obj=[{aa:{type:a}},{bb:{type:a}}]; 
c=new SimpleSchema(obj);
```
and this way ```c``` has strange SimpleSchema like this:
```
{
a:{type:...},
a.title:{type:String} <-- this one is right
}
```

@aldeed is there any proper way to do such a building of new SimpleSchema out of other SimpleSchema blocks? Maybe some cheat way?

Thank you.

**Comment by shkomg** [comment]
Looks like it may work like this:

```
a = aSchema.simpleSchema()._schema.title; obj=[{aa:a},{bb:a}]; c=new SimpleSchema(obj);
```

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.
