### ISSUE TITLE
Dynamically creating schema error

### ISSUE THREAD

**Issue by mchan75** [aldeed/meteor-simple-schema#354]
I am saving my app schemas in a collection so that I can load them dynamically, but when I try to create a new schema dynamically, I get error ( Uncaught Error: Invalid definition for label field. ), so I was wondering if there is anything I am missing / doing wrong in the code I am using (shown below)? Thanks.  

    Template.SchemaGenTemp.events({
       'click #createSchema': function(e, t){

          var x = ClassifiedsTemp.find({}).fetch(); 

          var Schema = {};
          _.each(x[5].fieldsList, function(item) { 
            Schema.ClassTest = new SimpleSchema(item);
          });
       }
    });

Object retrieved from the schemas collection:
Object {label: "testt", min: "1", max: "11", regex: "", _id: "XvexYrB35daCvvJCH"}

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.

**Comment by artjomg** [comment]
Is there any example how to store a SimpleSchema definition in a collection?
