### ISSUE TITLE
[Question] Autovalue conditional field

### ISSUE THREAD

**Issue by Difusio** [aldeed/meteor-simple-schema#355]
I've got this (truncated) object: 
````
Schemas.Shift = new SimpleSchema({
    ...
    pending: {
        type: Boolean,
        optional: true
    }
    takers: {
        type: [Meteor.Collection.ObjectId],
        optional: true
    },
    incompleteTrade: {
        type: [Meteor.Collection.ObjectId],
        optional: true
    },
    completeTrade: {
        type: [Meteor.Collection.ObjectId],
        optional: true
    }
    ...
});
   
````

I've got a takeShift method:

````
takeShift: function (shiftId) {
        Shifts.update(
            shiftId,
            {$push: { takers: this.userId }}
        )
    }
````

I'm trying to set pending as an autovalue depending on completeTrade and Takers. If either of them isn't empy then pending should be set to true.

This is what I tried:

````
    pending: {
        type: Boolean,
        autoValue: function () {
            var completeTrade = this.field("completeTrade");
            var takers = this.field("takers");
            return completeTrade.value || takers.value;
        },
        optional: true
    },
````

The goal is that when either `takers` or `completeTrade` is updated we check if either of them has any value left and if so, set pending to True, otherwise to False.

The problem I'm having is that with my attempt, the takers update isn't passing and nothing is happening.

**Comment by jadsonlourenco** [comment]
if you add it ```if (this.isUpdate)```? So:
```
pending: {
        type: Boolean,
        autoValue: function () {            
            var takers = this.field("takers").value;
            if (this.isUpdate && takers) {
                return takers;
            } else {
                this.unset();
            }
        },
        optional: true
    },
```
But I recommend to use this **if** to both inputs values, I don't know your idea about this to use two fields, but just use it, the **operation** to set the value. I hope this help.

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.
