### ISSUE TITLE
optional:true SubSchema field returning validation error

### ISSUE THREAD

**Issue by nixoz** [aldeed/meteor-simple-schema#357]
Hello,
Maybe i'm just bloody stupid and doing something wrong, but recently need some help.

i'm now into this issue. 

I have this schemas:

```javascript

ET.Schemas.OrderItems = new SimpleSchema({
  product: {
    type: ET.Schemas.Products, 
    label: "Product Full Document"
  },
  size: {
    type: ET.Schemas.Sizes,
    label: "Size Full Document"

  },
  color: {
    type: ET.Schemas.Colors,
    label: "Color Full Document"
  },
  location: {
    type: ET.Schemas.Locations,
    label: "Location Full Document"
  },
  unitPrice: {
    type: Number,
    label: "Custom price for position"
  },
  qnty: {
    type: Number,
    label: "Amount of Units"
  }
});

ET.Models.Orders = new Mongo.Collection("orders");
ET.Schemas.Orders = new SimpleSchema({

  items: {
    type: ET.Schemas.OrderItems,
    optional: true
  },
  client: {
    type: ET.Schemas.Clients,
    optional: true
  },
  totalCount: {
    type: Number,
    label: "Total items",
    optional: true
  },
  totalCost: {
    type: Number,
    label: "Total costs",
    optional: true
  },
  status: {
    type: String,
    label: "Order status",
    optional: true
  },
  type: {
    type: String,
    label: "Type of order",
    optional: true
  },
  creator: {
    type: String,
    autoValue: function() {
      if (this.isInsert) {
        return Meteor.userId();
      } else if (this.isUpsert) {
        return {$setOnInsert: Meteor.userId()};
      } else {
        this.unset();
      }
    }
  },
  createdAt: {
    type: Date,
    autoValue: function() {
      if (this.isInsert) {
        return new Date();
      } else if (this.isUpsert) {
        return {$setOnInsert: new Date()};
      } else {
        this.unset();
      }
    }
  },
  updatedAt: {
    type: Date,
    autoValue: function() {
      if (this.isUpdate) {
        return new Date();
      }
    },
    denyInsert: true,
    optional: true
  },
  deliveredAt: {
    type: Date,
    optional: true
  },
  description: {
    type: String,
    label: "Brief summary",
    optional: true,
    max: 2000
  }
});

ET.Models.Orders.attachSchema(ET.Schemas.Orders);

```

As you can see, main schema here is Orders. and all fields are optional(well, not all, autofield are still generated). So, in theory i can just insert empty document. But i just can't do that. I'm getting validation error with "required" fields in SubSchemas of OrderItems field(but OrderItems is optional and not required).

p.s. i'm not included the ET.Schemas.Products; ET.Schemas.Sizes, ET.Schemas.Colors (they have nothing special just the schemas, but with some fields which are not optional)

What i'm doing wrong?

**Comment by kop** [comment]
I have this issue too. But I've noticed that it only appears when I'm trying to insert a document.

My schema:

```javascript
ProspectSearchesCollection.schema.SearchRequest = new SimpleSchema({
    query: {
        type: String,
        max: 255
    },
    scopes: {
        type: [String],
        optional: true,
        defaultValue: []
    },
    page: {
        type: Number,
        optional: true,
        defaultValue: 1
    }
});
ProspectSearchesCollection.schema.SearchResult = new SimpleSchema({
    stats: {
        type: ProspectSearchesCollection.schema.SearchResultStats
    },
    items: {
        type: [ProspectSearchesCollection.schema.SearchResultItem],
        optional: true,
        defaultValue: []
    }
});
ProspectSearchesCollection.schema.Main = new SimpleSchema(
    {
        uniqueKey: {
            type: String
        },
        request: {
            type: ProspectSearchesCollection.schema.SearchRequest
        },
        result: {
            type: ProspectSearchesCollection.schema.SearchResult,
            optional: true
        }
    }
);
```

When I do:

```javascript
ProspectSearches.insert({ request: { query: 'test', scopes: [ 'G29NkoYmJudTN3ot7' ], page: 1 }, uniqueKey: '47edbd181a9cf46013ef31144c23c5bb35d94772-1'});
```

I get `insert failed: Error: Stats is required`.

Hovewer, if I do:

```javascript
ProspectSearches.simpleSchema().namedContext().validate({ request: { query: 'test', scopes: [ 'G29NkoYmJudTN3ot7' ], page: 1 }, uniqueKey: '47edbd181a9cf46013ef31144c23c5bb35d94772-1' });
```

It returns `true`.

**Comment by kop** [comment]
I found what is causing problems in my code. It's `defaultValue` directive.

It sets value `[]` for the `result.items` key and SimpleSchema validates `result` object. Maybe, to avoid such issues, it makes sense to flag somehow whether it was a default value set or custom one? And if it's default value and parent object is optional, such value should be probably ignored?

**Comment by tagrudev** [comment]
I have the same issue on insert even though I am using the optional: true option (and not setting any defaultValue) my custom validation is still running ...

**Comment by Pagebakers** [comment]
Having the same issues here, any news on this?

**Comment by aldeed** [comment]
@kop: `defaultValue` is always set on insert so of course it creates any empty parent objects as necessary to do that, which means some required value will be missing. If you want to have a default value only when the object already exists, then you can use a more advanced customer `autoValue` for that.

@tagrudev: Custom validation always runs because you might want to use it to make something conditionally required. Please submit a different issue with more details if you think your case is not as expected.

@nixoz If anything ANYWHERE has a `defaultValue`, for example in `ET.Schemas.Products/Sizes/Colors/Locations` or anywhere deeply nested within that, then all of the necessary objects will be auto-created in order to set that default value. Which might then make there be missing required fields. If you want to have a default value only when the object already exists, then you can use a more advanced customer `autoValue` for that.
