### ISSUE TITLE
Array with minCount cannot be optional?

### ISSUE THREAD

**Issue by st3phan** [aldeed/meteor-simple-schema#359]
The following Schema has an answers Object with a minCount and maxCount and it should be optional. But it's always giving an required error. An object with minCount and/or maxCount cannot be optional?

````
Error in quickForm pre-submit validation Error: Answers is required {invalidKeys: Array[1], stack: (...), message: "Answers is required"}
````

Here's a meteorpad: http://app-aajychm7.meteorpad.com/

````javascript
Schemas.Answer = new SimpleSchema({
    _id: {
        type: String,
        regEx: SimpleSchema.RegEx.Id,
        autoValue: function() {
            return Random.id();
        },
        autoform: {
            type: 'hidden'
        }
    },
    text: {
        type: String,
        autoform: {
            placeholder: 'Answer text',
            label: false
        }
    }
});

Schemas.Question = new SimpleSchema({
    answers: {
        type: [Schemas.Answer],
        minCount: 2,
        maxCount: 10,
        optional: false
    }
});
````

**Comment by zimme** [comment]
`optional: false` -> `optional: true`

However I don't think you can have optional in combination with `minCount` as you're saying the array should have at least 2 objects for the schema to be valid.

BUT I'm not sure about this.

**Comment by st3phan** [comment]
So I've been scratching my head on this for a few days now and finally found out that the issue was on my side. The culprit was in one of my before hooks:

````javascript
AutoForm.hooks({
    questionUpdateForm: {
        before: {
            'method-update': function(doc) {
                // https://github.com/aldeed/meteor-autoform/issues/914
                doc.$set.answers = _.compact(doc.$set.answers);
                return doc;
            }
        }
    }
});
````

The `_.compact function fixes a small bug as described in the link in the comment above. This function returns an empty array when the answers object is submitted empty. AutoForm then correctly throws a validation error because of the minCount option that is set in the schema. I fixed this by wrapping it in an if statement:

````javascript
// https://github.com/aldeed/meteor-autoform/issues/838#issuecomment-96078925
if (doc.$set.answers) {
    doc.$set.answers = _.compact(doc.$set.answers);
}
````

To confirm that this was on my side I've created a meteorpad where the required property works as expected when setting a minCount: http://meteorpad.com/pad/o6Lgq6paqfcJr7idf/Autoform:%20Optional%20Object%20field%20is%20required
