### ISSUE TITLE
Impossible to pull in a Array

### ISSUE THREAD

**Issue by Flavien-Pensato** [aldeed/meteor-simple-schema#367]
Hello,

Sorry, I'm beginning with SimpleSchema. I can't pull a element in my array but I can push. See.

My schema
  photos: {
    type: [Object],
    optional: true
  },

  "photos.$.url": {
    type: String,
    label: "url"
  },
  "photos.$.relative_url": {
    type: String,
    label: "relative_url"
  },
});

and my functions:

  'updatePhotoProduct': function(url, relative_url, productId) {
    check(url, String);
    check(relative_url, String);
    check(productId, String);
    Products.update(productId, {
      $push: {
        photos: {
          "url": url,
          "relative_url": relative_url
        }
      }
    });
  },

  'deletePhotoProduct': function(url, relative_url, productId) {
    check(url, String);
    check(relative_url, String);
    check(productId, String);

    Products.update(productId, {
      $pull: {
        photos: {
          "url": url,
          "relative_url": relative_url
        }
      }
    });
  },

Please help me!

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.

**Comment by Klatalk** [comment]
I have the same issue, I can easily add subdocuments but using $pull doesn't remove them.

**Comment by Flavien-Pensato** [comment]
Pull does not work on the client side but if you do it one the server. It's all right ☺

**Comment by Klatalk** [comment]
My issue was server side.
I had to redesign my collections to work more like a relational database and I've got more control on each Collection. My app won't have a lot of data/users so I guest performance won't be an issue..
Still interested in a better solution.

**Comment by cdolek** [comment]
I am having the same issue. Push works but pull does not.

**Comment by aldeed** [comment]
Closing since this seems to be more of a collection2 issue, and there is an issue for it in that repo already: https://github.com/aldeed/meteor-collection2/issues/284
