### ISSUE TITLE
Accessing sub schema members

### ISSUE THREAD

**Issue by eoliphan** [aldeed/meteor-simple-schema#368]
Hi, I'm using SimpleSchema with Autoform and can't quite figure out what I'm doing wrong in relation to using a subschema

I basically have 

Address = new SimpleSchema()
X = new SimpleSchema()
XWithAddress = new SimpleSchema([X,{address:{type:Address}}]);

in a quickForm using XWithAddress as its schema the following doesn't work

{{> afQuickField name="address.line1" }}

nor does 

{{> afObjectField name="address"}}

**Comment by bySabi** [comment]
Please shared a github repo or meteorpad.

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.
