### ISSUE TITLE
addValidator is working right or I don´t undestand how do it??

### ISSUE THREAD

**Issue by bySabi** [aldeed/meteor-simple-schema#369]
Hello.
I add a custom option with `extendOptions` this way:
```
SimpleSchema.extendOptions({
    capilowerize: Match.Optional(Boolean)
});
```
Then I can write schema´s like this:
```
UsuarioSchema = new SimpleSchema({
    nombre: {
        type: String,
        capilowerize: true
    },
    apellido1: {
        type: String,
        capilowerize: true
    }
});
```

and  add a global validator:
```
SimpleSchema.addValidator(function () {
    if (this.definition.capilowerize && !_.isNull(this.value) && _.isString(this.value)) {
        var string = this.value;
        
        //Ex: FRED -> Fred
        string = string.toLowerCase();
        string = string.charAt(0).toUpperCase() + string.slice(1);
        
        this.value = string;
        console.log('[value]: "', this.value, '" on [key]: ', this.definition);
    }
});
```

This work fine. Validator change `this.value` but object inserted on collection still have original value. Say {nombre: 'FRED'}.
What I do wrong??

Here is a test repo: https://github.com/bySabi/autoform-test checkout `case1`branch.

Thanks.

**Comment by djlogan2** [comment]
The validator will only validate, not change values. To change values, you need to use the autoValue property:

var schema = new SimpleSchema({
firstname: {
  type: String,
  autoValue: function() {
    if(this.isSet) {
        string = string.toLowerCase();
        string = string.charAt(0).toUpperCase() + string.slice(1);
        return string;
    }
  }
}
});

or something along those lines. Validators will only tell simple-schema whether to allow the Mongo operation or not.

**Comment by bySabi** [comment]
Ah! .. thanks for info @djlogan2
