### ISSUE TITLE
TypeError: Cannot read property 'Id' of undefined (SimpleSchema.RegEx)

### ISSUE THREAD

**Issue by dandv** [aldeed/meteor-simple-schema#371]
I'm trying to use SimpleSchema.RegEx from another package, and I'm getting

> TypeError: Cannot read property 'Id' of undefined

To reproduce, `meteor run` https://github.com/dandv/simple-schema-regex-undefined. What is the package missing?

**Comment by awei01** [comment]
seems like duplicate of #390

**Comment by aldeed** [comment]
Should be `api.use('aldeed:simple-schema@1.3.0');`

Without the version it pulls in a very old version of the package.

**Comment by JulianKingman** [comment]
How does this work with react, ie `import SimpleSchema from 'meteor/aldeed:simple-schema';`?
