### ISSUE TITLE
Embedding documents in Simpleschema

### ISSUE THREAD

**Issue by aryamazaheri** [aldeed/meteor-simple-schema#372]
Hi,
I need to embed documents to access their keys inside my collection. For instance, this is my schema definition:
```javascript
Displays = new Mongo.Collection('displays');
DisplayGroups = new Mongo.Collection('displayGroups');

var Schemas = {};

Schemas.Display = new SimpleSchema({
    name: {
        type: String
    },
    group: {
        type: Schemas.DisplayGroups,
        optional: true
    },
    'group.name': {
        type: String
    }
});

Schemas.DisplayGroups = new SimpleSchema({
    name: {
        type: String,
        optional: false
    },
    description: {
        type: String,
        optional: true
    }
});

Displays.attachSchema(Schemas.Display);
DisplayGroups.attachSchema(Schemas.DisplayGroups);
```
However, group.name is not available in the database after creation. Any idea what is wrong?

**Comment by harmon25** [comment]
Looks like you are trying to represent relationships between collections.
Sadly this will not work...

The group property of the Display schema should contain an autoform, options property.
```
Schemas.Display = new SimpleSchema({
    name: {
        type: String
    },
    groupId: {
        type: String,
        regEx: SimpleSchema.RegEx.Id,
        optional: true,
        autoform: {
          options: displayGroups
          }
    }
});

```
This can be a function which returns all DisplayGroups:
```
displayGroups = function(){
  groups = DisplayGroups.find({})
  var options = $.map(groups, function(g){
    return {label:g.name, value:g._id}
  });
  return options
}
```

This way, Autoform produces all DisplayGroup names and IDs for a Dropdown when inserting into the Displays collection.

This is a loose relationship, the group field within a display document now stores the ID of the group for which that display belongs...

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.
