### ISSUE TITLE
Add support for validating an array of objects with check()

### ISSUE THREAD

**Issue by Aralun** [aldeed/meteor-simple-schema#376]
Reproduction code:

    var schema = new SimpleSchema({
      aField : { type : String }
    });

    check( [ { aField : 'foo' } ], schema);

This will throw `TypeError: key.substring is not a function` at the following line:

    SimpleSchema.prototype.condition = function(obj) {
      var self = this;

      //determine whether obj is a modifier
      var isModifier, isNotModifier;
      _.each(obj, function(val, key) {
          if (key.substring(0, 1) === "$") {  //Boom! -> key === 0

**Comment by Aralun** [comment]
Any update, research, confirmation on this?

**Comment by d4nyll** [comment]
Just a comment to say I also came across this exact same issue.

**Comment by aldeed** [comment]
This is supported in 2.0: https://github.com/aldeed/node-simple-schema#validate-an-array-of-objects-and-throw-an-error
