### ISSUE TITLE
Asynchronous Custom Validation and Named context problem

### ISSUE THREAD

**Issue by Adiel-Sharabi** [aldeed/meteor-simple-schema#378]
Hi, 
I'm using AutoForm to populate 2 forms (one for insert and another for update). 
I have a field with custom  asynchronous validation to check the the field is unique. 
The demo of "Asynchronous Custom Validation" uses specific form name. 
I need to do different check if this is insert (check against the database) or update (check only if the field is different then the source). 

1. How can i do that? 
2. How can I addInvalidKeys to different forms? 

Thanks.

**Comment by AlexFrazer** [comment]
did you try:
```
custom: function () {
  if (this.isInsert) {
    Meteor.call('insertValidate', this.value, function (err) {
      if (err) {
        MySchema.namedContext('insert-form').addInvalidKeys({
          // ...
        });
      }
    })
  } else if (this.isUpdate) {
    Meteor.call('updateValidate', this.value, function (err) {
      if (err) {
        MySchema.namedContext('insert-form').addInvalidKeys({
          // ...
        });
      }
    })
  }
}
```

**Comment by Adiel-Sharabi** [comment]
awesome!! 
I didn't know such property even exist. 
Thanks.

**Comment by thearabbit** [comment]
Excuse me, we should return what for the `result`
```js
// In doc
.........
if(!result){
...........
}

// this
if(err){
...........
}
```
which one and `result` value for return?

**Comment by thearabbit** [comment]
I have problem with `onSuccess Hook`, it run before `custom validate`
