### ISSUE TITLE
Uncaught ReferenceError: SimpleSchema is not defined When Deployed

### ISSUE THREAD

**Issue by yozawiratama** [aldeed/meteor-simple-schema#380]
I get 
    Uncaught ReferenceError: SimpleSchema is not defined
when deploy meteor app on server. because it bundled i dont know where it wrong.
why this only happend when it bundled and deployed. on development i dont meet this.
thanks

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.
