### ISSUE TITLE
How  to manage an asyncronous `addValidator` for a namedContext?

### ISSUE THREAD

**Issue by AlexFrazer** [aldeed/meteor-simple-schema#381]
Let's say I wanted to validate my whole form, but needed to make a call to the back end to do it.

> To add a custom validation function that is called for all keys for a specific SimpleSchema instance, use mySimpleSchema.addValidator(myFunction).

```
// validate an address by looking up the whole address through a meteor method
AddressSchema.addValidator(function () {
  Meteor.call('Address._validateAddress', this.value, function (err) {
    // ???
  });
});
```

While the docs show how to use it for a single key, it doesn't seem very clear how to use it for an _entire form_. How would this be done?

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.

Also, this is more of a collection2 or autoform question, since simpleschema could simply be run in the method and then send the invalidKeys back to the client.
