### ISSUE TITLE
Reactive method not being called in autorun

### ISSUE THREAD

**Issue by jaypanares** [aldeed/meteor-simple-schema#385]
Hi, I'm trying to replicate the autorun function from the docs:

```
if (Meteor.isClient) {
  Meteor.startup(function () {
    Tracker.autorun(function () {
      var context = Schemas.Login.namedContext('schemasLogin');
      console.log(context.invalidKeys());
    });
  });
}
```

but the `console.log(context.invalidKeys());` get's called only once.  Shouldn't the `log` get called every time the result of `.invalidKeys()` changes since it is reactive?

What I'm trying to do is have the console log the invalid keys as a user makes changes to the form.  The result should be that for every field that the user corrects, the number of invalid keys that are outputted to the console gets smaller.

Currently the `.log` gets called only once.

Thanks!

**Comment by aldeed** [comment]
Yep, any time you call `validate()`, `validateOne()`, `resetValidation()`, or `addInvalidKeys()`, `invalidKeys()` will rerun. If it isn't working, you'll need to provide a link to a reproduction app.
