### ISSUE TITLE
Not an issue. Need help quickly. Schema update after attached

### ISSUE THREAD

**Issue by iSuslov** [aldeed/meteor-simple-schema#386]
Hi guys, forgive me for asking here but I need any help urgently. I'm modifying telescope, that uses simple schema. They initialise it like this 

Settings = new Mongo.Collection("settings");

Settings.schema = new SimpleSchema({
...
})

Settings.attachSchema(Settings.schema);

Is it possible for me after that having access to Settings variable, add some new fields to this schema? I looked at documentation and tried clean method, but I'm afraid I don't understand it fully.

**Comment by chafey** [comment]
I just started using SimpleSchemas today and ended up here because I had the same question.  If you have data in the database and then need to expand the schema, it seems you need to provide default values for the new schema values via the defaultValue setting.

**Comment by AlexFrazer** [comment]
Having the same problem myself, would be nice to be able to modify a schema after instancing

**Comment by aldeed** [comment]
When `Settings.attachSchema` is called again, it merges the new schema with the already attached one. (That was not quickly, but that is the answer. :) )
