### ISSUE TITLE
Match error reported on '_id' field

### ISSUE THREAD

**Issue by devillex** [aldeed/meteor-simple-schema#387]
When validating collection documents against a schema (of type SimpleSchema), I get the following Match error: _id is not allowed by the schema 

**Stack trace of Match Error:**
```
W20150623-22:26:48.348(2)? (STDERR) Error: Match error: _id is not allowed by the schema
W20150623-22:26:48.348(2)? (STDERR)     at [object Object].SimpleSchema.condition (packages/aldeed:simple-schema/simple-schema.js:602:1)
W20150623-22:26:48.349(2)? (STDERR)     at checkSubtree (packages/check/match.js:220:1)
W20150623-22:26:48.349(2)? (STDERR)     at check (packages/check/match.js:32:1)
W20150623-22:26:48.349(2)? (STDERR)     at app/server/bootstrap.js:72:5
W20150623-22:26:48.349(2)? (STDERR)     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:965:1)
W20150623-22:26:48.349(2)? (STDERR)     at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:812:1)
W20150623-22:26:48.349(2)? (STDERR)     at validateFosMap (app/server/bootstrap.js:71:20)
W20150623-22:26:48.349(2)? (STDERR)     at app/server/bootstrap.js:2:3
W20150623-22:26:48.349(2)? (STDERR)     at /home/.../boot.js:229:5
```

**Code from 'bootstrap.js':**
```javascript
function validateFosMap() {
  var qualFosMapCursor = QualificationFieldOfStudyMap.find();

  qualFosMapCursor.forEach(function (fosMapping) {
    check(fosMapping, QualificationFieldOfStudySchema);
  });
}
```

**Schema definition:**
```javascript
QualificationFieldOfStudySchema = new SimpleSchema({
  fieldOfStudy: {
    type: String,
    label: 'Field of Study'
  },
  mappedKeywords: {
    type: [String],
    label: 'Mapped Keywords',
    minCount: 1
  },
  fieldOfStudyId: {
    type: String,
    label: 'ID (don\'t set or update)',
    autoValue: function () {
      var fos = this.field('fieldOfStudy');
      if (fos.isSet) {
        return fos.value.replace(/\s/g, ''); // remove spaces
      } else {
        this.unset(); // prevent user from setting their own value
      }
    }
  }
})
```

**Example document:**
```json
{
  "_id" : ObjectId("5585630935f8834cf6939a59"),
  "fieldOfStudy" : "Theology",
  "fieldOfStudyId" : "Theology",
  "mappedKeywords" : [ "theology", "ministry" ] 
}
```

Please let me know if I can provide any additional information.

**Comment by jedwards1211** [comment]
Does simple-schema not allow us to use our own `_id`s?

**Comment by sean-stanley** [comment]
+1,

either we have to add an _id field to our schemas or delete the `_id` key off a clone of the document to validate the rest of the document.

**Comment by BudgieInWA** [comment]
+1, this is a pain when doing and `upsert` using `$set`

**Comment by aldeed** [comment]
Yeah, if there's an _id field, then the schema needs to define it. This is slightly different if collection2 is handling your validation because currently it ignores the `_id` for you when validating, but I will probably ditch that in an upcoming version of collection2 and always require `_id` to be in the schema.

**Comment by sean-stanley** [comment]
Maybe a better implementation is to do what Mongoose does and automatically add a default _id field to the schema for you that a user can overwrite in their own schema if they want different options like a numerical _id or a proper ObjectId.

**Comment by aldeed** [comment]
Good idea

**Comment by cyrus-za** [comment]
any update on this? This is currently a blocker as we need to use ObjectId with the data coming from other systems outside of meteor
