### ISSUE TITLE
SimpleSchema.RegEx.ZipCode not working

### ISSUE THREAD

**Issue by ffxsam** [aldeed/meteor-simple-schema#390]
When I try to use this as such:

```
Info.attachSchema(new SimpleSchema({
  zipCode: {
    type: String,
    regEx: SimpleSchema.RegEx.ZipCode,
    label: 'ZIP Code'
  },
  ...
```

I get this:

```
Your app is crashing. Here's the latest log.


/Users/samh/.meteor/packages/meteor-tool/.1.1.3.1hk6jli++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Invalid definition for zipCode field.
    at packages/aldeed:simple-schema/simple-schema.js:62:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at [object Object].SimpleSchema (packages/aldeed:simple-schema/simple-schema.js:59:1)
    at app/lib/collections/leads.js:3:20
    at app/lib/collections/leads.js:49:3
    at /Volumes/Sites/trial/.meteor/local/build/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/samh/.meteor/packages/meteor-tool/.1.1.3.1hk6jli++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Volumes/Sites/trial/.meteor/local/build/programs/server/boot.js:117:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by bgrayburn** [comment]
+1 when I go to the console, type `SimpleSchema.RegEx.` and tab for autocomplete, ZipCode is not listed as should be expected based on the README

**Comment by awei01** [comment]
ran into same issue when using SimpleSchema.RegEx from w/in a package. I tried console.log(SimpleSchema.RegEx) and it came back undefined.

**Comment by aldeed** [comment]
Probably a version issue. Make sure you are using `1.3.0` or higher. You may have to explicitly list `aldeed:simple-schema@1.3.0` in your package file or it will just use whatever minimum version some other package like collection2 depends on.

**Comment by lonniev** [comment]
How do we assure that Collection2 is using the latest npm version of SimpleSchema - and that that SimpleSchema has the RegEx property/class mixed in?

Meanwhile, I get undefined crashes trying to use SimpleSchema.RegEx references.
