### ISSUE TITLE
Schema with multiple unique key

### ISSUE THREAD

**Issue by urvishsheth** [aldeed/meteor-simple-schema#391]
Hello sir,

I want to define multiple unique key in my schema, It is not working, i mean it is not working as a combine key. 

ex.
fromZone:{
        type: string,
        label: "From Zone",
        unique: true,
        index: true
    },
    toZone:{
        type: string,     
        label: "To Zone",
        unique: true,
        index: true
}

Thanks,
Urvish

**Comment by aldeed** [comment]
You can't do dual key unique through the schema. Use the normal `_ensureIndex()`

**Comment by thearabbit** [comment]
I tried to use `_ensureIndex()`, It is OK.
how to get the error message to `AutoForm`?
