### ISSUE TITLE
Comparing two field value in a autoform with schema validation

### ISSUE THREAD

**Issue by YouSour** [aldeed/meteor-simple-schema#392]
hi , i don't know how to comparing two field value in a autoform with schema validation .
example: i have schema like below i want to validated paidAmount can't bigger than dueAmount .
Dental.Schema.Payment = new SimpleSchema({
    dueAmount: {
        type: Number,
        decimal: true,
        label: 'Due Amount'
    },
    paidAmount: {
        type: Number,
        decimal: true,
        min: 1,
        label: 'Paid Amount'
    }
});

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.
