### ISSUE TITLE
Required validation not working without regex

### ISSUE THREAD

**Issue by flt123** [aldeed/meteor-simple-schema#396]
Folks,

Something strange is going on and I hope someone can help. I have a schema that does not trigger validation except I have a regex on it. I have the schema below:

    userFirstName: {
    type: String,
    label: 'Firstname',
    regEx: /^[a-zA-Z-]{2,25}$/
    },

    userLastName: {
    type: String,
    label: 'Lastname',
    regEx: /^[a-zA-Z]{2,25}$/
    },

    userAddressOne: {
    type: String,
    label: 'Address',
    regEx: /^[a-zA-Z0-9 _-]{2,25}$/
    }

If I remove the regEx, and leave the fields empty, the required validation is not triggered. Does anyone know what is going on?

**Comment by flt123** [comment]
any taker?

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.
