### ISSUE TITLE
Definition Objects Array Enhancement

### ISSUE THREAD

**Issue by dcarrask** [aldeed/meteor-simple-schema#398]
Hi there,

I'm using your package and I would like to suggest an idea. Could it be possible to declare one array object instead of:

```javascript
questions:{
	type:[Object],
	minCount: 1,
	maxCount: 4,
},
'questions.$.a':{
	type: String,
},
'questions.$.b':{
	type: String,
},
'questions.$.c':{
	type: String,
},
'questions.$.d':{
	type: String,
},
'questions.$.answer':{
	type: String,
},
```

... declare nested syntax like this example:

```javascript
questions:{

	type:[Object],
	minCount: 1,
	maxCount: 4,

	elem:{
		'a':{
			type: String,		
		},
		'b':{
			type: String,		
		},
		'c':{
			type: String,		
		},
		'd':{
			type: String,		
		},
		'answer':{
			type: String,		
		},
	}

}
```

'elem' can be anything... It's just a point of view I find it more obvious to understand like this.

What do you think?

**Comment by aldeed** [comment]
I prefer the flat structure. If you don't need any advanced SS features, you can write a JSONSchema, which is nested, and then use https://atmospherejs.com/bshamblen/json-simple-schema to convert it to a SS.
