### ISSUE TITLE
wait for custom function that adds invalid keys

### ISSUE THREAD

**Issue by niklasp** [aldeed/meteor-simple-schema#400]
I have a schma with a field that uses a custom function (that calls a server method) and may add InvalidKeys to the Schema context.

```
		treenumber: {
			type: Number,
			custom: function () {
				if (Meteor.isClient && this.isSet) {
				  	Meteor.call("isBaumNummerUniqueForAccount", this.value, function (error, result) {
					    if (!result) {
					      BaumInfos.simpleSchema().namedContext("importContext").addInvalidKeys([{name: "Baumnummer", type: "notUnique"}]);
					   }
				    });
				}	
			}		
		},
```
Then in the ui I want to display if the validation succeeded. However the invalid keys are added asynchronusly and 
    isValid = BaumInfos.simpleSchema().namedContext().validate(result.baumInfo);
does not wait for the response. How can I make sure that validation waits for the server results?

**Comment by aldeed** [comment]
It's best to do your method call somewhere else, before you even validate on the client, or just do the full validation on the server and send back the invalid keys.

**Comment by thearabbit** [comment]
Could you example?
I have problem with `onSuccess Hook`, it run before `custom validate`
