### ISSUE TITLE
Checking against schema in methods

### ISSUE THREAD

**Issue by mazing** [aldeed/meteor-simple-schema#402]
If I have a schema

    Schema.Post = new SimpleSchema({
      text: {
        type: String,
      },
      isApproved: {
        type: Boolean,
        defaultValue: false,
        autoform: {
          omit: true
        },
      },

the `isApproved` should be set as false by default and it should be omitted from the forms.

But if I use a method to create posts like this:

    createPost: function(postAttr) {
      check(postAttr, Posts.simpleSchema());
      Posts.insert(postAttr);
    },

I get an match error with message: "Match error: Is approved is required".

I do understand that if I haven't set `optional: true`, the field has to be present in `postAttr` for the object to be valid according to the schema, but I don't think it makes sense to set `optional: true` because it is not optional but just set automatically "behind stage".

Isn't this an "error" or can I avoid this behaviour somehow?

**Comment by sean-stanley** [comment]
You can avoid it by running this code:

```
createPost: function(postAttr) {
  Shema.Post.clean(postAttr);
  check(postAttr, Posts.simpleSchema());
  Posts.insert(postAttr);
},
```

Running `clean` on an object will populate the defaultValues, autorun, custom validation, etc. so it will pass your check function afterwards.
