### ISSUE TITLE
Error: When the modifier option is true, validation object must have at least one operator

### ISSUE THREAD

**Issue by trusktr** [aldeed/meteor-simple-schema#404]
What does that mean?

**Comment by diegodesouza** [comment]
I am getting the same error, would like to find out what's causing it.

**Comment by trusktr** [comment]
@diegodesouza I decided to just use Meteor `check` instead of this. I find the syntax for describing the types to be nicer, and it works as expected! For example:

```js
Cards = new Mongo.Collection("cards");

// use this function to validate Cards before insertion.
Cards.validate = function(document) {
  check(_.omit(document, '_id'), {
    // _id of a CardType.
    typeId: MeteorIDString,

    // _id of a Space this card belongs to.
    spaceId: MeteorIDString,

    // _id of a wall this card belongs to.
    wallId: MeteorIDString,

    // _id of a board this card belongs to, null if none.
    boardId: Match.OneOf(MeteorIDString, null),

    // a user _id
    createdBy: MeteorIDString,

    createdOn: Date,
  })
}

Cards.before.insert(function(userId, doc) {
  Cards.validate(doc)
})
```

**Comment by trusktr** [comment]
`Items.before.insert` is possible with ]collection-hooks](https://atmospherejs.com/matb33/collection-hooks).

**Comment by vonwao** [comment]
I'm getting this same error message when I try to update an document. 

I created a collection, but I didn't attach a schema to it.   

So why is simple-schema trying to validate it?

**Comment by aldeed** [comment]
Usually this happens because after your update modifier is cleaned, everything has been removed and there is nothing left. So it ends up being the equivalent of doing `update(id, {})`.
