### ISSUE TITLE
How to validate Strings in an array?

### ISSUE THREAD

**Issue by trusktr** [aldeed/meteor-simple-schema#408]
In the docs, I see you can do things like `updatesHistory.$.date` to target items inside objects of arrays, but what if we have an array of Strings?

For example, is this right?

```js
  children: { type: [String] },
    'children.$': { type: String, regEx: Id }
```

**Comment by aldeed** [comment]
Yes, but it's better to do `type: Array` for the `children` one since `children.$` already specifies the item type.
