### ISSUE TITLE
regEx validation should be done only if optional field is present

### ISSUE THREAD

**Issue by SachaG** [aldeed/meteor-simple-schema#409]
I'm using `check(post, Posts.simpleSchema())` in an Autoform method to check my arguments, but it throws an error when the optional `post.userId` field – which has the `SimpleSchema.RegEx.Id` regEx validation – is missing. 

On the other hand, if I remove that regEx validation the check passes even if the field is missing. 

Is this the expected behavior? Does that mean I shouldn't use `check` with optional fields and regEx validation?

**Comment by CyberClaw** [comment]
I'm having similar issues (not using check, but validateOne) also with regex & optional. The documentation doesn't clarify if manual validation ignores optional (I believe it does). Another example is having a type:String, min:5, optional:true, And when manual validating it will also return a minchars error (which might make sense, as the str.length < min, but then again, it's optional so it'd make sense that the empty string was ignored as an undefined value)

The way I worked around this was turning empty strings into undefined before validating. Takes care of both those problems.

**Comment by aldeed** [comment]
Reading through this again, there is no issue here. Empty strings are values so they are validated. To avoid the errors you can call `clean` first with `removeEmptyValues: true`
