### ISSUE TITLE
GeoJSON to SimpleSchema

### ISSUE THREAD

**Issue by djoice** [aldeed/meteor-simple-schema#410]
Hi! How write multi array (3 levels) to simple scheme?

My scheme:

Schemas.GeoLoc = new SimpleSchema({

'center' : {
    	type : Object,
    },

    'geometry' : {
    	type : Object,
    },
    'center.coordinates' : {
		type : Array,
		minCount : 2,
		maxCount : 2,
	},
    
	'center.coordinates.$' : {
		type : Number,
		decimal: true,
	},

	'center.type' : {
		type : String,
		allowedValues: ["Point"],
		defaultValue: "Point",
	},

	'geometry.coordinates' : {
		type : Array,
	},
    
	'geometry.coordinates.$' : {
		type : Array,
		minCount : 1,
	},
	
	'geometry.coordinates.$.$' : {
		type : Array,
		minCount : 2,
		maxCount : 2,
	},

	'geometry.coordinates.$.$.$' : {
		type : Number,
		decimal: true,
	},

	'geometry.type' : {
		type : String,
		allowedValues: ["Point","Polygon","LineString","MultiPolygon"],
		defaultValue:"Polygon",
	},

});

But debug say:
SimpleSchema.clean: filtered out value that would have affected key "loc.geometry.coordinates.$.0.$", which is not allowed by the schema
aldeed_...f8566e4 (строка 2581)

SimpleSchema.clean: filtered out value that would have affected key "loc.geometry.coordinates.$.1.$", which is not allowed by the schema
aldeed_...f8566e4 (строка 2581)

....

My data:

{

            center : {
              type : "Point",
              coordinates : [30.52306, 50.44983],
            },
            geometry : {
              type : "Polygon",
              coordinates : [[[30.52232,50.44996],[30.52215,50.45005],[30.52221,50.45009],[30.52203,50.45019],[30.52209,50.45024],[30.52207,50.45025],[30.52212,50.45028],[30.52199,50.45036],[30.52214,50.45045],[30.52301,50.44996],[30.52308,50.45001],[30.5233,50.4499],[30.52325,50.44986],[30.52328,50.44984],[30.52281,50.44946],[30.52263,50.4493],[30.52241,50.44937],[30.52261,50.44955],[30.52289,50.44979],[30.52273,50.44988],[30.52264,50.44981],[30.52242,50.44994],[30.52201,50.44964],[30.52193,50.44969],[30.52232,50.44996]]],
            }

        }

Ho it fix? :)

**Comment by cwaring** [comment]
I'm interested if you found a way to do this @djoice?

**Comment by Architecty** [comment]
Following up that I'm finding the same issue. GeoJSON needs a three level deep Number array. Attempting to list it as `[[[Number]]]` doesn't work -- Meteor crashes with the following message:

    Error: Invalid definition for geoJSON.$.geometry.coordinates.$.$.$ field.
     at packages/aldeed_simple-schema/simple-schema.js:457:1
     at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
     at [object Object].SimpleSchema (packages/aldeed_simple-schema/simple-schema.js:454:1)
     at collections/general.js:123:17
     at /home/daniel/analyze/.meteor/local/build/programs/server/app/collections/general.js:152:4
     at /home/daniel/analyze/.meteor/local/build/programs/server/boot.js:242:10
     at Array.forEach (native)
     at Function._.each._.forEach (/home/daniel/.meteor/packages/meteor-tool/.1.1.10.ivfvg7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
     at /home/daniel/analyze/.meteor/local/build/programs/server/boot.js:137:5

**Comment by ilfrich** [comment]
Looks like the following schema will do for the `geometry` field:

```
GeometrySchema = new SimpleSchema({
    'coordinates': {
        type: Array
    },
    'coordinates.$': {
        type: Array
    },
    'coordinates.$.$': {
        type: [Number]
    },
    type: {
        type: String,
        optional: true
    }
});
```

**Comment by djoice** [comment]
Thanks for your help, now I use blackbox: true
Be careful when using the scheme and geo indexes in mongodb :)

**Comment by ilfrich** [comment]
Played around a little with this and couldn't get it to work to only declare `coordinates` as blackbox. The declaration needs to happen on the `geometry` level:

```
...
'properties': {
  type: FeaturePropertySchema // needs to be declared as labels: { type: [String] }
},
'type': {
  type: String
}
'geometry' : {
    type : Object,
    blackbox: true
}
...
```

**Comment by krishaamer** [comment]
Hello, any solution to this yet?

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and should fix this bug.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
