### ISSUE TITLE
Special characters such as ö, é, æ, ø, å, etc.

### ISSUE THREAD

**Issue by mazing** [aldeed/meteor-simple-schema#413]
The user schema provided at https://github.com/aldeed/meteor-collection2#attach-a-schema-to-meteorusers requires the user to use string characters in names, but it doesn't accept special characters such as ö, ø, æ, å, é, etc. which is critical behaviour when dealing with personal names.

How can I make it accept such characters?

**Comment by aldeed** [comment]
Reg exp was removed from this awhile ago
