### ISSUE TITLE
Bug with email regex

### ISSUE THREAD

**Issue by OminStyle** [aldeed/meteor-simple-schema#414]
```SimpleSchema.RegEx.Email``` returns false for abc-@gmail.com. But regex from http://stackoverflow.com/questions/46155/validate-email-address-in-javascript returns true.
```
function validateEmail(email) {
    var re = /^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i;
    return re.test(email);
}
```

**Comment by aldeed** [comment]
I've chosen to stick with the one recommended here: http://www.w3.org/TR/html5/forms.html#valid-e-mail-address

So unless they need to change that one, I will not fix this, but you can always use whatever expression you want.
