### ISSUE TITLE
Use decorators/metadata to create SimpleSchema

### ISSUE THREAD

**Issue by brettle** [aldeed/meteor-simple-schema#416]
[Typescript 1.5 adds support for decorators](http://blogs.msdn.com/b/typescript/archive/2015/07/20/announcing-typescript-1-5.aspx) based on the [ES7 decorators proposal](https://github.com/wycats/javascript-decorators), and it [automatically adds type metadata](https://github.com/Microsoft/TypeScript/pull/2589) to classes and properties. It would be nice if the resulting metadata could be used to create SimpleSchema objects. Ideally, I could write something like the following in Typescript:

```typescript
class Person {
  @label('First and last name')
  fullName: string;

  @label('Date of birth')
  dob: Date;

  @label('Number of children')
  @min(0)
  numChildren: number;
}

schema = new SimpleSchema(Person);

```

And the resulting schema would be equivalent to:

```javascript
schema = new SimpleSchema({
  fullName: {
    type: String,
    label: 'First and last name'
  },
  dob: {
    type: Date,
    label: 'Date of birth'
  },
  numChildren: {
    type: Number,
    label: "Number of children",
    min: 0
  }
});
```

Is anyone looking into this? Should it be implemented as a separate package, or would a pull request which added support be considered (assuming it doesn't introduce any new dependencies).

The implementation I'm imagining would detect the existence of the [Reflect.metadata API](https://www.npmjs.com/package/reflect-metadata) and, if it exists, use it to find the metadata and build the schema.

Thoughts?

**Comment by ncubica** [comment]
have you done any kind of progress in this subject? I'm really interest in this kind of solution. Maybe we should start coding this.

**Comment by brettle** [comment]
I haven't done anything yet. If/when I do I'll post here. If you do (or anyone else does), please do the same.

**Comment by aldeed** [comment]
It should be a separate package, but if changes are needed in core to support plugging in the new package, let me know.
