### ISSUE TITLE
Collection 2 "Email Address is required"

### ISSUE THREAD

**Issue by gotandon** [aldeed/meteor-simple-schema#417]
I'm getting the following error:

Error: EmailAddress is required
W20150723-19:24:14.947(5.5)? (STDERR)     at getErrorObject (packages/aldeed:collection2/collection2.js:363:1)
W20150723-19:24:14.948(5.5)? (STDERR)     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:346:1)
W20150723-19:24:14.948(5.5)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2/..............

My Schema:

Organizations = new Mongo.Collection('organizations');

var Schemas = {};
//
Schemas.Organizations = new SimpleSchema({
    name: {
        type: String,
        label: "Organization Name",
        regEx: /^[a-z0-9A-z .]{3,30}$/,
        max: 100
    },
    email: {
        type: String,
        label: "Email Address",
        regEx: SimpleSchema.RegEx.Email
   

    },
    website: {
        type: String,
        regEx: SimpleSchema.RegEx.Url,
        optional: true,
        label: "Website"
    },
    category:{
        type: String,
        allowedValues: ['Health', 'Education', 'Sports', 'Finance'],
        label: "Category"
    },
    regions: {
        type: [String],
        allowedValues: ['India', 'North America', 'South America', 'Europe', 'Asia', 'Australia'],
        minCount: 1,
        label: "Regions"
    }

});

Organizations.attachSchema(Schemas.Organizations);

//

**Comment by flt123** [comment]
add optional: true,

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.
