### ISSUE TITLE
Question: document references

### ISSUE THREAD

**Issue by TWKDreamState** [aldeed/meteor-simple-schema#421]
Hi,

I am very new to Meteor having come from another MEAN stack. Previously I have used mongoose.

My intent is to have two collections; one contains a number of questions and the other contains a number of quizes. The quizes will reference the questions. Some questions may appear in several different quizes.

In mongoose schema I used the Schema.Types.ObjectId in order to store the reference to the questions document. I could then use 'populate' when I retrieved the data and the ObjectId was replaced with the questions documents.

What would be the method I need to use with simple-schema in order to achieve this (and publish the results to the client)? Or is there a different method I should be using?

Many thanks.

**Comment by aldeed** [comment]
Default Meteor IDs are strings so you would use `String` type, store the ID, publish relations using `publish-composite` package, and do "joins" using `collection-helpers` package. Or there are packages like Astronomy and PeerDB that take other approaches.
