### ISSUE TITLE
Update fails on type Date when using MongoDB $currentDate modifier

### ISSUE THREAD

**Issue by rurri** [aldeed/meteor-simple-schema#422]
Schema looks like:

`modified: { type: Date, optional: true}`

mongodb update looks like:

`{$currentDate: {modified: true}, $set: {......}}`

Simple Schema reports: "Modified must be a Date [400]"

**Comment by aldeed** [comment]
To help me catch up, I'm closing some old issues. If you still need help, post a comment asking to reopen.
