### ISSUE TITLE
Server/client restrictions

### ISSUE THREAD

**Issue by CaptainN** [aldeed/meteor-simple-schema#423]
It'd be great if there was a simple way to specify where a particular property was allowed to be updated regarding server or client. For example, I'd like to create an `isMember` property, and have it locked on the client, so that no one on that side could modify the Boolean value. Only privileged server methods would be able to set the value.

Something like:
```JavaScript
allowReadFrom: ['server', 'client'],
allowUpdateFrom: 'server',
allowInsertFrom: ['server'],
```

**Comment by streamnsight** [comment]
I was also wondering if there is a way to have only a 'subset' of the full schema on the client side. 
Is it actually possible to 'attach' a (different) schema on the server and client side?

**Comment by CaptainN** [comment]
That's an interesting idea. You could apply one inside an `isServer` if block, and the other in an `isClient` if block (or appropriate folders). I wonder what would happen if we did that now? In the current version, is it validated twice (with Collection2) when you update or insert into a collection on the client? Once on the client, and then once on the server? I'm not sure.

**Comment by aldeed** [comment]
This has been discussed before but does not belong in core. Schema options are extensible so someone could create a separate package that handles this.
