### ISSUE TITLE
Bug with accounts-base

### ISSUE THREAD

**Issue by gwendall** [aldeed/meteor-simple-schema#424]
I have recently been seeing this error when trying to login. Any idea why?

``` sh
Exception while invoking method 'login' Error: When the modifier option is true, validation object must have at least one operator
  at checkModifier (packages/aldeed:simple-schema/simple-schema-validation.js:271:1)
  at doValidation1 (packages/aldeed:simple-schema/simple-schema-validation.js:321:1)
  at doValidation (packages/aldeed:simple-schema/simple-schema-context.js:9:1)
  at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate] (packages/aldeed:simple-schema/simple-schema-context.js:44:1)
  at [object Object].doValidate (packages/aldeed:collection2/collection2.js:317:1)
  at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:154:1)
  at Object.Accounts._insertHashedLoginToken (packages/accounts-base/accounts_server.js:597:1)
  at Object.Accounts._insertLoginToken (packages/accounts-base/accounts_server.js:608:1)
  at loginUser (packages/accounts-base/accounts_server.js:189:1)
  at attemptLogin (packages/accounts-base/accounts_server.js:255:1)
```

**Comment by Rongky** [comment]
same here... 

this only happens when I add a schema for Meteor.users collection...

**Comment by PeterBloom** [comment]
+1 Also having this problem.

**Comment by oskareke** [comment]
+1. Did anyone figure this one out?

**Comment by gwendall** [comment]
@oskareke As @Rongky said, it has to deal with a schema you defined on Meteor.users.

**Comment by oskareke** [comment]
Sorry for being unclear, I meant services as part of the schema defined and attached to Meteor.users. The code below gave me the error, switching to blackbox: true resolved it.

Schema.User = new SimpleSchema({
services: {
            type: Object,
            optional: true,
            blackbox: false
        }
...
});
Meteor.users.attachSchema(Schema.User);

**Comment by gwendall** [comment]
Yes that's the idea of `blackbox`, allowing you to define an object with no particular structure within it. You need it in `services` since the different providers you can sign up with all expose slightly different structures to their `services` objects (ie. `services.facebook` will not necessarily have the same structure as `services.twitter`).

**Comment by mahmoudkm** [comment]
I have the same issue, and even setting services blackbox to true didn't resolve the issue, any thoughts? 
below is my schema code

          this.Schemas = {};
          Schemas.UserProfile = new SimpleSchema({
            name: {
              type: String,
              optional: true
            }
          });

          Schemas.User = new SimpleSchema({
            username: {
              type: String,
              regEx: /^[a-z0-9A-Z_]{3,15}$/,
              optional: true
            },
            emails: {
              type: [Object],
              optional: true
            },
            "emails.$.address": {
              type: String,
              regEx: SimpleSchema.RegEx.Email
            },
            "emails.$.verified": {
              type: Boolean
            },
            services: {
                  type: Object,
                  optional: true,
                  blackbox: true
            },
            password: {
                  type: String,
                  blackbox: true
            },
            createdAt: {
              type: Date
            },
            profile: {
              type: Schemas.UserProfile,
              optional: true
            },
            group: {
              type: String,    
              optional: true
            },
            roles: {
              type: [String],
              blackbox: true,
              optional: true
            }
          });

          Meteor.users.attachSchema(Schemas.User);

**Comment by aldeed** [comment]
The reason could be different in different cases. This happens when schema cleaning ends up removing everything so it's like doing `update(id, {})`. So you need to debug what the `update` call is, then try running `Schemas.User.clean(modifier)` and verify that it's removing everything. Then compare `modifier` to your schema carefully and figure out why it's filtering out everything from that modifier. Then fix your schema.

**Comment by desaiuditd** [comment]
@aldeed Can you elaborate on your last comment for how to debug this issue ?

For example,
- where would I be debugging the `update` call ?
- where would I be running `Schema.User.clean(modifier)`?  What would be the value for `modifier` ?
- What would I be comparing `modifier` with ?

A sample code would be appreciated. Thanks.
