### ISSUE TITLE
Could I use "inputmask" with number (decimal) field of Simple Schema? 

### ISSUE THREAD

**Issue by thearabbit** [aldeed/meteor-simple-schema#425]
I would like to use `inputmast` with `number (decimal)` field fo Simple Schema.
```js
// Simple Schema
amount: {
    type: Number,
    label: "Amount",
    decimal: true
  },

// Template
Config inputmask (...000,000.00)
```
But have problem with type `Number`.
Please help me.

**Comment by aldeed** [comment]
The output is probably string so you will have to do `parseFloat` before saving it.
