### ISSUE TITLE
extracting schema bug

### ISSUE THREAD

**Issue by partus** [aldeed/meteor-simple-schema#427]
var myschema = new SimpleSchema({name: {type: [String]}})
undefined
myschema.pick(["name"])
simple-schema.js:465 Uncaught Error: Invalid definition for name.$ field.

**Comment by partus** [comment]
simplest hack for my needs is 

function pickSchema(schema, key){
  var allKeys = [key];
  _.each(schema.schema(), function(v,k){
    if(k.indexOf(key+'.')==0){
      allKeys.push(k)
    }
  })
  return schema.pick(allKeys)
}

**Comment by aldeed** [comment]
Duplicate of #284
