### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by PArch** [aldeed/meteor-simple-schema#432]
Hi,

I work with Meteor + Atom for deskop app.

I have a simple form and when I run in browser with localhost:3000 it works.

But when i run  deskop and click on my submit form ...

Uncaught TypeError: undefined is not a function simple-schema.js:742
mDoc.forEachNode.endPointsOnly simple-schema.js:742
(anonymous function) mongo-object.js:209_.each._.forEach underscore.js:113
self.forEachNode mongo-object.js:205
SimpleSchema.clean simple-schema.js:716
getFormValues autoform-inputs.js:147autoFormSubmitHandler autoform-events.js:276
(anonymous function) template.js:463
Template._withTemplateInstanceFunc template.js:437
(anonymous function) template.js:462
(anonymous function) view.js:869
Blaze._withCurrentView view.js:523
(anonymous function) view.js:868
(anonymous function) events.js:47
jQuery.event.dispatch jquery.js:4665

Any idea ?

**Comment by aldeed** [comment]
It might have something to do with the stringjs library not getting loaded within your app

**Comment by aldeed** [comment]
Stringjs dependency is removed in next version
