### ISSUE TITLE
autoValue on failed update

### ISSUE THREAD

**Issue by justindra** [aldeed/meteor-simple-schema#435]
Hi,

So just wondering how and when the autoValue is called. As I had an update function which will not find a match, (the selector doesn't exist) and for some reason, autoValue came up with an error as the field I was using to reference in there does not exist.

On a side note, how does the whole process go for upserts? Does it try and update first, therefore running through everything, and then run another insert? What values in the fields gets passed through to the insert?

Cheers!

**Comment by aldeed** [comment]
It is done as part of calling `.clean()`, which collection2 does on the server only for inserts, updates, and upserts. For upserts, it just runs your modifier through the function before calling `upsert()`. Nothing fancy.
