### ISSUE TITLE
Support for DbRefs?

### ISSUE THREAD

**Issue by calvinfroedge** [aldeed/meteor-simple-schema#436]
Is something like this currently possible with SimpleSchema?

```
{
  "_id" : ObjectId("5126bbf64aed4daf9e2ab771"),
  // .. application fields
  "creator" : {
                  "$ref" : "creators",
                  "$id" : ObjectId("5126bc054aed4daf9e2ab772"),
                  "$db" : "users"
               }
}
```

http://docs.mongodb.org/master/reference/database-references/#dbref-explanation

**Comment by aldeed** [comment]
No, this may be supported through collection2 or a separate package at some point, but it would not be a simple schema thing. SS is not aware of the database at all, just the objects it's validating.
