### ISSUE TITLE
Custom validation messages ignores label value passed from quickField

### ISSUE THREAD

**Issue by Maxhodges** [aldeed/meteor-simple-schema#438]
I have a custom validation message like this

    SimpleSchema.messages({
      required: "[label] " + mf('validation_message_is_required', 'is required'),
    });

and I'm passing a label value from quickField using a helper:

    {{> afQuickField name='fullName' label=mfFullName template="bootstrap3" }}

      'mfFullName': function() {
        return mf('shipping_address_full_name', 'Full Name');
      },

But it seems like the `[label]` value in the custom validation message is coming from the schema, not from my overridden value. When I create a Japanese translation in messageFormat, the is required field still says "Full Name"; not the Japanese text.

Is this perhaps a subtle bug? 

As a workaround it seems I can just define the mf function inside the schema:

      fullName: {
        type: String,
        label: mf('shipping_address_full_name', 'Full Name'),
        max: 80,
      },

Cheers!
Max

**Comment by aldeed** [comment]
I can see where this is confusing, but `label=mfFullName` is an AutoForm thing, allowing you to provide specific label _element_ text, whereas the `label` in the schema is a SimpleSchema thing, used to provide a readable name for the error messages. (AutoForm also borrows the SS label as a default, adding to the confusion.)

So there is no bug here.
