### ISSUE TITLE
Provide a simple way to check() with object cleaning first

### ISSUE THREAD

**Issue by AlexFrazer** [aldeed/meteor-simple-schema#449]
I have a method that looks roughly as follows.

```
Meteor.methods({
  'Players.addToGame': function (playerDoc, gameId) {
    check(playerDoc, Players.simpleSchema());
    // do some other stuff.
  }
});
```

This does not work as intended. I checked, and it looks like the autoValues never fire on the check. This, however, does work:

```
check(Players.simpleSchema().clean(playerDoc), Players.simpleSchema());
```

But that seems a bit redundant. Can the check clean it automatically?

**Comment by aldeed** [comment]
I wouldn't want to assume that everyone wants it cleaned. But I will be making some different checking functions in an upcoming release that can have options to do the cleaning.

**Comment by AlexFrazer** [comment]
Makes sense, I have tons of autovalues on all of my schemas.

**Comment by aldeed** [comment]
Moved to https://github.com/aldeed/node-simple-schema/issues/10
