### ISSUE TITLE
Default values in optional subschemas

### ISSUE THREAD

**Issue by ramijarrar** [aldeed/meteor-simple-schema#455]
If I attach a subschema with default values to an optional field and in my document leave the optional field unspecified, simple schema will still generate the nested default values in the subschema. This will often produce errors when the subschemas contains other required fields.

For example:

```js
Brand = new SimpleSchema({
    name: {
        type: String
    },
    logo: {
        type: String,
        defaultValue: "http://example.com/logo.jpg"
    }
});

Product = new SimpleSchema({
    name: {
        type: String
    }
    brand: {
        type: Brand,
        optional: true
    }
})
```

**Comment by aldeed** [comment]
That is the expected behavior of `defaultValue`. If you want something different, you can use `autoValue`

**Comment by kellertobias** [comment]
is this still the expected behaviour? I have a case where I depend on creating the object if the subschema has `defaultValue`s but when switching to the new version of simple schema it does not work again
