### ISSUE TITLE
Validate a complete array

### ISSUE THREAD

**Issue by johngonzalez** [aldeed/meteor-simple-schema#457]
I have this schema: 
``` javascript
MySchema = new SimpleSchema({
  myarray: {
    type: [Boolean]
  }
});
```
I want to validate only one true Boolean value. For example:
``` javascript
Match.test([true, false, true, false], MySchema)  // return false
Match.test([false, false, false, false], MySchema)  // return false
Match.test([false, true, false, false], MySchema) // return true
```
How I should make it using custom validation function?

**Comment by sebakerckhof** [comment]
You'll probably have to make a custom validation function https://github.com/aldeed/meteor-simple-schema#custom-validation
