### ISSUE TITLE
Reverse integer/decimal

### ISSUE THREAD

**Issue by aldeed** [aldeed/meteor-simple-schema#466]
It's confusing that `decimal: true` is required for `Number` type to allow floats. This would be a big thing to change this for everyone using existing way, but we could have an opt in (or opt out, need to decide) so that we can transition to allowing floats by default and limiting to integers only when `integer: true`.

**Comment by jedwards1211** [comment]
Cool!  Do you have any idea what you'd want the code for opting in to look like?

**Comment by idmontie** [comment]
Not sure what the best solution is, but it is a bit odd that `check` says that decimals are valid numbers:

```javascript
check( 14.2414, Number );
```

But Simple Schema needs an extra setting for it to accept decimal numbers.

**Comment by Hongbo-Miao** [comment]
I met same issue until I found this. It is indeed confusing.

**Comment by aldeed** [comment]
Thanks for your patience. SimpleSchema 2.0.0-rc.1 is now released and includes changes that resolve this issue.

There are a number of breaking changes when updating to 2.0, so be sure to check out [the change log](https://github.com/aldeed/meteor-simple-schema/blob/devel/CHANGELOG.md#200). If you use aldeed:collection2, you will need to use 2.10.0 or higher of that package in order to use SimpleSchema 2.0. If you use autoform, it is not yet updated to work with SimpleSchema 2.0, but hopefully soon.

SimpleSchema is now an isomorphic NPM package, so you can check out the updated readme and file issues over at the [other repo](https://github.com/aldeed/node-simple-schema). The Meteor wrapper package will exist for now but eventually I will probably deprecate support for it.

This is still a beta/RC and I do expect people will find issues, so use with caution. Production use is not yet recommended. That said, there are more and better unit tests than ever before, and the codebase should be much easier for others to read through and debug quickly.
