### ISSUE TITLE
Validate Key Value Pair

### ISSUE THREAD

**Issue by merlinpatt** [aldeed/meteor-simple-schema#468]
I would like to have a field point to an object with keys that are IDs of one Collection, which point an array of related information, like so

```field: {
  id1: [someInfo],
  id2: [someOtherInfo],
  ...
}```

How can I use Simple Schema Validation to ensure that the key is an ID?

**Comment by merlinpatt** [comment]
I am attempting to use a custom function to validate this but I end up getting the error `field.id1 is not allowed by the schema` and the error type `keyNotInSchema`. Thoughts?

**Comment by aldeed** [comment]
You would have to do `blackbox: true` on the `field` schema plus custom validation for it that validates every key of the object.
