### ISSUE TITLE
Referencing documents

### ISSUE THREAD

**Issue by silently** [aldeed/meteor-simple-schema#47]
Hello, this is more a question than an issue:
what "type" should be set when we want to reference another doc within a Schema?

I've tried:

```
schema: {
  userId: {
    type: Meteor.Collection.ObjectID
  }
}
```

But got a failed validation.

Thanks!

**Comment by robinnewhouse** [comment]
For anyone else who lands here it looks like `SimpleSchema.RegEx.Id` is the way to acomplish this now with stricter validation than just `String`

**Comment by zhe1ka** [comment]
if you want to use `Mongo.Collection.ObjectID` then you always need to specify `blackbox: true`

`    _id: {
        type: Mongo.Collection.ObjectID,
        blackbox: true
    },`
