### ISSUE TITLE
Is it possible to override schema rules in a custom validator?

### ISSUE THREAD

**Issue by eoliphan** [aldeed/meteor-simple-schema#473]
Hi, I have some rather complex calculations that need to be performed to figure out the min/max for a schema field.  To accomplish this I have to pass some extra info to the custom schema rule (autoform magic on the client, the extendedCustomContext on the server), this part is working.  However, the say max may change based on the result of what goes on in the 'custom' rule function.  I've tried  something like the following:

```
if (this.value > x.annualSalesLimit) {
                    this.definition.max = x.annualSalesLimit;
                    return "maxNumber";
                }
````

However, when the validation fails based on the return of 'maxNumber' the [max] value in the error message is whatever it was originally set in the schema.  I can't seem to use a function as 'max' either as I don't get all the context info I need to perform the calculation when it's evaluated.  On the server it has no access to the extendedCustomContext.  On the client, it blows up when using the AutoForm functions (getCurrentDataPlusExtrasForForm",etc) as I think it's causing some sort of circular dependency (maybe autoform is calling max to initialize the form, but then max is calling autoform to get info about the form that's being created)

**Comment by aldeed** [comment]
I will try to support this in an upcoming release by allowing more complex ways of adding invalid keys / messages within a custom function. There is a separate issue for that.
