### ISSUE TITLE
Inserting multiple documents

### ISSUE THREAD

**Issue by smirnovigor** [aldeed/meteor-simple-schema#481]
while inserting array of documents ``Collection.insert([{key1:"val1"},{key2:"val2"}])``, I got validation error. when I turn of validation, with validation option, the documents stored with unexpected format:

```
{
_id: "document id",
  0: {key1:"val1"}
}
```

My question is does simple schema support multiple documents insert?

**Comment by duranmla** [comment]
I think it doesn't same is happening to me, so looking forward to this reply, in order to work into this problem or to know how is the right approach (I don't see anything about it into the docs).

**Comment by aldeed** [comment]
The answer is no, that is only recently supported by Meteor and not yet added to collection2. But this is a collection2 thing, so I'm closing.
