### ISSUE TITLE
you can $push more than maxCount

### ISSUE THREAD

**Issue by SierraGolf** [aldeed/meteor-simple-schema#487]
I am unsure if this is a bug or expected behaviour, at least I find it surprising.

Scenario:
* given you have a document with a schema attached which specifies that the document holds an array which should not have more than 2 elements (maxCount: 2)
* and there is a document holding 0 elements in that array
* when you $push one element to that array
* and then push another element to that array
* and then push another element to that array
* then no validation error is thrown
* and the count of the elements in that array is 3

**Comment by JcBernack** [comment]
I was just about to report the same thing.
Seems like the given limit with `maxCount` is applied to the number of elements being pushed, not the resulting array length.

Using your example with `maxCount: 2` the following does not work:

    MyCollection.update(id, { $push: { objects: { $each: [a, b, c] } } });
    Error: You cannot specify more than 2 values

**Comment by SierraGolf** [comment]
@aldeed is simple schema meant to validate the to be persisted document against its already persisted data or is this something one would need to do in a custom validation?

**Comment by aldeed** [comment]
SS has no idea about what's in the database. This leaves several holes. Collection2 is database-aware and can fill these holes (though at the cost of extra DB lookups), but this issue is one of the ones that is still not added. See https://github.com/aldeed/meteor-collection2/issues/12

**Comment by SierraGolf** [comment]
yeah, you are right. I mixed up simple schema and collection2 functionalities. btw. SS is kind of an overloaded abbreviation.
