### ISSUE TITLE
Use function in allowed values Meteor

### ISSUE THREAD

**Issue by mohsinali1317** [aldeed/meteor-simple-schema#488]
In my Competition schema I need to add list of teams. I have defined a TeamSchema and also I have added some teams in the collection. Now I want to add a competitions and add list of teams to that competitions.

This is how my competition schema looks

    var CompetitionsSchema = new SimpleSchema({
    year: {
        type: String
    },
    division: {
      type : String,
      allowedValues: ['Elite', '1st','2nd','3rd','4th','Intro']
    },
    teams:{
        type : [TeamSchema],
        allowedValues : function () {
            return Teams.find().map(function (doc) {
                return doc;
            });
        }
    }
    });

Now when I am trying to insert using autoform like this

    {{> quickForm collection="Competitions" id="insertTeamForm" type="insert"}}

I don't get list of teams to choose from. Am I doing something wrong here?

**Comment by aldeed** [comment]
`allowedValues` can't currently be a function (see #456), but autoform options can:

```js
teams: {
  type: [TeamSchema],
  autoform: {
    options: // your function
  }
}
```
