### ISSUE TITLE
Is there a method to get a Schema for a certain key?

### ISSUE THREAD

**Issue by derwaldgeist** [aldeed/meteor-simple-schema#489]
I would like to validate an object against a bigger part of a schema, for instance only the user profile part of a user schema. Of course I could use nested schemas and save them for reference later. But is there a way to obtain a directly for a certain key? I mean something like

```js
var profileSchema = userSchema.getSchema({key: 'profile'});
check(profileObj, profileSchema);
```

**Comment by aldeed** [comment]
Try [pick](https://github.com/aldeed/meteor-simple-schema#extracting-simpleschemas)

**Comment by derwaldgeist** [comment]
Thanks for your quick reply. I was blind... Will try it and close this issue now.
