### ISSUE TITLE
Object field w/ custom validator not receiving object value

### ISSUE THREAD

**Issue by john-osullivan** [aldeed/meteor-simple-schema#490]
Hello,

I have a schema `Package` (technically the schema is `PackageSchema` and it is attached to the Mongo Collection `Package`, but I'll refer to the schema as `Package` for convenience) which has a nested object `content` which has one of four different structures based on the value of a field `Package.packageType`.  In order to validate this nested object `Package.content`, I'm using a custom validator which gets the value of `Package.packageType` then uses it to determine which of the four possible schemas `Package.content` should be validated against.

The issue I'm running into is that this field doesn't seem to be getting the object which is passed in.  I've verified from immediately before the call to `Package.insert` that the object has a key called `content` whose value is an object containing the data I wish to validate.  Additionally, I've verified from within the custom validator on `Package.content` that the `content` key was set during the insert.  The correct value of what I was trying to insert, however, gets lost.  `this.value` from within the `Package.content` validator returns an empty object rather than the object being passed in.

Is there something wrong what I'm doing, or is there an issue with custom validation on the Object type?

**Comment by john-osullivan** [comment]
Update, I tried reproducing with a fresh schema that only has one field and had the same issue.  It looks like the actual object is getting overwritten when the field has a custom validator.  Trying to look through your code and see where it might be happening, @aldeed , I'll get back to you if I'm able to find something.

**Comment by john-osullivan** [comment]
After some investigative work, the issue is in the SimpleSchema.prototype.clean function.  I'm not specifying the subkeys of the object in the parent schema because the subkeys are different for different instances of the object.  The custom validator selects one of four schemas to perform validation on, but because the sub-keys aren't specified in the schema, the clean function is removing all of the objects values.

EDIT:  Okay, I think I've mostly fixed it.  Turns out that I needed both blackbox and the custom validator specified in order for the sub-fields not to get cleaned away.  The documentation made it seem like the blackbox property would keep the custom validator from being called, but I suppose not!

However, it turns out that my approach doesn't work like I'd hoped.  When I call SomeOtherSchema.newContext().validate(subobject), it doesn't apply any of the autoValue functionality to said object.  That makes sense, considering validation only returns true or false.  Is there some way to conditionally run the field through one of four other schemas and have the autoValue and defaultValue properties of those other schemas take effect?

**Comment by aldeed** [comment]
SS does not support dynamic types. Even if Mongo supports it, I don't think it's usually a good way to write schemas. If there are only 4, you could just have 4 different possible but optional keys and validate that at least one is set. Otherwise you can create a full schema dynamically and validate outside of collection2, like in a method.

This might become easier when the ability to add customer full-doc validators is added, as is planned.
