### ISSUE TITLE
autoValue being repeated

### ISSUE THREAD

**Issue by Xsandor** [aldeed/meteor-simple-schema#491]
I've tried to use autoValue this way.

    autoValue: function(){
      return this.value*10;
    }

I know that autoValue is performed both on the client and the server. But it also seems like the *this.value* on the server is the result from autoValue on the client. So instead of multiplying by 10 it gets multiplied by 100. This is the result when performing an **insert**, when **updating** a value it gets even worse. It runs twice on the client and once on the server, so it's multiplied by 1000 instead.

Is there a better way for me to do this?
I want to store currency as an integer, so it needs to be converted when used and stored.

**Comment by aldeed** [comment]
On the client, collection2 clones the object and sets autovalues and validates the clone only. So the autoValue from the client should not be making it to the server. But maybe it should be deep cloning.

This is a collection2 issue, so I am closing this. You can create an issue in the collection2 repo with more details, like a full schema and `insert` call that can be run to reproduce the issue.
