### ISSUE TITLE
allowedValues pass by reference

### ISSUE THREAD

**Issue by pdiniz13** [aldeed/meteor-simple-schema#492]
There are quite a few other issues setting allowedValues to a function, but Im actually just trying to set it to an array passed by reference.

var someValues = ['Elite', '1st','2nd','3rd','4th','Intro']

var newSchema = new SimpleSchema({
year: {
    type: String
},
division: {
  type : String,
  allowedValues: someValues
}
});

This will save and the allowed values will display on the backend, but they are not being sent over to the front end.

**Comment by aldeed** [comment]
Nothing is sent between server and client. You will need to include this code in both.
