### ISSUE TITLE
Ids must be an object

### ISSUE THREAD

**Issue by dfischer** [aldeed/meteor-simple-schema#497]
I'm completely lost on this.

Why am I getting this error? I want ids to definitely be an array but simple schema is erroring out that is has to be an object with `check()`

How do I make simple schema and meteor support this?
```
type: Object
ids: Array[4]
0: "6Z2kL8vqqi5JmcDZh"
1: "LmMJrjZCpnwNqkRtD"
2: "LXmfgR623k8K94Zsy"
3: "6Z2kL8vqqi5JmcDZh"
```

`check(room, Schema.pick('name', 'type', 'type.ids.$'));` ends up returning `Ids must be an object [400]`

Schema:

```
  'type.ids': {
    type: Array,
 
  },
  'type.ids.$': {
    type: String
  },
```

**Comment by aldeed** [comment]
It should work if you add `'type.ids'` to `pick`
