### ISSUE TITLE
Typescript Classes as Objects : "must be an Object"

### ISSUE THREAD

**Issue by prodogs** [aldeed/meteor-simple-schema#503]
Need some help - i am trying to define a Class in Typescript which could be stored using Simple Schema

i get the following error when trying to store an object which contains the class

Metric Value must be an object

the class is simple now but will get more complex later 

Here is the class definition
<code>
class MetricValue extends C4Object {
    public value : number;
    constructor() {
        super();
    }

    public getValue() {
        return this.value;
    }

    public setValue(value : number) {
        this.value = value;
    }

    public toString() : string {
        return "Value = "+ this.value;
    }

    public clone() : MetricValue {

        var cloneObject = new MetricValue();
        cloneObject.value = this.value;
        return cloneObject;

    }

    public typeName() : string {
        return "MetricValue";
    }

    public toJSONValue () {
        return {
            value: this.value
        }
}

    
} this.MetricValue = MetricValue;
</code>
I have defined the Object as value in the following 
<code>
MetricValuesSchema = new SimpleSchema({
    tags        : { type: String,       label : "Tags", optional : true, defaultValue: ""},
    name        : { type: String,       label : "Metric"},
    description : { type: String,       label : "Description",  optional : true, defaultValue: ""},
    value       : { type: Object,       label : "Metric Value", optional : false, blackbox : true},
    classType   : { type: String,       label : "ClassType",    optional : true, defaultValue: "metricValue"},
    createdAt: {
        type: Date,
        autoValue: function () {
            if (this.isInsert) {
                return new Date;
            } else if (this.isUpsert) {
                return {$setOnInsert: new Date};
            } else {
                this.unset();  // Prevent user from supplying their own value
            }
        }
    },
    updatedAt: {
        type: Date,
        autoValue: function () {
            if (this.isUpdate) {
                return new Date();
            }
        },
        denyInsert: true,
        optional: true
    },
    createdBy: {
        type: String,
        optional: true,
        autoValue: function () {
            return this.userId
        }
    }

</code>
I then tried to store the following object : 

<code>        var object = {
                name : "A Metric Value",
                description : "Another Description",
                value : mv
        }
</code>
where MV is an instance of MetricValue

I then get the following error : 
Metric Value must be an object

and this may help
<code>
[
    {
        "invalidKeys": [
            {
                "name": "value",
                "type": "expectedObject",
                "value": {
                    "value": 10
                }
            }
        ],
        "validationContext": {
            "_simpleSchema": {
                "_schema": {
                    "tags": {
                        "label": "Tags",
                        "optional": true,
                        "defaultValue": ""
                    },
                    "name": {
                        "label": "Metric"
                    },
                    "description": {
                        "label": "Description",
                        "optional": true,
                        "defaultValue": ""
                    },
                    "value": {
                        "label": "Metric Value",
                        "optional": false,
                        "blackbox": true
                    },
                    "classType": {
                        "label": "ClassType",
                        "optional": true,
                        "defaultValue": "metricValue"
                    },
                    "createdAt": {},
                    "updatedAt": {
                        "denyInsert": true,
                        "optional": true
                    },
                    "createdBy": {
                        "optional": true
                    }
                },
                "_schemaKeys": [
                    "tags",
                    "name",
                    "description",
                    "value",
                    "classType",
                    "createdAt",
                    "updatedAt",
                    "createdBy"
                ],
                "_autoValues": {},
                "_blackboxKeys": [
                    "value"
                ],
                "_validators": [
                    null
                ],
                "_messages": {},
                "_depsMessages": {
                    "_dependentsById": {}
                },
                "_depsLabels": {
                    "tags": {
                        "_dependentsById": {}
                    },
                    "name": {
                        "_dependentsById": {}
                    },
                    "description": {
                        "_dependentsById": {}
                    },
                    "value": {
                        "_dependentsById": {}
                    },
                    "classType": {
                        "_dependentsById": {}
                    },
                    "createdAt": {
                        "_dependentsById": {}
                    },
                    "updatedAt": {
                        "_dependentsById": {}
                    },
                    "createdBy": {
                        "_dependentsById": {}
                    }
                },
                "_firstLevelSchemaKeys": [
                    "tags",
                    "name",
                    "description",
                    "value",
                    "classType",
                    "createdAt",
                    "updatedAt",
                    "createdBy"
                ],
                "_objectKeys": {
                    "value.": []
                },
                "_validationContexts": {
                    "default": {
                        "$ref": "$[0][\"validationContext\"]"
                    }
                }
            },
            "_schema": {
                "$ref": "$[0][\"validationContext\"][\"_simpleSchema\"][\"_schema\"]"
            },
            "_schemaKeys": [
                "tags",
                "name",
                "description",
                "value",
                "classType",
                "createdAt",
                "updatedAt",
                "createdBy"
            ],
            "_invalidKeys": {
                "$ref": "$[0][\"invalidKeys\"]"
            },
            "_deps": {
                "tags": {
                    "_dependentsById": {}
                },
                "name": {
                    "_dependentsById": {}
                },
                "description": {
                    "_dependentsById": {}
                },
                "value": {
                    "_dependentsById": {}
                },
                "classType": {
                    "_dependentsById": {}
                },
                "createdAt": {
                    "_dependentsById": {}
                },
                "updatedAt": {
                    "_dependentsById": {}
                },
                "createdBy": {
                    "_dependentsById": {}
                }
            },
            "_depsAny": {
                "_dependentsById": {}
            }
        }
    }
]
</code>

**Comment by abecks** [comment]
I am having the same problem with stamps from stampit. If you try to validate an object that doesn't directly descend from Object, it will always fail.

**Comment by aldeed** [comment]
This should work in SimpleSchema 2.0
