### ISSUE TITLE
Reference error when trying to use schema with check() on server

### ISSUE THREAD

**Issue by matt-jay** [aldeed/meteor-simple-schema#508]
Hi all!

I have followed the examples in the docs in trying to implement autoform for the first time. I am running into an issue with SimpleSchema, however.

Here is an extract of my code: http://meteorpad.com/pad/qntHWnpH4jrXzAE49/Schema

When the form is submitted, the server reports this error:

    Exception while invoking method 'submitQuote' ReferenceError: Schemas is not defined

Why is this happening when `Schemas` is defined in `common.js`?

**Comment by aldeed** [comment]
`var Schemas = {};` should be `Schemas = {};` to put it in the global scope.
