### ISSUE TITLE
Mongo Indexes drop indexes

### ISSUE THREAD

**Issue by ktruckenmiller** [aldeed/meteor-simple-schema#513]
I just had an issue with unique indexes - I changed the schema and moved some indexes around, and mongo wasn't picking up that I had changed indexes. After around 2 days of trouble shooting I finally went into mongo and found that it still had a relic index that was required to be unique.  I removed it and updated my simple schema and it worked. 

Has anyone had this issue? Is there a default index check that happens with meteor start or am I unique in this issue and no one changes their indexes?

**Comment by aldeed** [comment]
The only way to tell it to drop an index is to set `index: false` in the schema and restart, or to drop it yourself.

**Comment by h4de5** [comment]
I had the same problem - took me a while to figure this out. I had a title field set to unique, but changed my mind later on. removing the `uniqe` attribute or setting `unique: false` within the Schema didn't work. it needs this explicit `index: false` statement to drop a previous unique index.
Thanks for the clearification!
