### ISSUE TITLE
Problem with multi dimensional array and sub schemas

### ISSUE THREAD

**Issue by sebakerckhof** [aldeed/meteor-simple-schema#515]
I tried to have a multi dimensional array as per your comment: https://github.com/aldeed/meteor-simple-schema/issues/440#issuecomment-156112138

But this doesn't seem to work with sub schemas:
```js
var RuleSchema = new SimpleSchema({
  parameter:{
    type:String,
    defaultValue:"test"
  }
});

var TestSchema = new SimpleSchema({
  rules: {
    type:Array
  },
  "rules.$" : {
    type:Array
  }, 
 "rules.$.$" : {
    type:RuleSchema
  }
});

var doc = {rules:[[{parameter:"val"}]]};
TestSchema.clean(doc);
```

`val` gets changed to `test` and making `parameter` required will give an error when checking the schema.

**Comment by aldeed** [comment]
Looking at fixing this in v2

**Comment by aldeed** [comment]
Can you clarify what error you get?

**Comment by sebakerckhof** [comment]
Well, if you execute the js snippet,  you'll see that the `doc` gets changed in the clean operation, while it shouldn't, since it conforms to the schema. Same thing: Using `check(doc,TestSchema)` will throw an error while it shouldnt

**Comment by aldeed** [comment]
OK, yeah I'm pretty sure I remember fixing this is devel branch already, but I'll make sure.

**Comment by sebakerckhof** [comment]
This does indeed looks to be solved on the devel branch

**Comment by anjueappen** [comment]
The code I write: 
```
    Schema.Sketch = new SimpleSchema(...); 

    Schema.Round = new SimpleSchema({
    sketches:{
        type: Array,
        label: "Round Sketches",
        defaultValue: [],
        minCount: 0,
    },
    "sketches.$": {
        type: Schema.Sketch,
    },
   });
```

And the error I get: 
`W20170304-22:11:19.714(-7)? (STDERR) Error: sketches.$ key is missing "type"`
