### ISSUE TITLE
Dynamic options for fields

### ISSUE THREAD

**Issue by GerhardJO** [aldeed/meteor-simple-schema#516]
I'm looking to dynamically limit the number of sub-documents based on another field in the schema and was wondering if this was possible:

    MySchema = new SimpleSchema({
       addresses: {
          type: [Object],
          minCount: 1,
          maxCount: this.maxAddress
        },
       maxAddress: {
          type: Number,
          min: 1,
          max: 5
       }
    });

Here the addresses sub-document would be limited to 5 addresses at most depending on what the user selected for the maxAddress field.

I suppose my actual question is if a field is available to other fields as options?

**Comment by aldeed** [comment]
Yeah, see https://github.com/aldeed/meteor-simple-schema#validate-one-key-against-another

**Comment by GerhardJO** [comment]
Aah! There it is and in light of this let me add the novice programmer pledge:

I, @GerhardJO, do solemnly swear to RTFM of any API I use. From it first word to its last, at least twice, as this will prevent me from asking superfluous questions of said APIs developers.

Thanks @aldeed  for being kind enough to answer anyways. Happy holidays.

**Comment by aldeed** [comment]
No worries, happens to everyone
