### ISSUE TITLE
Validating the entire object together.

### ISSUE THREAD

**Issue by AlexFrazer** [aldeed/meteor-simple-schema#517]
I want to validate a whole object. A good example of this is an address. I have a validator that calls out to an API and ask for validation. I tried this.

```
Schemas.Address.addValidator(function () {
  if (this.isSet) {
    Meteor.promise('validate address', this.value).catch(err => {
      Schemas.Address.namedContext('insert-address-form').addInvalidKeys([
        { name: 'street1', type: 'address not found' }
      ])
    });
  }
});
```

this seems to just send every key to this method. I want to send the whole object. There doesn't seem to be any validation on entire objects.

**Comment by aldeed** [comment]
Yeah, I am looking into this feature for v2

**Comment by aldeed** [comment]
Added in v2: https://github.com/aldeed/node-simple-schema#custom-whole-document-validators
