### ISSUE TITLE
Cannot $unset old field deleted from schema

### ISSUE THREAD

**Issue by Firfi** [aldeed/meteor-simple-schema#519]
I had `profile.level` in my schema. I added `profile.level.songs` to schema, moved all `profile.level` from collection to `profile.levels.song` of this collection, and removed `profile.level` from schema. Now I want to delete old `profile.level` values from collection so schema don't get confused in future. However, on

`...update({_id: ...}, {$unset: {'profile.level': ''}}` I get `update failed: Error: profile.level is not allowed by the schema` error message. Actually it doesn't make _any_ sense to me: I don't need profile.level in collection, in fact I want to *remove* it. Any suggestions?

Thanks

**Comment by aldeed** [comment]
I know I fixed this, but it might be only in the v2 which isn't released yet. In the meantime, just skip validation with `validate: false` option.

**Comment by derwaldgeist** [comment]
+1 I ran into the same problem.

**Comment by athyuttamre** [comment]
+1 Just ran into the same problem. @aldeed when might v2 be released? In the meantime, would it be possible to update the documentation to mention this case?

**Comment by gduquesnay** [comment]
+1 Just ran into the same problem.  @aldeed Saw your suggestion to do validate: false.  Can't figure out where to put that.  Didn't see anything in the docs that mentioned how to skip validation.

Here's what I tried:
```
 Customers.update({}, $unset: {cell: '', team: ''}, validate: false)
```
