### ISSUE TITLE
Autoform can't use decimals ending with 0

### ISSUE THREAD

**Issue by serkyen** [aldeed/meteor-simple-schema#520]
I have a cost field that has decimal set to true. but whenever I insert a decimal ending with 0, it omits the 0. For example, I enter 2.30, and then if I check the field in mongodb it shows up as 2.3
Is there any way to keep the 0 ?

HTML
```
<div class="form-group {{#if afFieldIsInvalid name='cost'}} has-error{{/if}}" data-required="true">
          <label class="control-label" for="cost">Cost</label>
          <div class="input-group">
            <div class="input-group-addon">$</div>{{> afFieldInput name='cost'}}
          </div>
          <span class="help-block">{{#if afFieldIsInvalid name='cost'}}{{afFieldMessage name='cost'}}{{/if}}</span>
        </div>
```

JS
```javascript
cost: {
    type: Number,
    decimal: true,
    label: "Cost"
  }
```

Thanks

**Comment by aldeed** [comment]
No there is no way to do that but there really isn't any need to. You can just run the number through a function to properly format it whenever you display it, such as the `numeraljs` library.
