### ISSUE TITLE
can't use parseFloat() in autoValue function

### ISSUE THREAD

**Issue by serkyen** [aldeed/meteor-simple-schema#521]
I have the following autoValue function...

```
autoValue:function(){
    var numberOfUnits = this.siblingField("numberOfUnits").value;
    var cost = this.siblingField("cost").value;
    var costPerKilo = cost/numberOfUnits;
    console.log(costPerKilo);
    return costPerKilo;
}
```

It works ok but it saves the result as something like 1.333333333333
All I want is 1.33

So if I change it to...

`var costPerKilo = parseFloat(cost/numberOfUnits).toFixed(2);`

autoform no longer lets me submit the form.
I can see the correct value of 1.33 in the console each time I click submit. 

What am I doing wrong?

**Comment by aldeed** [comment]
Probably your schema is expecting a number but toFixed returns a string. So you could change your schema, or store it as the float and run it through toFixed when you display it.
