### ISSUE TITLE
check(object, Schema.object) passes function in tests

### ISSUE THREAD

**Issue by newsiberian** [aldeed/meteor-simple-schema#522]
Hello, I'm notice unexpected behavior of SS with `check` in tests. I've used [this schema](https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-schemas/common/schemas/address.js#L26)

Then, there is a server Method, which contain such code:
```javascript
"accounts/addressBookAdd": function (address, accountUserId) {
    check(address, ReactionCore.Schemas.Address);
    check(accountUserId, Match.Optional(String));
...
});
```
If I trying to call method in such way: 
```javascript
expect(function () {
  return Meteor.call(
    "accounts/addressBookAdd",
    () => {console.log("test")},
    () => {}
  );
}).toThrow();
```
It is successfully passed the `check`. Is this expected? This was not reproduced in browser.

**Comment by aldeed** [comment]
What does the method receive? Since function can't be sent over wire, I'm assuming `address` and `accountUserId` are probably `undefined` in your test. It's possible that no error is thrown when the first arg to `check` is undefined. Is that the issue?

**Comment by newsiberian** [comment]
Hi, in situation with browser, yes, method receive `undefined` or `null` as address.  I did not remember. But in Velocity's tests method receives a `function` and the main problem here - SS passes this `function` through.

**Comment by aldeed** [comment]
Closing this since it doesn't really seem like an issue with this package.
