### ISSUE TITLE
Safe to clean a constant?

### ISSUE THREAD

**Issue by fabyeah** [aldeed/meteor-simple-schema#524]
I'm using ```let``` and ```const``` everywhere now, so I just wanted to ask if it is safe to clean a constant or is there any case in which this would throw an error?

**Comment by aldeed** [comment]
I assume it would throw an error, but I haven't tried. Cleaning mutates the object.

**Comment by fabyeah** [comment]
I think all the listed cleaning options (https://github.com/aldeed/meteor-simple-schema#cleaning-data) only mutate the objects properties, which is fine with constants.
Or is there some part of the code that actually reassignes the object ```obj = ...```

I faintly remember getting an error once, before I changed all occurrences to let, but I can't be sure... Also I don't really know how to test this and cover all potential cases.

**Comment by aldeed** [comment]
Changing my answer, I don't think there's any problem here.

**Comment by macrozone** [comment]
@aldeed: short question, is this still the case on the npm-version? Just run into a bug, because I did not know that clean does mutate the object. IMHO you should never alter objects and treat everything as immutable (unless you have a very good reason to do so).
