### ISSUE TITLE
Is it possible to use the output of afFieldMessage in placeholder property?

### ISSUE THREAD

**Issue by Frenkieb** [aldeed/meteor-simple-schema#525]
Hi, 

I have an input {{> afFieldInput name='firstname' placeholder="First name"}}
When submitting and the form generates an error, is it possible to put the output of {{{afFieldMessage name='firstname'}}} in the placeholder of the input 'firstname'?

I tried to change the placeholder text in the onError hook with AutoForm.validateField but that returns just a boolean, not what the error is exactly. The error text could be that input is required or that it's not in the correct format.

**Comment by aldeed** [comment]
Did you try?

```
{{> afFieldInput name='firstname' placeholder=(afFieldMessage name='firstname')}}
```

See https://github.com/meteor/meteor/tree/devel/packages/spacebars#nested-sub-expressions
