### ISSUE TITLE
Combining schemas doesn't combine defaultValues

### ISSUE THREAD

**Issue by bigSmallio** [aldeed/meteor-simple-schema#527]
When combining these schemas, defaultValues aren't combined.

```
Schema.stats = new SimpleSchema({
  topicCount: {
    type: Number,
    defaultValue: 0
  }
});

Schema.users = new SimpleSchema({
  stats: { type: Schema.stats  }
  // expected behavior is that nesting Schema.stats implies a nested default.  e.g.
  // defaultValue: { topicCount: 0 }
});


Meteor.users.attachSchema(Schema.users);
```

This doesn't seem to be the case, and causes some confusion.

The best I can come up with is:
  1. Make everything optional in all schemas
  2. Include the default value in both schemas, which is extra maintenance

This could be better documented in [defaultValue](https://github.com/aldeed/meteor-simple-schema#defaultvalue) or [combining schemas](https://github.com/aldeed/meteor-simple-schema#combining-simpleschemas)

```
Schema.stats = new SimpleSchema({
  topicCount: {
    type: Number,
    defaultValue: 0
  }
});

Schema.users = new SimpleSchema({
  stats: {
    type: Schema.stats,
    defaultValue: { topicCount: 0 },
  }
});

Meteor.users.attachSchema(Schema.users);
```

It's not the end of the world, but it would be nice to write this code in just one place.  More than two "levels" and it's a mess.

**Comment by bigSmallio** [comment]
example from #418

**Comment by aldeed** [comment]
I'm pretty sure this should work in v2
