### ISSUE TITLE
allowed values

### ISSUE THREAD

**Issue by shiftux** [aldeed/meteor-simple-schema#532]
Hello,
I am using simple schema in combination with auto form.
my schema has an entry like so: 
```javascript
    workouts:{
      type: [String],
      allowedValues: _.pluck(Categories.find({}).fetch(), "exercise"),
      // allowedValues: ['a', 'b', 'c'],
      optional: true
    }
```
in my html I have the corresponding field like so:
```javascript
    {{> afQuickField name='workouts' options="allowed" type='select-checkbox'}}
```

My problem is that I don't get anything displayed in the form. The query works in the shell and if I replace the query with a simple array `['a', 'b', 'c']` the output is displayed as expected. I thought it might be a publication issue and tried to publish all 'Categories' (the whole collection) but that didn't help either... 

Can anyone please give me a hand here? - Thanks a lot

**Comment by Ajaxsoap** [comment]
Hi @shiftux ,

in my schema, the allowed values is inside autoform like this:

```
autoform: {
      options: function () {
      type: "select",
      firstOption: 'Choose a category', // optional, for better UX
        return Categories.find().map( function ( categ ) {
          return {
            label: categ.name,
            value: categ._id
          };
        } );
      },
    }
```
No need to use _.pluck method, lastly, on your template:

```
{{> afQuickField name='workouts' }}
```
I hope this helps your problems.

**Comment by shiftux** [comment]
Thank you @Ajaxsoap!
That seems to work for the template...
2 questions on that:
- What I liked about the "allowed values" was that it verified the content. Meaning it's a check, so that no one could enter false values. This is kind of lost with your solution, no?
- The submit template works fine. What I haven't figured out is the update template. I can't get it to show the content that was originally submitted, plus the complete list of options for the workouts (with the previously selected ones still selected initially)
Thanks again!

**Comment by Ajaxsoap** [comment]
You mean a user can enter a values in your checkbox? From my suggestion it's assumed that the categories collection is already populated with data. So it depends if you have a user filter to populate the checkbox with categories. 

Is your data is in the table or a post with an edit button? It's better if you provide more details on how you update your collection. 

on my app, I have a table, whenever a user ``click`` a row ``tr``, it triggers click event and the router will bring the user to the update route. What I normally do in my app to update a certain document, I just pass a parameter ``_id `` on the router something like:
```
'click tbody > tr': function ( event ) {
    Router.go( 'updateRoute', {
      _id: this._id
    } );
  }
```
It depends on your router, or if you use flow router you can refer to meteor [guide](http://guide.meteor.com/routing.html) on routing.

I hope this helps your problem.

**Comment by aldeed** [comment]
I am closing old issues. If you still need help, please submit a new issue
