### ISSUE TITLE
Schema type object without defining the keys

### ISSUE THREAD

**Issue by ekeuus** [aldeed/meteor-simple-schema#533]
I have tried to add an object as a part of a schema and the values are only stored if the object's children are described as "object.child" in the schema.

I currently got a solution working by serializing the object and storing it as a string, but it will negate all hopes of searching by those values in the future. 

Am I missing something about the object type and/or is there a workaround for this?

**Comment by mbreuer23** [comment]
have you tried ```blackbox: true```? 

in other words : 
```
myObj: {
    type: Object,
    blackbox: true
}
```
then you can add any keys you want to ```myObj```
