### ISSUE TITLE
what is the different between' type:new SimpleSchema({})',and 'type:Object'

### ISSUE THREAD

**Issue by dengjianan** [aldeed/meteor-simple-schema#541]
hello,i am student of chinese this is my question @dburles 
defined an object of Communication
```
Communication = new SimpleSchema({
  callSignal: {
    type: String
  },
  frequency: {
    type: String
  },
  fixedPhone: {
    type: String
  }
});
```
```
  communication: {
    type: Communication,
    optional: true
  },
```
however,when i use autoform to create,communication is invaid,then i defined as follows:
``` 
  communication: {
    type: Object,
    optional: true
  },
  "communication.callSignal": {
    type: String
  },
    "communication.frequency": {
    type: String
  },
    "communication.fixedPhone": {
    type: String
  }
```
it can be created

**Comment by aldeed** [comment]
Either one should work as long as `Communication` is defined before you use it (in a file that loads before the file in which it's used, or closer to the top of the file).
