### ISSUE TITLE
Empty string value deletes the entire field from document

### ISSUE THREAD

**Issue by v3rron** [aldeed/meteor-simple-schema#543]
I have a very simple user profile schema that looks like this:
```
Schemas.UserProfile = new SimpleSchema({
  first_name: {
    type: String,
    label: "First name",
    regEx: /^[a-zA-Z -]{2,32}$/,
    optional: true
  },
  last_name: {
    type: String,
    label: "Last name",
    regEx: /^[a-zA-Z -]{2,32}$/,
    optional: true
  },
  picture: {
    type: String,
    label: "Photo",
    optional: true
  },
  about: {
    type: String,
    label: "About me",
    optional: true,
    max: 255
  }
});
```
on the server I have a Meteor.method:
```
userProfileUpdate: function( userData ) {
    if( !userData ) {
      throw new Meteor.Error( 400, "No data provided for updating a user document" );
    }
    return Meteor.users.update( { _id: this.userId }, { $set: {
      "profile.first_name": userData.first_name,
      "profile.last_name": userData.last_name,
      "profile.about": userData.about,
    }});
  },
```
when I use `Meteor.call('userProfileUpdate', { first_name: "" });` it deletes the entire field, so I no longer have profile.first_name, so `profile: Object` looks like this:
```
about: "this is me"
first_name: "Ronen"
picture: "1EtM6q643nXjwutYq"
__proto__: Object
```
PS: when I set `userData` to `{ first_name: null }` it will set the value correctly in this case:
```
about: "this is me"
first_name: "Ronen"
last_name: null
picture: "1EtM6q643nXjwutYq"
__proto__: Object
```
PPS: if I set it to `undefined`, then the value stays as it was before.

**Comment by aldeed** [comment]
I am closing old issues. If you still need help, please submit a new issue. The answer to this is to set the [removeEmptyStrings](https://github.com/aldeed/meteor-collection2#skip-removing-empty-strings) option to `false`.
