### ISSUE TITLE
Error: Object has no method "Attach Schema"

### ISSUE THREAD

**Issue by Kamin12** [aldeed/meteor-simple-schema#549]
Hello,

Is Simple Schema compatible with Grid FS?  

I have defined a Grid FS collection: 

Images = new FS.Collection('images',{
  stores:[new FS.Store.FileSystem('useruploads',{path:'...'})]
});

and a Schema... 

Images.attachSchema(new SimpleSchema({

.....

}));

But am getting the error: TypeError: Object [object Object] has no method 'attachSchema...

Looks like it won't allow me to use the attachSchema method with Grid.FS. Is there any work around for this?

Thanks and hope to hear from you soon.

Best,

Ari Kamin
.

**Comment by RenMan** [comment]
I'm dealing with the same issue, so I'll be watching this to see what answer is given.  If I run into a workaround elsewhere, I'll post it here.

**Comment by dr-dimitru** [comment]
[this FS/Files package](https://github.com/VeliovGroup/Meteor-Files) is supports schema

**Comment by aldeed** [comment]
You'd just have to attach to the underlying collection, like `Images.files.attachSchema`
