### ISSUE TITLE
Overly complex validation using picked schemas...

### ISSUE THREAD

**Issue by kaurinz** [aldeed/meteor-simple-schema#554]
Maybe I missed something in the documentation, but I've come across a use case that has seemingly demanded an unnecessarily verbose and performance degrading approach to implement.

My case:

I have schema that validates an object that a user fills out.  The UI presents this to the user using a series of tabs.  When each tab subsection is complete and valid, I show an icon to the user indicating that everything checks out for that section.

However, the only way to do this seems to involve creating numerous schemas based on my original complete one.  This is fine, but as ".clean()" modifies the original object, I have to clone the object once for each tab, and then clean each cloned copy according to the previously picked schema.

Whereas, this whole thing would be far easier if I could pass a flag into the validate function, something like "ignoreAdditionalFields", without having to clean the object first.  Then I wouldn't need to clone it for each tab nor clean it prior to validating against these picked schemas.

Maybe my solution is over complicated and I missed something.  Any suggestions or comments would be great.  I'm not sure how difficult it would be to implement this feature, but I think it would make matters easier for others in similar situations.

**Comment by aldeed** [comment]
Having separate form schemas for each tab is best, but you can simplify it by using the `.pick()` function to pick just the fields that are on each form out of the overall schema. Regarding clean mutation, that no longer happens by default in SimpleSchema 2.0.
