### ISSUE TITLE
Make possible to set field 'undefined' in autoValue

### ISSUE THREAD

**Issue by Firfi** [aldeed/meteor-simple-schema#556]
I have another runtime typecheck system that I integrate with meteor-simple-schema. It's quite strict about fields and it's values, i.e. it accepts undefined field values but fields themselves (keys) should be there. `this.unset()` unsets the field itself, purging it with key from document. If I return `undefined`, predictably, it doesn't do anything by the lib docs. Is there a way to make it possible to set field to `undefined` in autoValue?

**Comment by aldeed** [comment]
Unfortunately this is not even remotely possible due to how values are handled internally.
