### ISSUE TITLE
Can't add validation messages on instance specific schema

### ISSUE THREAD

**Issue by lnmunhoz** [aldeed/meteor-simple-schema#559]
When I tried to use `mySimpleSchemaInstance.messages({myErrorMessage: 'error message'})`,  the validation after submit the form don't find the error and returned to me an `Error: Unknown validation error`.

I'm using the `custom` validation and the function returns `'myErrorMessage'` string. When I use `SimpleSchema.messages({myErrorMessage: 'error message'})` it works just fine.

**Comment by macrozone** [comment]
Same for me. instance.messages() seems to have no effect

**Comment by macrozone** [comment]
in my case the problem was that i extended from the schema where i defined the messages

```
const schemaA = new SimpleSchema();
schemaA.messages(mymessageobject); // messages work on this schema
const SchemaB = new SimpleSchema([schemaA, {... extension.... }];
// schemaB will NOT have mymessageobject. This gets not passed.
```

**Comment by aldeed** [comment]
I believe this is fixed by v2
