### ISSUE TITLE
Why all fields required for update operation?

### ISSUE THREAD

**Issue by pronevich** [aldeed/meteor-simple-schema#563]
Example: collection with docs where each doc has 20 fields. All fields are required for insert, but user sometimes update only few. When we {$set: {'companyName': 'Apple'}}  will be thrown error that another fields required.

**Comment by thomasmery** [comment]
I also ran into this but I think you have to filter your Schema on an update to only validate the fields you are actually updating

you can use `pick`for this
[Extracting SimpleSchemas](https://github.com/aldeed/meteor-simple-schema#extracting-simpleschemas)

any one more advanced with the library might help more I guess

**Comment by aldeed** [comment]
It does not require missing fields on update. You would have to post a more detailed reproduction to find out what's going on. But since this issue is old, I'm guessing it's been resolved.
