### ISSUE TITLE
Customizing a regEx error message removes default error messages of all other regEx

### ISSUE THREAD

**Issue by mjgallag** [aldeed/meteor-simple-schema#564]
If you customize a regEx error message it removes the default error messages of all the other regEx.

```javascript
SimpleSchema.messages({
  regEx: [
    {
      exp: SimpleSchema.RegEx.Phone,
      msg: '[label] must be a valid phone number'
    }
  ]
});
```

**Comment by aldeed** [comment]
The way regEx messages are defined in v2 is different, and I don't think this would be an issue anymore.
