### ISSUE TITLE
Is a string invalid because it has \t and \n in it?

### ISSUE THREAD

**Issue by a4xrbj1** [aldeed/meteor-simple-schema#565]
I'm checking the following string:

    3	120,771,538	124,348,989	2.4	634
    4	118,435,301	122,371,347	2.4	603
    7	43,840,265	47,079,909	4.0	553
    9	898,750	6,659,474	14.6	1,819
    14	46,631,810	50,054,957	2.3	539
    16	2,025,998	2,996,585	1.5	534
    17	56,851,020	60,825,222	3.6	504

which has tabs and new lines in the form of \t and \n in it. The typeOf confirms that it's a string, yet SimpleSchema rejects the validation with `is not allowed by the schema [validation-error]`

code used:

    new SimpleSchema({
            oneToManyContent: {type: String}
        }).validate({oneToOneContent});

**Comment by aldeed** [comment]
"is not allowed by the schema" means the property name isn't in the schema. Has nothing to do with string validation. (Guessing you already figured that out)
