### ISSUE TITLE
this.unset() under autoValue field is not working

### ISSUE THREAD

**Issue by devarashetty** [aldeed/meteor-simple-schema#566]
`'checking': 
 {   
      type:String,
      optional:true,
      autoValue:function(){
       if(this.siblingField('type').value != "//some string"){
          this.unset();
        }
      },`
the checking value is still showing in the doc but accoring to this statement
 **If you don't want it to be in the doc or modifier, you must call this.unset()** , it should not be there

**Comment by aldeed** [comment]
Would need more details (like what your insert/update call is) to debug this, but I'm guessing you've figured it out by now anyway.
