### ISSUE TITLE
this.field does not work

### ISSUE THREAD

**Issue by edvinsalo35** [aldeed/meteor-simple-schema#568]
I am using SimpleSchema for my project and I get this issue when I try to decide label based on other fields. 

Here is my Schema.

```
Schemas.Questions = new SimpleSchema({
  'text': {
    type: String,
    label: "Your Question",
    max: 200,
    autoform: {
      rows: 1
    }
  },
  'type': {
    type: String,
    allowedValues: ['Multiple Choice', 'Numeric', 'Year', 'Geo-Point'],
    label: 'What type of question are you asking?',
    autoform: {
      firstOption: "Please select one type",
      options: 'allowed'
    },
    optional: false
  },
  'min': {
    type: Number,
    optional: true,
    label: function() {
      if(this.field('type').value == "Year") {
        return "Minimum Year"
      }
      return "Minimum Value"
    }
  }
});
```
 

And this is the autoform that I am using. 

```
{{#autoForm schema=Schemas.Questions collection=Collections.Questions id="insert_question" type="insert"}}
	<div class="card-content">
          {{> afQuickField name="type"}}
	  {{> afQuickField name="text"}}
	  {{> afQuickField name="min"}}
	</div>
{{/autoForm}}
```

So, in label function, "this" returns blank object {} now. 

I can't understand why this returns {} .

Please help me!

**Comment by jeffyamada** [comment]
I've been looking to make options in a select field dynamic - and the options I've seen involve hooks, have you tried using hooks?

**Comment by BudgieInWA** [comment]
A `label` function will unfortunately always be called with `this` equal to `{}`.

In your case, you will need to use the AutoForm API to get the current value of field and set the label manually.

**Comment by devarashetty** [comment]
Try  using  `{{#autoForm schema=Schemas.Questions label={//some helper}} collection=Collections.Questions id="insert_question" type="insert"}}`

**Comment by aldeed** [comment]
Yeah if there is any issue here it would be an autoform issue
