### ISSUE TITLE
Ability to get current context in custom validation in method callbacks

### ISSUE THREAD

**Issue by Neobii** [aldeed/meteor-simple-schema#569]
It looks by your custom validation recipe that I will have to add invalid keys to all the name contexts which uses this custom validation (ie signup, change email..)

```javascript
Meteor.call('emailIsAvailable', this.value, function(err, res) {
  if(!res) 	registerSchema.namedContext("userRegisterForm").addInvalidKeys([{name: "email", type: "emailNotUnique"}]);
});
```

Any way to make this more dynamic?

**Comment by aldeed** [comment]
Not sure what the request is here. Please propose how a new API would look if that's what you're requesting.
