### ISSUE TITLE
Regex for Random.id()

### ISSUE THREAD

**Issue by ghost** [aldeed/meteor-simple-schema#570]
Hello Eric, where'd you find the info for [this regex](https://github.com/aldeed/meteor-simple-schema/blob/4ead24bcc92e9963dd994c07d275eac144733c3e/simple-schema.js#L551)?

**Comment by babenzele** [comment]
This can be closed, the source for the regex is stated in the comment above the linked to line.

character list: https://github.com/meteor/meteor/blob/release/0.8.0/packages/random/random.js#L88
string length: https://github.com/meteor/meteor/blob/release/0.8.0/packages/random/random.js#L143
