### ISSUE TITLE
Validation on Bulk.find.upsert

### ISSUE THREAD

**Issue by lorenzogm** [aldeed/meteor-simple-schema#572]
I'm trying to validate my schemas on Bulk.find.upsert.

https://docs.mongodb.org/manual/reference/method/Bulk.find.upsert/

```
var bulk = Items.rawCollection().initializeUnorderedBulkOp();
for (row = 0; row <= lastRow; row++) {
    bulk.find({ _id: itemId }).upsert().updateOne({
       key: "key",
       name: "name",
    });
}
var execute = Meteor.wrapAsync(bulk.execute, bulk);
execute();
```

Any idea how to include the SimpleSchema validation in the code?

Thanks in advance.

**Comment by aldeed** [comment]
I haven't thought much about how to support bulk yet since it's not something Meteor API officially supports yet. It would be good to do eventually, but this should be proposed over in the Collection2 repo since it's specific to Mongo collections.
