### ISSUE TITLE
[feature request] Throw an Error if a Schema definition key has a 'type' field set to 'undefined' 

### ISSUE THREAD

**Issue by xavierpriour** [aldeed/meteor-simple-schema#573]
Currently if you set 'type' to an undefined variable, SimpleSchema will happily (and silently) clean the whole content of your object... It would have spared me hours of debugging if he just raised an error :cry: 

```javascript
const myOwnSchema = {
    type1 = new SimpleSchema({
    // ...
    });
}

MyCollection.attachSchema({
    field1: {
        type: myOwnSchema.Type1 // Notice the capitalization error, resulting in undefined instead of my schema
    }
})
```

@aldeed I'll happily do a PR if you're ok with the idea

**Comment by aldeed** [comment]
v2 throws an error: https://github.com/aldeed/node-simple-schema/blob/master/lib/SimpleSchema.js#L735
