### ISSUE TITLE
Simple Schema - Updates all fields?

### ISSUE THREAD

**Issue by fdddk23** [aldeed/meteor-simple-schema#576]
Hi,

Can ayone help me with my problem?

http://stackoverflow.com/questions/35961229/meteor-simple-schema-updates-all-fields

Thanks - don't now how to handle this

**Comment by gabrielpoca** [comment]
Hi @fdddk23 looking at your code I guess you are putting business logic inside custom validators in your schema. I would strongly recommend you do that in meteor methods. I'm not sure how familiar you are with those, but feel free to ask questions. In my opinion, the schema should only validate the fields data, and maybe simple relations between them.

**Comment by fdddk23** [comment]
@gabrielpoca : Thanks foy your reply! Yes you are right and I'm using now collection-hooks - which are the better approach!

**Comment by gabrielpoca** [comment]
@fdddk23 because I think the best would be to have a function that does your custom validation and only after update the collection. By custom validation I mean this code:

```
          var colour = Colours.findOne({_id:this.docId});
          if (typeof colour !== 'undefined')
          {
            if (typeof colour.AppointmentId !== "undefined") 
            {
            return "appointmentAssigned";
            }
```

Does it make sense?
