### ISSUE TITLE
how to specify a field with several possible types?

### ISSUE THREAD

**Issue by zhaoyao91** [aldeed/meteor-simple-schema#578]
I want a field which may be an object or a string, how to do that?

**Comment by gabrielpoca** [comment]
Hi @zhaoyao91 , could you provide more context? It is not clear what your intentions are. A couple of things that may allow you to accomplish that are [custom validators](https://github.com/aldeed/meteor-simple-schema#custom) or [mutiple schemas](https://github.com/aldeed/meteor-collection2#attaching-multiple-schemas-to-the-same-collection). Do any of these solve your issue?

**Comment by zhaoyao91** [comment]
I mean, eg. the field password can be a string or object{algorithm, hash}

**Comment by gabrielpoca** [comment]
It still depends on the context. Or maybe I'm not understanding. Don't multiple schemas work?

**Comment by zhaoyao91** [comment]
yeah, you can use two schemas, but it's not good, because the users must know this(use two schemas to check).

**Comment by jpmoyn** [comment]
+1 I am looking for the ability to make a key either null or a Number. Is this possible? Can't find it in the custom section of the docs.

**Comment by tiberiumaxim** [comment]
I have the following situation: I'm creating a timeline of a user's trip and must add several types of cards. The cards property is an array of different kinds of cards. I need to validate the content of those cards.

`
var timeline = new SimpleSchema({
  startDate: {
    type: Date
  },
  endDate: {
    type: Date
  },
  cards: {
    type: Array
  },
  'cards.$': {
    allowedValues: [flightCard, accommodationCard] // the card could be either for flight or accommodation
  }
});
`

**Comment by jpmoyn** [comment]
@tiberiumaxim Is there any particular reason why you wouldn't just break them up into two separate arrays?

**Comment by tiberiumaxim** [comment]
@jpmoyn My app is already implemented and would need code changes on the logic side.
Besides, you design the structure to match the needs and the way you need to access the data.
Don't you think that's a bit unintuitive? To change the data structure just to please the schema package?

**Comment by jpmoyn** [comment]
@tiberiumaxim I see what you mean. I was just trying to offer up a potential solution given the current circumstance.

**Comment by aldeed** [comment]
This was added in v2: https://github.com/aldeed/node-simple-schema#multiple-definitions-for-one-key
