### ISSUE TITLE
publish on npm?

### ISSUE THREAD

**Issue by smeijer** [aldeed/meteor-simple-schema#584]
Would it be hard to remove dependencies on the `meteor` framework, so we can publish this on `npm`?

That way its easier to wrap some tests around it.

**Comment by zeroasterisk** [comment]
The [devel](https://github.com/aldeed/meteor-simple-schema/tree/devel) has that as WIP right now... eagerly awaiting new version of package.

_(this is a lot like v0.9 release, when all the core packages people rely on needed to be updated to follow Meteor core)_

**Comment by MechJosh0** [comment]
@aldeed Do you have an update on this? Last commit was over 2 months ago.
When do you think v2.0 will be out?

**Comment by SachaG** [comment]
I'm curious to know as well. With the direction things are going, I feel like new Meteor projects should probably try and avoid using non-NPM packages as much as possible. So if there are no plans to port SimpleSchema to NPM (which is totally understandable given the amount of work) it'd be good to know as soon as possible.

**Comment by macrozone** [comment]
This would make usage of SimpleSchema much easier in mantra-projects. Also you can't test code that has dependency to simpleSchema currently with the default setup :-/

**Comment by aldeed** [comment]
v2 is a node package: https://github.com/aldeed/node-simple-schema

**Comment by SachaG** [comment]
This is awesome! Does this mean v2 is now the officially supported/recommended production version?

**Comment by aldeed** [comment]
@SachaG I'm putting 90% energy toward v2 vs. 10% toward v1. I'm working through issue and PR backlog and will put out some minimal fixes releases for v1, but in general v2 will get more attention. v2 should be fine on production now if you are not using autoform. I am not putting a final v2 release out until I have a chance to publish an autoform release with support for it. My guess would be sometime in Oct. for that.

**Comment by macrozone** [comment]
@aldeed: <3 

The guys from the awesome uniforms-package (autoform for react) started also working on simple-schema 2 support: https://github.com/vazco/uniforms/issues/99
