### ISSUE TITLE
onDocumentCommit or onDocumentSave

### ISSUE THREAD

**Issue by yushaUzumo** [aldeed/meteor-simple-schema#585]
It would be nice to have a function that can be called when the document has been commited/saved. I know you can have a whole lot  of boiler plate on the update/insert callback function that is inside the if check "if (! error) {....}". I just think it would be much neater to have a function that can be called at the end as part of meteor-simple-schema. A nice use case for this would be sending a verification email after emails.$.address is updated with a new email as part of Meteor.users profile and email update.

**Comment by aldeed** [comment]
This would be something for the collection2 repo, but I don't really understand why this would be useful. Collection2 just follows the Meteor API so I think this wouldn't change unless Meteor changes their API.
