### ISSUE TITLE
Add checkUndefinedFields clean option to validator

### ISSUE THREAD

**Issue by yushaUzumo** [aldeed/meteor-simple-schema#586]
A cleaning option that checks for undefined fields would be nice. So if checkUndefinedFields: true, then no field in the document must be undefined all fields must be set to some value including empty spaces; just as long as it is a value! Use case would be if you always want all the fields to be passed. I know this use case might not be very common but if you do come across it then not having the clean option tends to be slap in the face.

**Comment by BudgieInWA** [comment]
The cleaning step involves modifying the doc in preparation for validation. The `removeEmptyStrings` option to the clean method (which is `true` by default) removes keys whose values are `""`.

Can you get the behaviour that you need by using `removeEmptyStrings: false` and making the keys required? If not, how is it different?

**Comment by aldeed** [comment]
All fields are required by default unless you add `optional: true`, so I'm not sure what this setting would do. Maybe you are suggesting that it would just set missing string fields to empty strings when cleaning them?
