### ISSUE TITLE
String fields throws expectedString validation error

### ISSUE THREAD

**Issue by ajnavsun** [aldeed/meteor-simple-schema#589]
Hi,

I have created a SimpleSchema 
AgeSchema = new SimpleSchema({
    age: {
        type: String,
        label: "Age",
        optional: true
    },
    dateOfBirth: {
        type: Date,
        label: "Date of Birth",
        optional: true,
   }
})
Then I have created another schema with 
AgeSchema2 = AgeSchema.pick([ 'age' ]);

Now while validation the age field for AgeSchema2 with value as 23 it throws expectedString validation error.
Second issue is that although I made dateOfBirth as optional it still give a validation error.
Kindly help.

Regards,
Ankit

**Comment by aldeed** [comment]
Closing old issues. If you still think there is a bug here, let me know.
