### ISSUE TITLE
Number regEx

### ISSUE THREAD

**Issue by julienrott** [aldeed/meteor-simple-schema#592]
Hi,

Is it possible to use the regEx option in combination with the decimal: true and type: Number ?
I would like to have decimal numbers with maximum 2 decimal digits.
I would like a number to match /^\d+\.\d{2}$/

Regards.

**Comment by aldeed** [comment]
Regular expressions are for strings, so you are better off storing as a string. You can't actually limit the number of decimals of a Number in javascript anyway since it's a float.
