### ISSUE TITLE
README should note that defaultValue is evaluated at schema instantiation

### ISSUE THREAD

**Issue by rhettlivingston** [aldeed/meteor-simple-schema#594]
This is probably correct behavior and perhaps it should have been obvious to me, but somehow I had it in my head that the following two lines are the same, but they aren't.

> defaultValue: this.userId 
> autoValue: function () { if (this.operator === null && !this.isSet) return this.userId; },

In the case of the defaultValue, "this.userId" is evaluated during the call to the SimpleSchema constructor and its return value is stored for use in the function. In the case of the autoValue, "this.userId" is evaluated during the collection mutation operation.

That has a profound effect of course on whether or not the extendAutoValueContext in the insert statements (as shown below) can help. I knew that defaultValue was implemented with autoValue and thus had an expectation that extendAutoValueContext would apply to it.

> List.insert(doc, { extendAutoValueContext: { userId: <<some userId source>> } });

It could also lead to really hard to find problems when variables or functions referenced in defaultValues change between SimpleSchema instantiation and usage in mutators. I wonder how many undiscovered issues are out there due to this behavior. I guess it should have been obvious to me, but my belief was that the code I provided was being plugged into the autoValue, not its evaluation.

I do question whether this is expected behavior though I'm not good enough with JS yet to know whether the string "this.userId" could be found by SimpleSchema as it could in some other languages.

At the least, I think this behavior is non-intuitive enough that it should get mention in README along with the other notes on defaultValue behavior. It took quite a bit of debugger tracing before I realized what was happening. It seems that the practice of usage of defaultValue as implemented should be strictly limited to literal values or simple operations with literals.

**Comment by BudgieInWA** [comment]
This behaviour is a consequence of JavaScript not a consequence of Simple Schema. All that the `SimpleSchema`

**Comment by aldeed** [comment]
Yeah I think I agree with @BudgieInWA.
