### ISSUE TITLE
Is there a way to verify if some field was changed in autovalue?

### ISSUE THREAD

**Issue by ilacyero** [aldeed/meteor-simple-schema#595]
I have an generic autovalue for updatedAt, but I only want to set this value if there is change in another field.

I can't use this.field(FIELD_NAME), because it is generic.

**Comment by Gary-Ascuy** [comment]
I have the same issue could you please take a look or send us a workaround

**Comment by aldeed** [comment]
Please post more details if you still need help with this, and I will reopen. I don't know what you mean by "because it is generic".
