### ISSUE TITLE
Ignore 'keyNotInSchema' errors

### ISSUE THREAD

**Issue by Gywem** [aldeed/meteor-simple-schema#599]
Is there a way to ignore 'keyNotInSchema' errors types from the validation process of a schema?

I just want to validate the keys I define in my schema and ignore the rest.

**Comment by BudgieInWA** [comment]
You can use the `clean` method on a your Simple Schema instance (ensuring that the `filter` option is true) to filter the document down to those keys that are in the schema, before validating. See https://github.com/aldeed/meteor-simple-schema#cleaning-data

**Comment by aldeed** [comment]
In v2, there is also an `ignore` option: https://github.com/aldeed/node-simple-schema#validation-options
