### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by Nemo64** [aldeed/meteor-simple-schema#60]
I miss an option `defaultValue` which would be inserted by the clean method. I know that collection2 delivers a `autoValue` but things aren't always inserted into the database and even then it takes some of the same logic every time I want to implement a default value.

**Comment by AndyWilkinUK** [comment]
Liking the defaultValue, works well with the select box, automatically selects that option. Though is there anyway I can use that value to pre-fill the input box in autoform?

**Comment by vincro** [comment]
I can see no apparent and obvious way to set default values on array fields.  I am using a custom template within which I have afArrayEachItem, but when clicking .autoform-add-item, the entry comes up blank, with no preselected value.

tracking a dependency on the form.field.deps, doesn't work without using _.delay, as one cannot guarantee items have been added to the dom reactively, and surely using a default element in the field is the best option.

Any direction would be handy.
Thanks!
