### ISSUE TITLE
Setting unique: true won't work

### ISSUE THREAD

**Issue by THPubs** [aldeed/meteor-simple-schema#605]
Hi, I have setup a field to be unique using `unique: true`. I'm trying to validate it in the client and use `invalidKeys()` to get all the errors. But I can't see the uniqueness error in there! Looks like it will allow me to add duplicate values?

I'm trying to set one field to be unique using simple schema. But no matter what I do it's not working. Here's how I set it up :

    let schema = new SimpleSchema({
      name: {
        type: String,
        label: 'Committee name',
        max: 200
      },
      shortName: {
        type: String,
        label: 'Short name',
        max: 10,
        index: true,
        sparse: true,
        unique: true,
        autoValue: (com) => {
          if (com.shortName) {
            return com.shortName.toLowerCase();
          }
        }
      },
    });

I even tried to reset meteor. If I add a duplicate value, it won't add the record but won't even give any errors when validating.

**Comment by THPubs** [comment]
To add the item I use insert But before that I use the validate method to get the errors : `Collection.simpleSchema().namedContext('insertForm').validate(values)`. But looks like this method won't return uniqueness errors.

**Comment by MichaelJCole** [comment]
Have you looked at Collection2 when using SimpleSchema?

**Comment by aldeed** [comment]
Yes, `unique` validation is added by collection2, or specifically by https://github.com/aldeed/meteor-schema-index. It works by trying the operation in Mongo, and then converting the error that mongo throws into a SimpleSchema error. There's really no other way you could implement it.

**Comment by thesubr00t** [comment]
Hi @aldeed,

I installed [aldeed:meteor-collection2](https://github.com/aldeed/meteor-collection2) wich automatically install simple-schema & schema-index.

But still no validation for 'unique'

**Comment by Murukaen** [comment]
+1

**Comment by jtara1** [comment]
the fix for me was to install `simpl-schema` (npm package) and use that instead

`$ npm i --save simpl-schema`

`import SimpleSchema from 'simpl-schema';`

looks like this repo and meteor package is deprecated

**Comment by guidouil** [comment]
you guys should search the doc wisely ^_^
`meteor add aldeed:schema-index` 🚀
