### ISSUE TITLE
Updating Nested Array Object Element failing

### ISSUE THREAD

**Issue by Amritpd** [aldeed/meteor-simple-schema#608]
First of all thanks for providing amazing packages. However I'm having trouble updating a specific attribute of an object that is within a nested array. The simpleSchema, call-to-update and more details can be found here: http://stackoverflow.com/questions/37304090/updating-nested-array-element-failing 

The error I keep on getting over and over again is this: 

I20160518-12:22:50.969(-4)? Exception while invoking method 'addLoanAndTable' Error: Rate is required
I20160518-12:22:50.970(-4)?     at getErrorObject (packages/aldeed_collection2-core/lib/collection2.js:437:1)
I20160518-12:22:50.971(-4)?     at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:420:1)
I20160518-12:22:50.972(-4)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:173:1)
I20160518-12:22:50.972(-4)?     at [object Object].addTable (methods/addingLoans/addTable.js:27:31)
I20160518-12:22:50.969(-4)? rate: undefined
I20160518-12:22:50.972(-4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
I20160518-12:22:50.973(-4)?     at packages/ddp-server/livedata_server.js:1617:18
I20160518-12:22:50.973(-4)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160518-12:22:50.981(-4)?     at Server.apply (packages/ddp-server/livedata_server.js:1616:45)
I20160518-12:22:50.982(-4)?     at Server.call (packages/ddp-server/livedata_server.js:1559:17)
I20160518-12:22:50.982(-4)?     at [object Object].addLoanAndTable (methods/addingLoans/addLoanAndTable.js:38:26)
I20160518-12:22:50.982(-4)? Sanitized and reported to the client as: Rate is required [400]

I've tried updating all my packages to see if that would do anything. I have tried setting validate: false and $setting the entire object in the array instead of $setting the individual keys. What am I missing?

**Comment by aldeed** [comment]
Closing old issues but let me know if you never figured this out.
