### ISSUE TITLE
Use with typescript?

### ISSUE THREAD

**Issue by dagatsoin** [aldeed/meteor-simple-schema#610]
Hi, is there a definition file for it? In case not, what are the alternatives to use a mongo schema with typescript and meteor? Thx.

**Comment by dagatsoin** [comment]
sorry to bother but does anyone could help me on this?

**Comment by icereed** [comment]
Do you use Node-Modules? I've done a definition for Typescript. But not fully completed.

**Comment by dagatsoin** [comment]
Thx @icereed. Have you got a link to your .d file?

**Comment by scharf** [comment]
I added this in my `globals.d.ts`. It's not complete at all, but it makes the compiler happy...

```typescript
declare module SimpleSchemaModule {
    interface SimpleSchemaDefinition {
        [attribute: string]: {[props: string]: any}
    }
    export interface SimpleSchema {
        new(definition: SimpleSchemaDefinition): SimpleSchema;
        extendOptions(options: {[options: string]: any}): void;
        validate(object:any):void;
    }

}

declare module 'meteor/aldeed:simple-schema' {
    export var SimpleSchema:{
        new(definition: SimpleSchemaModule.SimpleSchemaDefinition):SimpleSchemaModule.SimpleSchema;
        RegEx: {
            Url: RegExp,
            Email: RegExp
        }
    };
}
```

**Comment by awatson1978** [comment]
@scharf  - Wait... does this export SimpleSchemas based on a typescript file?

**Comment by anjueappen** [comment]
A typings definition for SimpleSchema can be found [here](https://github.com/meteor-typings/simple-schema) 

And can be installed with 

`typings install github:meteor-typings/simple-schema --global`

Further typings definitions can be found at [meteor-typings](https://github.com/meteor-typings)
