### ISSUE TITLE
Validate a dictionary

### ISSUE THREAD

**Issue by namirsab** [aldeed/meteor-simple-schema#611]
Hello!
Is there anyway to validate a dictionary/hashmap just like we validate arrays?
something like this:
```javascript
const hashmap = {
    'randomKey': {},
    'randomKey2': {}
};
```

**Comment by namirsab** [comment]
#613 solves this

**Comment by aldeed** [comment]
Closing as duplicate of #244

**Comment by namirsab** [comment]
@aldeed i've already implemented it an its working. I'm using in production for some time and it's giving 0 problems. Would you at least consider the PR?

**Comment by aldeed** [comment]
@namirsab I did look at the PR and I'll take a closer look soon when I implement this in v2. There have been several competing suggestions for how to do this, and I'll need to decide which works the best. It might be your way. I don't think this will go into v1, though. I'm limiting v1 to fixes to encourage people to update to v2.

**Comment by namirsab** [comment]
@aldeed okey thanks for your message. I'll keep using my fork till you make it to v2! :smile:
