### ISSUE TITLE
Validation error doesn't share what field is causing error.

### ISSUE THREAD

**Issue by MichaelJCole** [aldeed/meteor-simple-schema#614]
Hi, this code is causing the error below, but it's kinda hard to debug from the error message. 

```
SomeCollection.update({ _id: someItem._id }, { $unset: 'someField' });
```

Error: 

```
TypeError: Cannot call method 'lastIndexOf' of null
    at [object Object].SimpleSchema.keyIsInBlackBox (packages/aldeed_simple-schema/simple-schema.js:856:1)
    at checkObj (packages/aldeed_simple-schema/simple-schema-validation.js:210:1)
    at packages/aldeed_simple-schema/simple-schema-validation.js:313:1
    at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
    at packages/aldeed_simple-schema/simple-schema-validation.js:305:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at checkModifier (packages/aldeed_simple-schema/simple-schema-validation.js:289:1)
    at doValidation1 (packages/aldeed_simple-schema/simple-schema-validation.js:321:1)
    at doValidation (packages/aldeed_simple-schema/simple-schema-context.js:9:1)
    at SimpleSchemaValidationContext.simpleSchemaValidationContextValidate [as validate] (packages/aldeed_simple-schema/simple-schema-context.js:44:1)
```

I have several "blackbox" fields in my schema like this, but someField in the update above is a string.

```
timers: { type: Object, blackbox: true, defaultValue: {}, },
```

It's happening in this code:

```
// Check if the key is a nested dot-syntax key inside of a blackbox object
SimpleSchema.prototype.keyIsInBlackBox = function(key) {
  var self = this;
  var parentPath = SimpleSchema._makeGeneric(key), lastDot, def;

  // Iterate the dot-syntax hierarchy until we find a key in our schema
  do {
    lastDot = parentPath.lastIndexOf('.');
    if (lastDot !== -1) {
      parentPath = parentPath.slice(0, lastDot); // Remove last path component
      def = self.getDefinition(parentPath);
    }
  } while (lastDot !== -1 && !def);

  return !!(def && def.blackbox);
};
```

**Comment by MichaelJCole** [comment]
Ok, looks like this appeared because I had the wrong syntax for the update:

```
SomeCollection.update({ _id: someItem._id }, { $unset: 'someField' });  // Bad day
```

```
SomeCollection.update({ _id: someItem._id }, { $unset: { someField: true } }); // Good day
```

But that doesn't really address the root cause.

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
