### ISSUE TITLE
Default value should not be passed as a reference.

### ISSUE THREAD

**Issue by theodorDiaconu** [aldeed/meteor-simple-schema#615]
## Issue story

Given a schema with an element that has a {something: {type: [String], defaultValue: []}}
Then I create a new object (obj1) without "something" field, and pass it to "clean" method in the schema instance.
Then I modify that object by doing: obj.something.push('somethingElse')
Then I create another object (obj2) without "something" field and pass it to "clean" method.
At this stage my obj2 should not have 'somethingElse' in it.

This took me about 2 hours to debug. And the problem is that defaultValue is passed by reference. Maybe we should use _.clone ?

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
