### ISSUE TITLE
Conditional Allowed Values

### ISSUE THREAD

**Issue by eliehamouche** [aldeed/meteor-simple-schema#617]
What's the best practice on dealing with dependencies between fields?

For example, I have a select field on my form for City, however the values would depend on the value of the Country selected.
Same thing with phone numbers and their format, they are dependent on the initial choice of country.

I've thought of storing all the rules in a .json file or collection and then use a function in allowed_values match a selected country to its allowed values.

Just wondering if anyone has any suggestions or best practices. # #

**Comment by ro6** [comment]
https://github.com/aldeed/meteor-simple-schema#make-a-field-conditionally-required
