### ISSUE TITLE
Use function to assign `optional` for field

### ISSUE THREAD

**Issue by brylie** [aldeed/meteor-simple-schema#618]
We would like to make a field required based on the value of another field. Custom validation is overly complicated, and we would like to write a simpler function that returns true if the field should be required or false if not. Is there a way to use a function for the value of `optional` wherein we could check the value from another field?

**Comment by bharathkeshav12** [comment]
This is mentioned in the documentation. 


Here is part of my code snippet making it work: I have a radio button where in I can select auth type as No Password and password. If password is selected, then password field becomes mandatory. Else it will be optional, meaning it can have empty string.

```
"type":{
        type: String,
        autoform:{
            type:"select-radio-inline",
            options: function (){
                return [
                    {label: "No Authentication", value: "null"},
                    {label: "Password Authentication", value: "password"}
                   ];
            },
            defaultValue: function () {
            return Defaults.find({"schemaName":"authentication_schema", "label":"type"},{value:1,_id:0}).map(function(c) {return c.value;})[0];
            }
        }
    },
    "password":{
        type: String,
        optional: true,
        custom: function (){
            var shouldBeRequired = this.field('type').value == "password";
            if (shouldBeRequired) {
        // inserts
                if (!this.operator) {
                    if (!this.isSet || this.value === null || this.value === "") return "passwordRequired";
                }
            }
        },
        autoform:{
            placeholder: "Password, 8 chars long",
            type: "password"
        }
```

**Comment by brylie** [comment]
Well, it relies on the custom validator, which, as stated, may be overly complex. 

> Note: In the future we could make this a bit simpler by allowing optional to be a function that returns true or false. Pull request welcome.

The idea is to allow the `optional` to take a function, wherein we can check the value of a second field and return `true` or `false` based on the value of the second field. Any ideas how we can do that?

**Comment by aldeed** [comment]
Can be a function in v2
