### ISSUE TITLE
AutoValue and isSet on an update?

### ISSUE THREAD

**Issue by mrlowe** [aldeed/meteor-simple-schema#620]
I think I may be doing something wrong, so I figured I'd ask. If this would be better asked on stackoverflow, I can do that too.

Suppose I have a schema with an autovalue that generates timestamps, like this:
```
createdAt: {
    type: Date,
    autoValue: function() {
        if (this.isSet) {
            return this.value;
        }
        return moment().toDate();
    }
}
```

And then I want to update a single field in that document using ```Collection.update()```, like so:
```
Things.update(id, { $set: {
    processedAt: moment().toDate()
}},
{
    selector: { type: thingType }
});
```

I think you can see the nasty thing that is going to happen. ```isSet``` is going to be false in the autoValue function, and the createdAt field in my Thing is going to get stomped on. But that behavior kind of surprised me. Do I just need to remember to always use ```getAutoValues : false``` any time I'm making an update that doesn't set all the fields on the document? Or is there a more graceful way to handle autoValue timestamps?

**Comment by mrlowe** [comment]
I think I can answer my own question now. Using getAutoValues is suboptimal, because I want my updated timestamps to still be set. Instead, I should check to see if the operation is Update, meaning the createdAt autoValue function should look more like this:
```
    autoValue: function() {
        if (this.isSet || this.isUpdate) {
            return this.value;
        }
        return moment().toDate();
    }
```

**Comment by CookeMoore** [comment]
Thank you for this.
