### ISSUE TITLE
Schema Not Defined

### ISSUE THREAD

**Issue by adamwan92** [aldeed/meteor-simple-schema#621]
After updating to Meteor 1.3.3, I've been getting this error: 

W20160616-14:24:47.342(8)? (STDERR)
W20160616-14:24:47.524(8)? (STDERR) /Users/adamwan/.meteor/packages/meteor-tool/.1.3.3.1fefzvf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160616-14:24:47.526(8)? (STDERR)             				throw(ex);
W20160616-14:24:47.526(8)? (STDERR)             				      ^
W20160616-14:24:47.726(8)? (STDERR) ReferenceError: Schema is not defined
W20160616-14:24:47.726(8)? (STDERR)     at meteorInstall.collections.Accounts.js (collections/Accounts.js:3:1)
W20160616-14:24:47.727(8)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160616-14:24:47.728(8)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160616-14:24:47.728(8)? (STDERR)     at /Users/adamwan/Desktop/SideQuest/sidequestweb/.meteor/local/build/programs/server/app/app.js:13209:1
W20160616-14:24:47.729(8)? (STDERR)     at /Users/adamwan/Desktop/SideQuest/sidequestweb/.meteor/local/build/programs/server/boot.js:291:10
W20160616-14:24:47.729(8)? (STDERR)     at Array.forEach (native)
W20160616-14:24:47.730(8)? (STDERR)     at Function._.each._.forEach (/Users/adamwan/.meteor/packages/meteor-tool/.1.3.3.1fefzvf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160616-14:24:47.730(8)? (STDERR)     at /Users/adamwan/Desktop/SideQuest/sidequestweb/.meteor/local/build/programs/server/boot.js:133:5

Please help!

**Comment by Cyval** [comment]
Same problem here. Just updated to Meteor 1.3.3 and I encountered this issue. I tried adding `const` to the schema but it blows up and throw another error, but that's another issue.

**Comment by adamwan92** [comment]
Alright so I managed to fix this by:
