### ISSUE TITLE
Clean is filtering out object properties incorrectly

### ISSUE THREAD

**Issue by s-devaney** [aldeed/meteor-simple-schema#626]
I have the following schema rules:

```
    "seasons.$.fixtures": {
        type: Array
    },

    "seasons.$.fixtures.$": {
        type: Array
    },

    "seasons.$.fixtures.$.$": {
        type: Object
    },  

    "seasons.$.fixtures.$.$.homeTeam": {
        type: String,
        regEx: SimpleSchema.RegEx.Id
    },

    "seasons.$.fixtures.$.$.awayTeam": {
        type: String,
        regEx: SimpleSchema.RegEx.Id
    },

    "seasons.$.fixtures.$.$.status": {
        type: Number,
        min: 0,
        max: 1
    }
```

When I run clean on an object with these properties they are filtered out with the following debug message:

`SimpleSchema.clean: filtered out value that would have affected key "seasons.$.fixtures.$.5.status", which is not allowed by the schema`

`fixtures":[[{},{},{},{},{},{}]`

The values in question:

```
"seasons": [{
    "fixtures": [
            [{
                "homeTeam": "Q3uJfiYFdXE2mFqZM",
                "awayTeam": "WH5jFsT3eYqqAwMiy",
                "status": 0
            }]
    ]
}]
```

**Comment by s-devaney** [comment]
By flattening my schema from Array -> Array -> Object to Array -> Object this problem was solved. It appears that SimpleSchema has problems with Arrays of Arrays of Objects...

**Comment by yanickrochon** [comment]
Then I get this behavior

```js
const schema = new SimpleSchema({
  'str': String,
  'arr': Array
});
const value = {
  str: 'Hello',
  arr: [ 'World', '!!!!' ]
};
const model = schema.clean(value);
// -> { str: 'Hello', arr: [] }
```

Why is the array cleared?

**Comment by s-devaney** [comment]
You need to specify the allowed values of the array using the $ operator.

So your schema needs this:
`
'arr.$': String
`

**Comment by yanickrochon** [comment]
Right. However, my first impression was that declaring a field as an array would not care about it's content, and using the `$` operator would explicitly define each array value types. Saying that a field is an array should allow for any element.

Oh well, if this is the behavior, I'll be declaring the array elements then.

**Comment by s-devaney** [comment]
You can add blackbox: true to the schema to allow any value
