### ISSUE TITLE
Generate blank document?

### ISSUE THREAD

**Issue by tdsfugal** [aldeed/meteor-simple-schema#628]
Is there an easy way to extract a minimal conforming "blank" document from Simple Schema?  If not, would anyone be interested in having such a capability?  

My sense is that 90% of the use cases involve objects with only simple fields - strings, integers, etc - that have natural default values ("" for String, minValue for Number, etc).  Having this capability in the schema would take a lot of boilerplate out of writing "insertBlankDocument" functions.  Would like to gage interest before investing a lot of time making it happen.

**Comment by aldeed** [comment]
Closing since this should be implemented as a separate package, but I've heard others request this so please post a link here if you do it.
