### ISSUE TITLE
Ability to use Math.random() in autovalue 

### ISSUE THREAD

**Issue by Neobii** [aldeed/meteor-simple-schema#629]
I have a collection that I would like to have a number re-randomized every time it's view count is incremented and it seems as though since the Math.random call is giving two different numbers on client and server it won't pass validation.

**Comment by aldeed** [comment]
It should be fine since autoValues on the client are only generated for validation purposes and are then "thrown away" before sending to the server (assuming you're talking about how collection2 package does it). So only the value generated on the server would be saved.
