### ISSUE TITLE
check Validating an Array Object

### ISSUE THREAD

**Issue by YouSour** [aldeed/meteor-simple-schema#631]
![ask](https://cloud.githubusercontent.com/assets/9318106/16651005/592a8190-446b-11e6-84da-a36a11b775ba.png)
hi , i want to check Validate that material is unique (can choose only one) when i click on save button , any idea ?

**Comment by aldeed** [comment]
If you're using collection2, it adds the `unique` index option, which will let Mongo handle uniqueness checks. This error makes its way back to the client and should show automatically if you're using autoform. If not autoform, then you'd have to handle the error yourself.

**Comment by YouSour** [comment]
thank you for reply :+1: , problem slove
