### ISSUE TITLE
[FEATURE] Linked Collection ID Validation

### ISSUE THREAD

**Issue by DerekTBrown** [aldeed/meteor-simple-schema#634]
I am working on a project which has several "linked collections"- that is, schemas which are to contain IDs to objects in other collections.  I already wrote a custom validator for this type, but it seems like this is something that other people would be interested in the long run.  Should I submit a pull request?

**Comment by DerekTBrown** [comment]
Also created an issue here, not realizing this is not the actual source:
https://github.com/aldeed/meteor-collection2/issues/333

**Comment by aldeed** [comment]
A standard way of defining joins in collection2 has been a goal for some time but I have never done it. I plan to publish a successor to collection2 which will work differently, so it might be better to wait and implement it there. Any help is welcome, though.
