### ISSUE TITLE
autoValue not working when you validate against mongodb collection fields

### ISSUE THREAD

**Issue by yushaUzumo** [aldeed/meteor-simple-schema#635]
I am trying to set a value using autoValue based on already stored values I am using meteor 1.3.4.1

This used to work in meteor 1.1.0.2

here is my code:

> id: { 
    type: String,
    label: "ID",
    autoValue: function() {
        var isFirstTime = this.field("profile.isFirstTime").value;
        var isApproved = this.field("profile.changesApproved").value; 
        var value = this.field("profile.unapproved_id").value;
        var userId = this.userId;
        var user = Meteor.users.findOne({_id: userId});
        if (user && user.profile && user.profile.id)
        {
            return user.profile.id;
        }
    }
}

I expect value of user.profile.id to be returned since user.profile.id has a value in the users collection but I get a value that is passed from input field. How do I get simple-schema to notice collection values as it used to on meteor 1.1.0.2

**Comment by aldeed** [comment]
Is this still something you need help with? Did you check whether `this.userId` is set? Can't debug this further unless you post the actual insert/update call you're making.
