### ISSUE TITLE
Strange behavior when updating nested objects

### ISSUE THREAD

**Issue by lvnr** [aldeed/meteor-simple-schema#637]
For some reason update operations on a nested object that has numbers as its keys executes with no errors, but doesn't affect any data.

Let's say you have a document like this:

```
{
  total: 0,
  data: {
    '0': 0,
    'test': 0
  }
}
```

So, when I am running the following command:

```
Collection.update(
  { _id: someId },
  { $inc: { total: 1, 'data.test': 1, 'data.0': 1 } }
)
```

Both `total` and `data.test` values get incremented, but `data.0` doesn't.

This works ok when I remove the schema attached to the collection.

In my schema the object is specified with `blackbox: true`

```
data: {
  type: Object,
  blackbox: true
}
```

**Comment by aldeed** [comment]
Can you skip filtering and see if that fixes it?

```js
Collection.update(
  { _id: someId },
  { $inc: { total: 1, 'data.test': 1, 'data.0': 1 } },
  { filter: false }
)
```

**Comment by nidem** [comment]
I've encountered the same issue. When I use `filter: false` the update works just fine.

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
