### ISSUE TITLE
Error messages are piece of crap

### ISSUE THREAD

**Issue by gooor** [aldeed/meteor-simple-schema#639]
Is there any chance to set it more friendly for developer to find source of error? I'm asking because  getting just "SomeField is required [400]" is nothing - I don't know on which collection, I'm not updating any "SomeField" field. Really it gets me more trouble to use it than not to use it :|

Edit:
I found source `... 'someUpperFIeld:someField': { ... } ...` - while also have `someField: { ... }` instead of changing `someUpperField.someField` to `SomeField` it should leave just `someUpperField.someField` if there's no label. Seriously this would help me a bit. And also add collection name.

**Comment by aldeed** [comment]
I can look into it, but this would probably be something to add in the collection2 package.

**Comment by d4nyll** [comment]
@gooor Regarding the title of this post - "Error messages are piece of crap" - I'd advise you to read this article - [Dear JavaScript](https://medium.com/@thejameskyle/dear-javascript-7e14ffcae36c#.7fxjqrf2t)

Your tone is unhelpful, rude, and we need less complaints and more support in our community. If you create something of substance and people say "that bit is a piece of crap", maybe you'll think about your choice of words more wisely.

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
