### ISSUE TITLE
Empty string as acceptable value on non-optional field?

### ISSUE THREAD

**Issue by noahadler** [aldeed/meteor-simple-schema#64]
What is the correct way to allow an empty string ('') to validate?  I haven't marked this field as optional, but I set min to 0.  I'd expect it to reject my insert if I passed null, undefined, or omitted the field entirely, but it seems to also reject an empty string.  Is this by design?  For certain applications, might it make sense to allow empty string as an acceptable value?  I'm willing to try to work around this, but wanted to be sure it's a design decision that I can learn, and not a bug.  Thanks!

**Comment by green-coder** [comment]
I ran into the same corner case, where I have a non-optional string which is allowed to be empty.

Polite complain +1.
