### ISSUE TITLE
Validation error silently swallowed when used within publish function

### ISSUE THREAD

**Issue by serkandurusoy** [aldeed/meteor-simple-schema#641]
Given a publish function:

``` js
Meteor.publish('hello', function(name) {
  new SimpleSchema({name: {type: String, min: 5}}).validate({name})
  return Names.find({name});
});
```

Subscribing with:

``` js
Meteor.subscribe('hello', 'x');
```

I would expect to see an error on the server console just like I do with `check` but I see nothing. The function simply does not publish anything and that's it, making it hard to debug publications.

PS: I cross posted this over at the validated-method tracker on [issue 15](https://github.com/meteor/validation-error/issues/15)

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
