### ISSUE TITLE
Collection object in autoValue

### ISSUE THREAD

**Issue by andresespinosapc** [aldeed/meteor-simple-schema#643]
I'm trying to set the initial owner of an object using autoValue, but I get a validation error because of the publish/subscribe functionality. Here's the relavant part of my schema's code:

```javascript
owners: {
    type: Array,
    autoValue: function() {
        if (this.userId) {
            return [Meteor.users.findOne(this.userId)];
        }
        else {
            this.unset();
        }
    }
},
'owners.$': {
    type: UserSchema
}
```

The problem is that it only gets user data that is published, obviously not the whole User object, so my UserSchema throws an error on missing fields.

Please correct me if I'm wrong, but I think that if I query the database in the server-side I should get the whole object, so the error I'm getting should be client-side. Is there a way of skipping just the owners field validation and only in client-side? Any other solution to my problem will be happily received :)

**Comment by aldeed** [comment]
You can skip client side validation (for the whole doc, not just that one field), by adding `validate: false` to your insert or update call in client code. The server-side validation won't be skipped so you'd still get any errors back on the client after it makes a trip to the server.
