### ISSUE TITLE
autoValue is not set for optional fields

### ISSUE THREAD

**Issue by obiwarn** [aldeed/meteor-simple-schema#647]
my auto value func gets called when the field is optional: true but the value is not set.

**Comment by aldeed** [comment]
Can't debug this without more reproduction code to look at

**Comment by obiwarn** [comment]
@aldeed: sorry for beeing so unclear

I introduced a new field "lastDeactivatedAt" to an existing collection.
When the field "active" is set to false it should get a timestamp.
The autovalue func runs but does not set change the vaule of the field.

lastDeactivatedAt: {
    type: Date,
    optional: true,
    autoValue: function() {
      var activeField;
      activeField = this.field("active");
      if (activeField.isSet && activeField.value === false) {
        return new Date();
      } else {
        return new Date(0);
      }
    }
  }

**Comment by aldeed** [comment]
@obiwarn can you post the context for this? What insert or update are you doing that is not properly setting the value?

**Comment by obiwarn** [comment]
I use this with yogiben:admin.

When I open the document view there it uses autoform for the UI. 
Above code works fine when I remove the 

    optional: true,

 I uncheck the "active" checkbox and the autovalue calculates my new "lastDeactivatedAt".

The moment I make "lastDeactivatedAt" optional it does not work anymore.

**Comment by aldeed** [comment]
This sounds like maybe a yogiben:admin issue. Autovalue isn't really meant to be used for this purpose.
