### ISSUE TITLE
Add getDefaultValue(key) that gets the value not the reference

### ISSUE THREAD

**Issue by merlinpatt** [aldeed/meteor-simple-schema#648]
I would like to be able to quickly get the default value of an object so I can use it in my code. I know that currently I can get default values by doing `SomeSchema.schema().key.defaultValue`. But this poses one major problem and one minor problem
1. It's passed by reference which doesn't work for arrays and objects.
2. It feels slightly lengthy at times.

Ideally the solution would look like `SomeSchema.getDefault(key)` and would pass only the value back, not the reference.

**Comment by aldeed** [comment]
The main problem here is that there isn't really such a thing as `defaultValue`. If you provide it, it is transformed into an `autoValue` function while constructing the schema instance. Maybe there is some way to rearchitect or some different way default values could be handled internally.

**Comment by aldeed** [comment]
Closing. This function exists in the NPM package
