### ISSUE TITLE
Telescope-Nova - Positional projection does not match the query document

### ISSUE THREAD

**Issue by abhaytalreja** [aldeed/meteor-simple-schema#651]
In Nova, can't we not have an array of objects in the schema? something like..

```
/**
 * castElements schema
 * @type {SimpleSchema}
 */
Telescope.schemas.castElements = new SimpleSchema({
  celeb: {
    type: String,
    optional: true,
    publish: true,
  },
  castedAs: {
    type: String,
    optional: true,
    publish: true,
  }
});

...
  cast: {
    type: [Telescope.schemas.castElements],
    publish: true,
    optional: true,
  },
```

I am getting the exception `posts.single :  Positional projection 'cast.$.celeb' does not match the query document.` on subscription.
am i missing something or i need to change my schema?

**Comment by aldeed** [comment]
This is a MongoDB error, so I don't think it has anything to do with your schema. It's that your `update` call isn't formatted correctly.
