### ISSUE TITLE
The 'autoValue' property runs multiple times.

### ISSUE THREAD

**Issue by jpmelnik** [aldeed/meteor-simple-schema#655]
For some reason when I call 'insert' or 'update' the autoValue property has multiple executions.

I'm using something like:

`// ValidatedMethod => validate() =>`

```
App.Schema.get('User').clean(user, {
        extendAutoValueContext: {  isInsert: true  }
});
```

`//App.Schema.get('User').validate(user);`

Schema:

```

createdAt: {
    type: Date,
    autoValue : function() {
      if(this.isInsert) {
        console.log('createdAt');
        return new Date();
      }
      this.unset();
    }
  }
```

`Users.insert(user, { validate: false });`

**Comment by aldeed** [comment]
If this is on the client, then this is probably what was fixed recently in [collection2-core@2.0.2](https://github.com/aldeed/meteor-collection2-core/blob/master/CHANGELOG.md#202)
