### ISSUE TITLE
Extend simple Schema.

### ISSUE THREAD

**Issue by sadanandGithub123** [aldeed/meteor-simple-schema#657]
Hi,
Can i extend simple schema on run time ?
I have created a collection, which is attached with simple schema . that i am using in autoform also.
now i want to update simple schema(want to add some new properties/fields) on the fly and it should reflect on autoform as well, is it possible .if yes then how?
I already tried attachSchema function at runtime which never worked. please suggest me a solution.

**Comment by aldeed** [comment]
In v2, this is possible: https://github.com/aldeed/node-simple-schema#extending-schemas
