### ISSUE TITLE
Support Mongo 3.2 Document Validation natively

### ISSUE THREAD

**Issue by MentalGear** [aldeed/meteor-simple-schema#660]
Would it make sense to use the native document validation (for possible speed gains) when the package detects that MongoDB 3.2 is used ?

https://docs.mongodb.com/manual/core/document-validation/

**Comment by aldeed** [comment]
SimpleSchema isn't database-aware, so this would have to be an enhancement done by some package that uses SimpleSchema, such as collection2.
