### ISSUE TITLE
Unwanted combine of $setOnInsert and $set during validate()

### ISSUE THREAD

**Issue by imajus** [aldeed/meteor-simple-schema#666]
Case:

``` es6
const modifier = { $set: { a: 'a' }, $setOnInsert: { b: 'c' } };
new SimpleSchema({ 
  a: { type: String }, 
  b: { type: String }
}).validate(modifier, { modifier: true, upsert: true });
console.log(modifier);
// After that I'm going to use collection upsert
```

Output:

``` es6
{ '$set': { a: 'a', b: 'c' } }
```

Expected:

``` es6
{ '$set': { a: 'a' }, '$setOnInsert': { b: 'c' } }
```

**Comment by cpury** [comment]
+1, this is breaking our stuff. Was this newly introduced?

Can be easily avoided though by passing it a clone of the modifier instead of the original.

**Comment by aldeed** [comment]
There is some code that combines them at one point in order to validate properly, but it may not be deep cloning properly. I think this is fixed in the npm package, but will verify before closing.

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
