### ISSUE TITLE
Impossible to use $pull operator with array member properties.

### ISSUE THREAD

**Issue by SzybkiSasza** [aldeed/meteor-simple-schema#667]
I'm trying to write simple update script to pull the element from the array based on one of its properties:

```
collection.update({
            _id: 'someId'
        }, {
            $pull: {
              property: {
                _id: 'someInternalId'
              }
            }
        }, {
            multi: true
        });

```

Schema is as easy as it could get:

```
InternalObject: {
   _id: {
    type: String,
    optional: true
  }
  anotherProperty: {
    type: String,
    optional: true
  }
}

// Another properties of the schema

property: {
   type: [InternalObject],
   optional: true
}
```

I tried both with dot notation in `$pull`, with different ways of selecting the properties and every time I get one of those two errors: 
`Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation in field $pull`
Or directly from simpleSchema sanitizer: 
`SimpleSchema.clean: filtered out value that would have affected key "property._id", which is not allowed by the schema`
Or:
`SimpleSchema.clean: filtered out value that would have affected key "property.$._id.$", which is not allowed by the schema`

For me it seems like something is going wrong in SimpleSchema itself, as I am getting perfect results using exactly the same selectors directly with MongoDB and schema for this property is very simple.

**Comment by thiagodelgado111** [comment]
Maybe this other issue can help you: https://github.com/aldeed/meteor-collection2/issues/245.

**Comment by Paku-** [comment]
Any solution as of end of 2017 ??

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
