### ISSUE TITLE
simple-schema compound

### ISSUE THREAD

**Issue by dannicus** [aldeed/meteor-simple-schema#669]
```
photosInformation = new SimpleSchema({
    gallery : {
      type : [String],
      label : "arreglo con direcciones url de imagenes"
    },
    profile_picture : {
      type : String,
      label : "direccion url de la imagen de perfil"
    }
});

profileInformation =  new SimpleSchema({
    name : {
      type : String,
      label : "name",
      max: 30
    },
    description : {
      type : String,
      label : "description",
      max : 250
    },
    industry : {
      type : String,
      label : "industria a la cual pertenece",
      max: 20 
    },
    url_website : {
      type : String,
      label : "url de la organizacion",
      max : 30
    },
    country : {
      type : String,
      label : "pais al cual pertenece",
      max : 20
    }
});

contactInformation = new SimpleSchema({
  phone : {
    type : Number, 
    label : "numero telefonico",
    max : 5699999999,
    optional: true
  },
  email : {
    type : String, 
    label : "email",
    max : 40,
    optional: true
  },
  address : {
    type : String,
    label : "direccion",
    max : 50,
    optional: true
  }
});

Organizations.attachSchema( new SimpleSchema({
  _id : {
    type : String,
    label: 'id',
    max: 20
  },
  url : {
    type : String,
    label: 'url personalizable',
    max : 30
  },
  profile : {
    type : profileInformation,
    label : 'informacion del profile'
  },
  contact : {
    type : contactInformation,
    label : 'informacion de contacto',
    optional: true
  },
  photos : {
    type : photosInformation,
    label : 'fotos',
    optional: true
  }
}));
```
Hi, I have a simple-schema compound and have problems when implemented a Factory.create. it's saying 'informacion del profile' is required.

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
