### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by jvella61** [aldeed/meteor-simple-schema#683]
I have done an "npm install --save simpl-schema" in my project and npm shows a successful installation of "simpl-schema@0.1.1"
The documentation talks about release of "Version 2".
Can you explain the difference in the versions numbers?
Thanks.

**Comment by aldeed** [comment]
"Version 2" switched from being a Meteor package to being a non-Meteor-specific JavaScript package on NPM. It is v2 in that it is a major rewrite with breaking changes, but I restarted the actual numbers since it's really an entirely new package.

**Comment by jvella61** [comment]
Thanks
