### ISSUE TITLE
Feature request: uniqueValues & allowedValues for array fields

### ISSUE THREAD

**Issue by fabyeah** [aldeed/meteor-simple-schema#688]
It would be nice, if the schema could validate whether all values in a given array are unique and there are no duplicates. So you don't have check it with underscore additionally.

Also if allowedValues were possible for array fields, too. So the given array must be the same or a subset of the allowedValues array.

**Comment by aldeed** [comment]
uniqueValues: The main problem is that it could not guarantee uniqueness if validating a modifier (e.g., $push validation does not know what values already exist that might be the same as what is being pushed). But it could be implemented with that caveat.

allowedValues for array: You can already do allowedValues for the array item definition (`myArray.$`) so wouldn't that be enough?

**Comment by fabyeah** [comment]
uniqueValues: I see. I'd be fine with it just working for $set.

allowedValues: Isn't myArray.$ only used for an array of objects? I have an array of strings. Or do you mean to say it's possible to have

```
myArray.$: {
    type: String,
    allowedValues: arrayVariable,
}
```

**Comment by aldeed** [comment]
@fabyeah Yes, that is what I mean

**Comment by fabyeah** [comment]
OK, great. Thanks for clearing that up.
