### ISSUE TITLE
How to add 2dsphere Index

### ISSUE THREAD

**Issue by BearandYoon** [aldeed/meteor-simple-schema#691]
I have to geoNear query on mongodb so, I added 2dsphere index in following way:

location: {
    type: 'Point',
    coordinates: [Number],
    index: '2dsphere',
    optional: true
  }

This is how I defined location field but I got following error

W20170308-13:05:03.448(2)? (STDERR) Error: Invalid definition for location field.
W20170308-13:05:03.448(2)? (STDERR)     at packages/aldeed_simple-schema.js:1429:13
W20170308-13:05:03.449(2)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:147:22)
W20170308-13:05:03.449(2)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed_simple-schema.js:1426:5)
W20170308-13:05:03.450(2)? (STDERR)     at meteorInstall.imports.api.users.users.js (imports/api/users/users.js:28:16)
W20170308-13:05:03.450(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170308-13:05:03.451(2)? (STDERR)     at Module.require (packages/modules-runtime.js:111:16)
W20170308-13:05:03.451(2)? (STDERR)     at Module.Mp.import (/Users/mac/.meteor/packages/modules/.0.7.7.1b1w7yl++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
W20170308-13:05:03.452(2)? (STDERR)     at meteorInstall.imports.api.quote-requests.server.publications.js (imports/api/quote-requests/server/publications.js:1:1)
W20170308-13:05:03.453(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:188:9)
W20170308-13:05:03.453(2)? (STDERR)     at Module.require (packages/modules-runtime.js:111:16)

**Comment by aldeed** [comment]
`index` feature is provided by https://github.com/aldeed/meteor-schema-index package so please submit this issue there instead. 2dsphere is not a supported type so this would be an enhancement request.

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
