### ISSUE TITLE
TypeError: Cannot read property '_schema' of undefined

### ISSUE THREAD

**Issue by prasanth-cubettech** [aldeed/meteor-simple-schema#701]
When I compile SimpleSchema object in meteor mongo collection file. I'm getting errors contain _schema of undefined.
`Roles.Schema = new SimpleSchema({
  name: {
    type: String
  },
  name: {
    type: String
  },
  code: {
    type: String
  },
  permissions: {
    type: []
  },
  active: {
    type: Boolean
  },
  createdAt: {
    type: Date
  },
  updatedAt: {
    type: Date
  }
});`

Error:

`TypeError: Cannot read property '_schema' of undefined
W20170522-15:39:55.898(5.5)? (STDERR)     at packages/aldeed_simple-schema.js:1066:16
W20170522-15:39:55.898(5.5)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:147:22)
W20170522-15:39:55.898(5.5)? (STDERR)     at expandSchema (packages/aldeed_simple-schema.js:1049:5)
W20170522-15:39:55.899(5.5)? (STDERR)     at packages/aldeed_simple-schema.js:1190:32
W20170522-15:39:55.899(5.5)? (STDERR)     at Array.forEach (native)
W20170522-15:39:55.899(5.5)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:139:11)
W20170522-15:39:55.899(5.5)? (STDERR)     at mergeSchemas (packages/aldeed_simple-schema.js:1183:5)
W20170522-15:39:55.899(5.5)? (STDERR)     at [object Object].SimpleSchema (packages/aldeed_simple-schema.js:1406:18)
W20170522-15:39:55.899(5.5)? (STDERR)     at meteorInstall.imports.api.users.roles.js (imports/api/users/roles.js:31:13)
W20170522-15:39:55.899(5.5)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)`

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
