### ISSUE TITLE
Decimal property not working as expected

### ISSUE THREAD

**Issue by jpmelnik** [aldeed/meteor-simple-schema#702]
I've the following field in my Schema and I'm getting an error: 

> "Error: Invalid definition for minimumPaymentDue field: "decimal" is not a supported property"

The documenation says:

> Set to true if type is Number or [Number] and you want to allow non-integers. The default is false.

```
/**
   * The minimum payment required at this time.
   * [Review]
   */
  minimumPaymentDue: {
    type: Number, 
    optional: true,
    decimal: true
  },
```

**Comment by mgscreativa** [comment]
Hi! how did you solve this?

**Comment by jpmelnik** [comment]
I make a mistake. I confused with Meteor Simple Schema with Node Simple Schema.
Meteor Simple Schema use decimal: true.
Node Simple Schema use type: Number and SimpleSchema.Integer

**Comment by q71710** [comment]
> I make a mistake. I confused Meteor Simple Schema package with Node Simple Schema.
Meteor Simple Schema use decimal: true.
Node Simple Schema use type: Number and SimpleSchema.Integer

How to do that?
This is my problem, is anyone help me?
https://gist.github.com/q71710/4b00e12963a488938e7f21279182cdba
