### ISSUE TITLE
How does this.isSet in custom validation behave?

### ISSUE THREAD

**Issue by luixal** [aldeed/meteor-simple-schema#704]
Hi, I'm facing something kind of weird...

I have this definition for a field inside a schema: 

```javascript
pin: {
    type: Number,
    label: function() { return I18N.translate('employee_pin'); },
    optional: true,
    custom: function() {
      
      if (Meteor.isClient && this.isSet) {
        console.log(this); // --> this gets fired ALWAYS!!!
        if ( (this.value <= 0) || (this.value >= 100000000) ) {
          Employees.simpleSchema().namedContext("modalForm").addInvalidKeys([{name: "pin", type: "outOfRange"}]);
          return 'outOfRange';
        }
        Meteor.call(
          'getEmployeeByPIN', Meteor.user().currentProjectId, this.value,
          function(error, result) {
            if (result) {
              Employees.simpleSchema().namedContext("modalForm").addInvalidKeys([{name: "pin", type: "notUnique"}]);
              return 'notUnique';
            }
          }
        );
      }
    }
  },
```

that console logs shows this object:

```javascript
...
docId: "6QQTMm7CrQx7MdeAM"
genericKey: "pin"
isFromTrustedCode: false
isInsert: false
isLocalCollection: false
isSet: true
isUpdate: true
isUpsert: false
key: "pin"
operator: "$unset"
userId: "4dy58r789bBqYKky6"
value: ""
```

this happens when updating a doc using AutoForm's quickform.

Any idea why `isSet` is set to `true` if field is not being filled in? It's madness.

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
