### ISSUE TITLE
removeEmptyStrings doesn't work

### ISSUE THREAD

**Issue by zhe1ka** [aldeed/meteor-simple-schema#705]
Hi,
I've some problem when I want to save my object with an empty value of a field.
I try to use "removeEmptyStrings", but it doesn't help me. I really don't know what I should do to fix it.

My code
```
const CompaniesSchema = new SimpleSchema({
    name: {
        type: String,
        defaultValue: ''
    }
}

CompaniesSchema.clean({
    removeEmptyStrings: false
});

const Companies = new Mongo.Collection('Companies');
Companies.attachSchema(CompaniesSchema);

========

Companies.update({ userId: this.userId }, {
    $set: {
        name: '',
    }
})

Exception while invoking method 'saveProfileCompany' Error: Name is required
```

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
