### ISSUE TITLE
decimal: true forces 2 decimal places

### ISSUE THREAD

**Issue by stephentcannon** [aldeed/meteor-simple-schema#71]
Decimal forces 2 decimal places on validation logic.  This restricts usage to usage specific to 2 decimal place use cases.  Suppose one was going to use this for forex or another purpose that is similar.

**Comment by serkyen** [comment]
I have done this and am using decimals but whenever I insert a decimal ending with 0, it omits the 0. 
For example, I enter 2.30, and then if I check the field in mongodb it shows up as 2.3
Is there any way to keep the 0 ?

HTML
```
<div class="form-group {{#if afFieldIsInvalid name='cost'}} has-error{{/if}}" data-required="true">
          <label class="control-label" for="cost">Cost</label>
          <div class="input-group">
            <div class="input-group-addon">$</div>{{> afFieldInput name='cost'}}
          </div>
          <span class="help-block">{{#if afFieldIsInvalid name='cost'}}{{afFieldMessage name='cost'}}{{/if}}</span>
        </div>
```

JS
```javascript
cost: {
    type: Number,
    decimal: true,
    label: "Cost"
  }
```

Thanks

**Comment by cheesington** [comment]
This is an old issue, but I ran into it today myself.  Just for those other few who may come looking, I found that adding `autoform { step: 0.00001 },` to my schema solved the problem, even when the number field in question was buried in an array (and rendered in an ArrayField).

**Comment by cheesington** [comment]
This is an old issue, but I ran into it today myself.  Just for those other few who may come looking, I found that adding `autoform { step: 0.00001 },` to the number field in my schema solved the problem, even when it was buried in an array (and therefore rendered in an ArrayField).

**Comment by krishaamer** [comment]
Thanks @cheesington, this helped me to get yogiben:admin working with GPS locations!
