### ISSUE TITLE
exception thrown when pick schema

### ISSUE THREAD

**Issue by veyronfei** [aldeed/meteor-simple-schema#713]
```
code 1. ASchema = new SimpleSchema([{
  a: {
    type: String,
    custom: function() {},
  }
}]);

code 2. BSchema = ASchema.pick(['a']);
```
Because I don't need custom in BSchema, so I add a line:
```
code 3. BSchema._schema.a.custom = undefined;
```
But the following code4 will throw exception
```
code 4. CSchema = BSchema.pick(['a']);
```
Error: Invalid definition for a field.

But if I put code 3 below code 4, everything works fine.

May I ask why it throws an exception? and what is the best way to do code 3?

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
