### ISSUE TITLE
AutoValue Doesn't Run On Server

### ISSUE THREAD

**Issue by mokaid** [aldeed/meteor-simple-schema#717]
Hello Guys, 

I don't know what is going on what the AutoValue 
A simple schema file is in common between the server and the client 
I have autovalue where it runs twice on the client side only and nothing on the server 

---> autovalue {
            if(Meteor.isServer)
                console.log('server')
                if(Meteor.isClient)
                    console.log('client')
}
result : client , client 

Am i missing anything or this is a normal behavior of the autovalue, please advice

**Comment by aldeed** [comment]
This was most likely fixed in [collection2-core@2.0.2](https://github.com/aldeed/meteor-collection2-core/blob/master/CHANGELOG.md#202)
