### ISSUE TITLE
notUnique doesn't work in simple schema messages

### ISSUE THREAD

**Issue by stephentcannon** [aldeed/meteor-simple-schema#72]
Collection2 mentions this

The error message for this is very generic. It's best to define your own using MyCollection.simpleSchema().messages(). The error type string is "notUnique".

SimpleSchema docs don't mention it.
https://github.com/aldeed/meteor-simple-schema#customizing-validation-messages

Cannot seem to get it to work with Collection2, SimpleSchema, Autoform

```
Cards = new Meteor.Collection('cards', {
  schema: {
    card: {
      type: String,
      min: 4,
      max: 100,
      unique: true
    },
});
```

and tried with various ways...

```
Cards.simpleSchema().messages({
  notUnique: '[label] must be unique.',
});
```

and

```
SimpleSchema.messages({
  notUnique: '[label] must be unique.',
});
```

any ideas?

**Comment by sunstorymvp** [comment]
I can't figure out how it works. I'im using
```
Categories.attachSchema new SimpleSchema
  name: 
    type: String
    unique: true
...

Categories.simpleSchema().messages
  notUnique: "NOT UNIQ"
```

and field ```name``` is published to the client, error message defaults to 'Internal server error' on client, and 'MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index' on the server console

**Comment by luckyyang** [comment]
@sunstorymvp I have the same problem:

```
Exception while invoking method 'addClub' MongoError: insertDocument :: caused by :: 
11000 E11000 duplicate key error index: meteor.clubs.$c2_name  dup key: { : "fdsf" }
```

**Comment by Taakn** [comment]
@luckyyang I am getting the same error... Let me know if you found a fix.

Thanks so much
