### ISSUE TITLE
Make a field conditionally required bug

### ISSUE THREAD

**Issue by vfonic** [aldeed/meteor-simple-schema#724]
I haven't tested this, but I believe there could be a bug in the code example in Readme documentation:
https://github.com/aldeed/meteor-simple-schema#make-a-field-conditionally-required

Specifically this line:
` if (this.operator === "$set" && this.value === null || this.value === "") return "required";`

I assume the correct line of code would be:
` if (this.operator === "$set" && (this.value === null || this.value === "")) return "required";`

The issue is that `&&` operator executes before `||` operator so `this.value === ""`  doesn't depend on `this.operator === "$set"`. If this is intended, perhaps it should be elaborated or surrounded by parenthesis (even though you might argue that those parenthesis are redundant).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
