### ISSUE TITLE
1.6.2 Has removed Deps from Tracker package

### ISSUE THREAD

**Issue by tcastelli** [aldeed/meteor-simple-schema#730]
This core commit meteor/meteor#9611 breaks this package. Any chance to get a critical update to make this package to work on 1.6.2?

Thanks

**Comment by aldeed** [comment]
@tcastelli Try 1.5.4

**Comment by tcastelli** [comment]
Thanks a lot! :)
The migration progress to the npm variant wasn't that easy when we tried it (middle size project), so we stayed on the old version until we have more time. It is definitely on the TODO list :)

**Comment by aldeed** [comment]
@tcastelli Totally understandable, but there are probably 50+ fixes and performance improvements that are only in the npm pkg at this point, if that helps you (or anyone else reading this) justify the time and difficulty. The Meteor pkg is intentionally getting only the minimum love necessary to keep it functioning.

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
