### ISSUE TITLE
"must be an object" error even though typeof() returns Object

### ISSUE THREAD

**Issue by andregoldstein** [aldeed/meteor-simple-schema#734]
Hi there, I've seen a few more historic issues relating to Object errors but I'm running into an issue where I'm trying in insert a basic Object not an array of Objects as below:

```
ProductItemschema = new SimpleSchema({

  animalId:
    type: String
  
  animal:
    type: Object
    blackbox: true

})
```

I'm passing in `animal` which is a direct call from a `findOne()` query but this doesn't seem to be passing validation. Would you have any possible pointers? Thanks

**Comment by andregoldstein** [comment]
Update:

I think I've tracked it down, I think because the findOne object is returning a multi-dimensional object, when I test with a single-level Object, it seems to pass. I don't actually need that depth so I'll transform the object before validation.

Though not sure if `blackbox: true` is supposed to allow this. Thanks

**Comment by andregoldstein** [comment]
Hmm actually, it appears to be returning a `Document` object (sorry about the trail here)

```
Document {
  _id: ...
}
```

**Comment by aldeed** [comment]
The Meteor SimpleSchema package is no longer maintained other than critical fixes to keep it running with each latest Meteor release. Closing non-critical issues in this repo. Anyone who cares about this may do one or more of the following:

- Switch to the [NPM package](https://github.com/aldeed/simple-schema-js). Be sure to adjust for the [breaking changes](https://github.com/aldeed/meteor-simple-schema/blob/master/CHANGELOG.md#200). There can be a lot of work involved in switching, but it is worth the effort.
- If this issue still occurs in the NPM package, [submit an issue there](https://github.com/aldeed/simple-schema-js/issues). Be sure to include a link to a reproduction repo or a PR that adds a failing test for the issue.
- If you have more time than money, submit a pull request to resolve any [issue labeled "help wanted"](https://github.com/aldeed/simple-schema-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) in the NPM package repo.
- If you have more money than time, [donate](https://opencollective.com/simple-schema-js/donate) to help support development if you are able
