### ISSUE TITLE
Make SimpleSchema custom() function reactive

### ISSUE THREAD

**Issue by wI2L** [aldeed/meteor-simple-schema#86]
Hi aldeed.

I am currently using the <code>custom()</code> function of <code>SimpleSchema</code> to add a custom validation for many fields of my forms.
Basically, i want to add a custom verification to check if a username is available : 

```
    username: {
        type: String,
        regEx: /^[a-z0-9A-Z_]{3,15}$/,
        label: "Username",

        // custom validation for username availability

        custom: function () {
            Meteor.call('accountsIsUsernameAvailable', this.value, function (error, result) {
                if (!result)
                    Session.set("usernameAvailability", "usernameNotAvailable");
                else
                    Session.remove("usernameAvailability");
            });
            return (Session.get("usernameAvailability"));
        }
    }
```

I am using a method of course because i obviously dont want to publish all the usernames of my database to the client. Because i want a result from these method, i set a callback and the method run asynchronously, and this is where is my issue.

To be sure that i will actually return a result from <code>custom()</code>, u can see in the code example above that i use <code>Session</code> as a reactive data source to make sure the custom function will return the result a soon as it arrive. In fact, there is two return for each excecution of <code>custom()</code>, but i don't really care.

What i would like to propose, is a way to avoid the use of <code>Session</code>. I prefer in every case to limit the use of <code>Session</code> to do not polluate the namespace.
I just wrote my code with <code>Session</code> to test the method inside <code>custom()</code>, but now i am gonna to write my own reactive data source for this purpose, according this tutorial : https://www.eventedmind.com/feed/meteor-build-a-reactive-data-source.

I am wondering if it would be possible to implement such a thing in <code>SimpleSchema</code> <code>custom()</code> function ? I don't know how it work internally in <code>SimpleSchema</code>, but i guess you are invalidating a field based on the return of <code>custom()</code>. Would it be possible to offer a property <code>this.result</code> inside <code>custom()</code>, let the user fill it with the same way (non-string for success -- string for error) and track this with a <code>Deps.Dependency</code>. Then on the change of this property, do the invalidation methodology inside <code>SimpleSchema</code>.

I am maybe wrong about this, if so, forgive me, i'm just sharing my thought because i was thinking of that when i was writting my code.

Regards,

William

---

<bold>EDIT:</bold> I don't think that the context of <code>custom()</code> would be available in the <code>Meteor.Method</code> that have to set the <code>this.result</code> property, but maybe using <code>_.bind</code> would be helpfull in this case, and solve the problem of accessibility.

**Comment by thearabbit** [comment]
Excuse me, we should return what for the `result`
```js
// In doc
.........
if(!result){
...........
}

// this
if(err){
...........
}
```
which one and `result` value for return?
don't work for me.

**Comment by thearabbit** [comment]
I have problem with `onSuccess Hook`, it run before `custom validate`
