### ISSUE TITLE
Support Additional Update Operators

### ISSUE THREAD

**Issue by aldeed** [aldeed/meteor-simple-schema#9]
This is to track progress adding support for additional update operators beyond `$set` and `$unset`.

The following operators need to be parsed and understood (but not necessarily validated) by the validation and cleanup functions in simple-schema:
- [x] $setOnInsert (treat this just like $set, merge contents with contents of $set)
- [x] $rename
- [x] $inc
- [x] $addToSet
- [x] $push
- [x] $pushAll (deprecated but might still work?)
- [x] $pull
- [x] $pullAll
- [x] $pop
- [x] $each (used with $push or $addToSet; probably remove the $each and treat like setting directly)
- [x] $slice

The following operators need to be validated as best they can by simple-schema:
- [x] $setOnInsert (treat this just like an insert)
- [x] $rename (make sure old name is not required and new name is in schema)
- [x] $addToSet (check allowed values and validate each item)
- [x] $push (check allowed values and validate each item)
- [x] $pushAll (deprecated but might still work?) (throw error)
- [x] $each (used with $push or $addToSet; probably remove the $each and treat like setting directly)

And all except $setOnInsert will probably need some extended validation added in the collection2 package.

**Comment by dandv** [comment]
Any chance to get a quick doc update for `setOnInsert`? It's not documented anywhere but it uses in the example at https://github.com/aldeed/meteor-collection2#autovalue.
